### ISSUE TITLE
Adding X-Vcap-Request-Id to access logs to enable correlation with router access logs

### ISSUE THREAD

**Issue by gberche-orange** [cloudfoundry/php-buildpack#10]
Thanks again Daniel for this great buildpack!

Following commits close to https://github.com/cloudfoundry/gorouter/pull/29 the gorouter now generates a `X-Vcap-Request-Id` (may be ultimately `X-Request-Id` ) in the HTTP header of requests send to apps and logs this request in the router access logs:

```
2014-05-16T14:10:10.80+0200 [RTR]     OUT php-info-gberche.cfapps.io - [16/05/2014:12:10:10 +0000] "GET /info.php?=PHPE9568F35-D428-11d2-A769-00AA001ACF42 HTTP/1.1" 200 2146 "http://php-info-gberche.cfapps.io/info.php" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:29.0) Gecko/20100101 Firefox/29.0" 10.10.2.122:62465 vcap_request_id:c8a81f5e-77d7-4d6e-7f99-288f07ee0345 response_time:0.004421576 app_id:65b6cb42-10b1-48f5-9722-e79df58c34ec
```

This enables correlation with more detailed access logging (or more confirming to common logging format) that could be done in apps, such as supported by the java-buildpack:

This is consistent with the heroku approach documented at https://devcenter.heroku.com/articles/http-request-id.

It would be great if the php buildpack could be logging the `X-Vcap-Request-Id` (or if missing `X-Request-Id`) to allow such correlation when run in CF and possibly in heroku.

Currently php buildpack logs with default nginx are of format:

```
2014-05-16T14:10:10.81+0200 [App/0]   OUT 12:10:10 nginx        | 193.252.157.49 - - [16/May/2014:12:10:10 +0000] "GET /info.php?=PHPE9568F34-D428-11d2-A769-00AA001ACF42 HTTP/1.1" 200 2536
```

**Comment by sureshreddygovindu** [comment]
@dmikusa-pivotal I would like to add my custom parameter into HTTP access logs and also I would like to parse access logs like **Key and Value** pair. like below. 
`[07/Mar/2018:16:39:28 -0500] [datacenter=local] [env=dev] [cluster=no] [logLevel=access] [[07/Mar/2018:16:39:28 -0500]:???c???] [app-name=xhAccountInfoPortal] ???X???{moneyTrace}  [MethodType=GET /img/account-information-logo.png HTTP/1.1] [uuuuu:/img/account-information-logo.png] [sssss:200] [bbb:1644] [kkk:0:0:0:0:0:0:0:1] [yyy:0.003] [useragent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.167 Safari/537.36] [referer=http://localhost:8080/xhAccountInfoPortal/portal/index]`

**Comment by dmikusa-pivotal** [comment]
@sureshreddygovindu - I think you're in the wrong place, this is for the PHP buildpack.
