### ISSUE TITLE
RFC: Drop nginx 1.6.3 from php-buildpack

### ISSUE THREAD

**Issue by flavorjones** [cloudfoundry/php-buildpack#109]
# Proposal to drop nginx 1.6.3 support

This issue describes a proposal to drop nginx 1.6.3 from the Cloud Foundry `php-buildpack`. The community is asked to comment on this proposal.

## The Challenge

Currently `php-buildpack` vendors three different versions of `nginx`:

* 1.9.5 ("Mainline")
* 1.8.0 ("Stable")
* 1.6.3 ("Legacy")

My understanding is that security updates will only be provided to "mainline" and "stable" releases.

## The Proposal

I'm proposing here to drop nginx 1.6.3 from the `php-buildpack`, since it appears to be unsupported upstream.

This would ideally be implemented no later than `php-buildpack` v4.1.6. (As of this writing, the current is 4.1.4 and [4.1.5 is being cut](https://www.pivotaltracker.com/story/show/105336604)).

## Action Items

Please comment on this ticket! If you're still using nginx 1.6.3 (likely by setting `NGINX_VERSION` in the app's `options.json` file), I'd like to know why, and know whether you'd be able to upgrade.

**Comment by dmikusa-pivotal** [comment]
What about taking it a step further and just shipping one version of Nginx?  Either mainline or stable, but probably stable.  From the perspective of hosting PHP apps, we use very few features in Nginx.  Running the stable release would probably be sufficient.

The only case where two versions would be nice is if there's a bug introduced, but if we're keeping previous maintenance releases of the branch you could switch back to one of those in the unlikely event of a bug.

Thoughts?

**Comment by shinji62** [comment]
I am agree you should dropped the legacy version and only keep stable and mainline, NGINX recommend the mainline anyway.

https://www.nginx.com/blog/nginx-1-6-1-7-released/

Btw I think is a good to force people to move forward on their nginx version.

**Comment by flavorjones** [comment]
@dmikusa-pivotal I agree that one version is probably ideal, and I intend to address that in the near future.

No objections having been raised, I'm going to schedule work on this change.
