### ISSUE TITLE
How to build another version PHP or change PHP.ini

### ISSUE THREAD

**Issue by feixuenet** [cloudfoundry/php-buildpack#112]
hey i just useing your PHP build and have some problem. I use **cf push -m 128M -b https://github.com/cloudfoundry/php-buildpack.git my-php-app** to push my app and i found that PHP don't have GD extension i need to change PHP.ini to add it
Also i want know if i can use HHVM to Instead apache？

**Comment by jtarchie** [comment]
@feixuenet you can use [PHP extensions](https://github.com/cloudfoundry/php-buildpack/blob/master/docs/config.md) without defining your own `php.ini` file.

In your application you can setup a `.bp-config/options.json` with a key `PHP_EXTENSIONS`, providing it the `gd` as an option. Here is the [default `options.json`](https://github.com/cloudfoundry/php-buildpack/blob/master/defaults/options.json).

As for HHVM, you should be able to specify `PHP_VM` to `hhvm` in your `options.json`. I don't recall if HHVM supports `gd` though.
