### ISSUE TITLE
PHP Tidy

### ISSUE THREAD

**Issue by decanus** [cloudfoundry/php-buildpack#120]
Quick question, does Tidy work with the php buildpack?

**Comment by aminjam** [comment]
@decanus: Acording to the [php docs for tidy](http://php.net/manual/en/tidy.installation.php), `configure` requires a `--with-tidy` flag. When we [compile our binaries](https://github.com/cloudfoundry/binary-builder/blob/master/recipe/php_meal.rb#L214-L260) we are not using that flag. If that's a requirement for your app, I would suggest generating a customized [PHP binary](https://github.com/cloudfoundry/binary-builder) and updating `manifest.yml` for your custom buildpack.

**Comment by decanus** [comment]
@aminjam Alright thanks.
