### ISSUE TITLE
Build pack installs PHP 5.4.45 when requested PHP 7

### ISSUE THREAD

**Issue by jornane** [cloudfoundry/php-buildpack#123]
My options.json reads `{"PHP_VERSION": "7.0.0"}`.

During deployment, I see:

```
Installing PHP
PHP 5.4.45
DEPRECATION WARNING: PHP 5.4 is being declared "End of Life" as of 2015-09-14
DEPRECATION WARNING: See https://secure.php.net/supported-versions.php for more details
DEPRECATION WARNING: Upgrade guide can be found at https://secure.php.net/manual/en/migration55.php
DEPRECATION WARNING: The php-buildpack will no longer support PHP 5.4 after this date
Downloaded [file:///var/vcap/data/dea_next/admin_buildpacks/789e7f71-f766-4dbf-88b5-c18b107ade50_781ff29342800240dace903bcc509c8167f85e34/dependencies/https___pivotal-buildpacks.s3.amazonaws.com_concourse-binaries_php_php-5.4.45-linux-x64-1442443195.tgz] to [/tmp]
```

So not only doesn't the build pack not support the latest and greatest version of PHP, it installs the oldest version it can get its hands on when you try. I would expect the build pack to either support the requested version, or abort with an error message.

**Comment by Dannyzen** [comment]
Hey @jornane thanks for putting in this issue. We're planning on supporting php version 7 soon. With regards to your issue of the buildpack reverting to the oldest version (5.4.45), I'm not able to reproduce this with the newest buildpack version (4.3.0)

**Comment by jornane** [comment]
Hi Danny. I tried again with the master version of the build pack. It uses version `php-5.5.30`, which seems to be the oldest version available. This is better than installing a EoL version, but it's still older than what I requested. I would like the build pack to fail when it can't handle the version requirement, instead of silently installing an older version.

**Comment by jvshahid** [comment]
@jornane where exactly is your `options.json` file located ? is it at the top level of the app ?

**Comment by RochesterinNYC** [comment]
Closing this issue due to lack of response. Please let us know if you require further assistance.
