### ISSUE TITLE
RFC: PHP 7 Support

### ISSUE THREAD

**Issue by Dannyzen** [cloudfoundry/php-buildpack#125]
# What

Proposed changes to the PHP buildpack to support PHP7

# Details

As community interest has been expressed for support of PHP7 we’ve completed preliminary work towards establishing an understanding of what a PHP7 Buildpack might include. These efforts have given us insight into the current state of supported packages and their compatibility with PHP7.

Below is a list of packages we currently support and their status regarding PHP7. We only intend to include packages that officially support PHP7, therefore packages for which do not explicitly support PHP7 will be removed. 

If you have any insight regarding the below list of packages or information that can assist us in verification PHP7 support, please comment on the issue.

# Does not officially support PHP7

Package Name        | Package Status                           | Notes                                                                      
--------------------|------------------------------------------|--------------------------------------------------------------------------- 
amqp                | Alpha Release                            | https://pecl.php.net/package-changelog.php?package=amqp 
memcached           | Open issue                               | https://github.com/php-memcached-dev/php-memcached/issues/199              
mongo pecl          | Superceded                               | https://pecl.php.net/package/mongo                                         
phalcon             | Closed issue                               | "It cannot work" [ref](https://github.com/phalcon/zephir/issues/756)                               
php-protobuff       | Open issue                               | https://github.com/allegro/php-protobuf/issues/46                          
phpiredis           | Open pull request                        | https://github.com/nrk/phpiredis/pull/39                                   
php-protocolbuffers | Unable to identify php7 support or plans |                                                                            
readline            | License issues                           |                                                                        
suhosin             | WIP                               | https://github.com/sektioneins/suhosin7                           
sundown             | Unable to identify php7 support or plans |                                                                            
twig                | Open issue                               | https://github.com/twigphp/Twig/issues/1695                                
xcachepecl          | Unable to identify php7 support or plans |                                                                            
xhprof              | Open issue                               | https://secure.phabricator.com/T9805            

# Officially supports PHP7

| Package Name | Package Status  | Notes | 
|--------------|-----------------|-------| 
| hiredis      | PHP 7 Supported |       | 
| msgpack      | PHP 7 Supported |       | 
| rabbitmq     | PHP 7 Supported |       | 
| yaf          | PHP 7 Supported |       |
| Mongodb Pecl | PHP 7 Supported | | 
| igbinary | PHP 7 Supported | |
| mailparser | PHP 7 Supported | |
imagick 3.4         | RC                                       | https://pecl.php.net/package-changelog.php?package=imagick| |
xdebug              | RC                                       | http://bugs.xdebug.org/changelog_page.php | |

Last Updated 4/04/16

**Comment by szepeviktor** [comment]
You may use a task list to keep track statuses.

- [x] @mentions, #refs, [links](), **formatting**, and <del>tags</del> are supported
- [x] list syntax is required (any unordered or ordered list supported)
- [x] this is a complete item
- [ ] this is an incomplete item

**Comment by RustJason** [comment]
For xhprof, How about try this one. https://github.com/RustJason/xhprof/tree/php7

**Comment by Dannyzen** [comment]
@RustJason thanks for commenting! I'm a little concerned including xhprof's php7 branch given the warning on the readme about using it in production.

**Comment by Dannyzen** [comment]
We'll be working on this issue this week with the goal of PHP7 support by Friday

**Comment by Dannyzen** [comment]
PHP7 support now exists as of [Release 4.3.5](https://github.com/cloudfoundry/php-buildpack/releases/tag/v4.3.5). We will keep this issue open in order to track progress of library support for PHP7.

**Comment by flavorjones** [comment]
Huzzah!

**Comment by RochesterinNYC** [comment]
@Dannyzen are we still keeping track of updates for individual library support of PHP7 in this issue?

**Comment by Dannyzen** [comment]
@RochesterinNYC indeed we are. Note the "last updated" date on the original post. We'll be including imagick and xdebug support for PHP 7 in the upcoming  release.

**Comment by jvshahid** [comment]
@Dannyzen can we close this issue now that the buildpack has been out for a while ?

**Comment by Dannyzen** [comment]
@jvshahid sure can. @community: If there are any additional questions please open a new issue
