### ISSUE TITLE
RFC: HHVM Support

### ISSUE THREAD

**Issue by Dannyzen** [cloudfoundry/php-buildpack#127]
# What
A request for feedback from the community regarding continued HHVM support.

# Details

Much like [Heroku](https://devcenter.heroku.com/articles/php-support#php-runtimes), the Cloudfoundry PHP buildpack has had experimental support for [HHVM](http://hhvm.com/). 

We'd like to understand if the team responsible for the PHP buildpack should continue to support HHVM and if so, what the benefits of HHVM are over PHP7. 

Our preference is to move forward with PHP7 and sunset support for HHVM. If you have a compelling reason for this buildpack to support HHVM please share them with our team. 

We will provide approximately __1 week__ for the conversation to take place in order to appropriately prioritize our [plans](https://github.com/cloudfoundry/php-buildpack/issues/125) for PHP7.

**Comment by flavorjones** [comment]
I'll place my vote as the Buildpacks PMC Lead: let's sunset HHVM support, and focus on PHP7.

Happy to discuss further, but this sounds like nobody sees a compelling reason to continue support for HHVM.

**Comment by Dannyzen** [comment]
We'll go forward with PHP7 and sunset HHVM. Work is planned to start next week. 

_So let it be written, so let it be done._
