### ISSUE TITLE
Broken link in README

### ISSUE THREAD

**Issue by nertzy** [cloudfoundry/php-buildpack#129]
This URL is now a 404:

https://www.cloudfoundry.org/learn/providers/

**Comment by jtarchie** [comment]
Thanks @nertzy. We'll take a look.

**Comment by jtarchie** [comment]
@nertzy should be resolved in this [commit](https://github.com/cloudfoundry/php-buildpack/commit/863f4adc32ca7727e88d54eef6fdae8ca0dada5d).
