### ISSUE TITLE
Additional module apache integration

### ISSUE THREAD

**Issue by keyser-fr** [cloudfoundry/php-buildpack#134]
Hello all,

I'd like to know how add a module extension for apache into buildpack PHP.

Indeed, I'd like add mod_security into
php-buildpack/defaults/config/httpd/extra/httpd-modules.conf

In other term, I'd like to know how build tarball image mentioned in manifest.yml file ?
uri: https://pivotal-buildpacks.s3.amazonaws.com/concourse-binaries/httpd/httpd-2.4.18-linux-x64.tgz

Thanks & have a good day ;)

**Comment by jtarchie** [comment]
We build all binaries for the buildpacks using these [build scripts](https://github.com/cloudfoundry/binary-builder). They help us valid source, checksums, etc. This [recipe](https://github.com/cloudfoundry/binary-builder/blob/master/recipe/httpd_meal.rb) pertains to HTTPD.

**Comment by keyser-fr** [comment]
Thanks a lot for your answer. ;)

**Comment by jtarchie** [comment]
@keyser-fr, let us know if you need anything else.

**Comment by keyser-fr** [comment]
@jtarchie, ok no problem.

I search the best solution for mod_security integration.
However, now I have a starting point.
Thanks again.
