### ISSUE TITLE
PHP build pack compilation error

### ISSUE THREAD

**Issue by bootstraap** [cloudfoundry/php-buildpack#135]
Hi ,

I am getting below error while pushing PHP app based on symfony framework, could you please help me with it : 

I am executing below command:
cf push -f manifest-tai-prod.yml -b https://github.com/cloudfoundry/php-buildpack.git#v4.3.5

-----> Downloaded app package (33M)
    Cloning into '/tmp/buildpacks/php-buildpack'...
Note: checking out '5b1ee33b56cbdb7ed3cdf1de5e59ca4bd7a37c49'.
You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.
If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:
  git checkout -b new_branch_name
    Submodule 'compile-extensions' (https://github.com/cloudfoundry/compile-extensions) registered for path 'compile-extensions'
Cloning into 'compile-extensions'...
Submodule path 'compile-extensions': checked out '9932bb1d352b88883d76df41e797a6fa556844f0'
-------> Buildpack version 4.3.5
Traceback (most recent call last):
  File "/tmp/buildpacks/php-buildpack/scripts/compile.py", line 49, in <module>
    .from_build_pack('lib/additional_commands')
  File "/tmp/buildpacks/php-buildpack/lib/build_pack_utils/builder.py", line 223, in done
    process_extension(extn, self._builder._ctx, 'configure', process)
  File "/tmp/buildpacks/php-buildpack/lib/build_pack_utils/utils.py", line 69, in process_extension
    success(getattr(extn, to_call)(*args))
  File "/tmp/buildpacks/php-buildpack/extensions/composer/extension.py", line 387, in configure
    config.configure()
  File "/tmp/buildpacks/php-buildpack/extensions/composer/extension.py", line 139, in configure
    php_version = self.read_version_from_composer('php')
  File "/tmp/buildpacks/php-buildpack/extensions/composer/extension.py", line 117, in read_version_from_composer
    composer = json.load(open(json_path, 'r'))
  File "/usr/lib/python2.7/json/__init__.py", line 290, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting , delimiter: line 67 column 9 (char 2767)
Staging failed: Buildpack compilation step failed

**Comment by dmikusa-pivotal** [comment]
It looks like it's having trouble reading your composer.json file.  Can you attach it?

**Comment by bootstraap** [comment]
Hi,

As requested below is my composer.json file

`{
    "name": "catalog",
    "license": "proprietary",
    "type": "project",
    "description": "The product catalog service",
    "autoload": {
        "psr-0": { "": "src/", "SymfonyStandard": "app/" }
    },   
    "require": {
        "php": ">=5.4",
        "symfony/symfony": "2.6.*",
        "doctrine/orm": "~2.2,>=2.2.3",
        "doctrine/doctrine-bundle": "~1.2",
        "twig/extensions": "~1.0",
        "symfony/monolog-bundle": "~2.4",
        "sensio/distribution-bundle": "~3.0.12",
        "sensio/framework-extra-bundle": "~3.0",
        "incenteev/composer-parameter-handler": "~2.1.2",

        "nelmio/api-doc-bundle": "~2.4",
        "stof/doctrine-extensions-bundle": "~1.1",
        "willdurand/negotiation": "@stable",
        "doctrine/doctrine-fixtures-bundle": "2.2.0",
        "nelmio/cors-bundle": "~1.3",
        "willdurand/hateoas-bundle": "~0.5",
        "doctrine/migrations": "1.0.*@dev",
        "doctrine/doctrine-migrations-bundle": "~1.0.1",
        "ramsey/uuid": "~2.8"
    },
    "require-dev": {
        "sensio/generator-bundle": "~2.3",
        "phpunit/phpunit": "~4.2",
        "liip/functional-test-bundle": "1.0.2",
        "pinkfire/pinkfire-bundle": "~1.0.0",
        "sami/sami": "~3.0"
    },
    "scripts": {
        "post-root-package-install": [
            "SymfonyStandard\\Composer::hookRootPackageInstall"
        ],
        "post-install-cmd": [
            "Incenteev\\ParameterHandler\\ScriptHandler::buildParameters",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::buildBootstrap",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::clearCache",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installAssets",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installRequirementsFile",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::removeSymfonyStandardFiles"
        ],
        "post-update-cmd": [
            "Incenteev\\ParameterHandler\\ScriptHandler::buildParameters",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::buildBootstrap",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::clearCache",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installAssets",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installRequirementsFile",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::removeSymfonyStandardFiles"
        ]
    },
    "config": {
        "bin-dir": "bin"       
    },
    "extra": {
        "symfony-app-dir": "app",
        "symfony-web-dir": "web",
        "symfony-assets-install": "relative",
        "incenteev-parameters": {
            "file": "app/config/parameters.yml",
            "dist-file": "app/config/parameters.yml.dist",
            "env-map": {
                "database_driver": "SYMFONY__DATABASE_DRIVER",
                "database_host": "SYMFONY__DATABASE_HOST",
                "database_port": "SYMFONY__DATABASE_PORT",
                "database_name": "SYMFONY__DATABASE_NAME",
                "database_user": "SYMFONY__DATABASE_USER",
                "database_password": "SYMFONY__DATABASE_PASSWORD",
                "locale": "SYMFONY__LOCALE",
                "secret": "SYMFONY__SECRET"               
            }
        },
        "branch-alias": {
            "dev-master": "2.6-dev"
        }
    }
}
`

**Comment by dmikusa-pivotal** [comment]
Huh.  Python seems to be able to read that.  At least on my local machine.  Can you send me a simple test app I can push to replicate this?

**Comment by RochesterinNYC** [comment]
@bootstraap are you still experiencing this issue? If so, could you please post a gist or something similar with a simple test app reproducing the issue? Thanks!

**Comment by RochesterinNYC** [comment]
Closing due to lack of response. Please let us know if you require further assistance.
