### ISSUE TITLE
PHP build pack paramters.yml.dist file not found error 

### ISSUE THREAD

**Issue by bootstraap** [cloudfoundry/php-buildpack#136]
Hello

I am trying to push PHP app based on symfony framework. I am getting below error while pushing the app

``Installing PHP
PHP 5.5.32
Downloaded [https://pivotal-buildpacks.s3.amazonaws.com/concourse-binaries/php/php-5.5.32-linux-x64-1455291679.tgz] to [/tmp]
Downloaded [https://pivotal-buildpacks.s3.amazonaws.com/concourse-binaries/php/php-5.5.32-linux-x64-1455291679.tgz] to [/tmp]
Downloaded [https://pivotal-buildpacks.s3.amazonaws.com/php/binaries/trusty/composer/1.0.0-alpha11/composer.phar] to [/tmp]
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   283  100   283    0     0    673      0 --:--:-- --:--:-- --:--:--   672
Loading composer repositories with package information
Installing dependencies from lock file
  - Removing sensio/generator-bundle (v2.5.3)
Generating autoload files
> Incenteev\ParameterHandler\ScriptHandler::buildParameters
Script Incenteev\ParameterHandler\ScriptHandler::buildParameters handling the post-install-cmd event terminated with an exception
  [InvalidArgumentException]
  The dist file "app/config/parameters.yml.dist" does not exist. Check your dist-file config or create it.
install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-plugins] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [-v|vv
|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--ignore-platform-reqs] [--] [<packages>]...
Traceback (most recent call last):
  File "/tmp/buildpacks/php-buildpack/scripts/compile.py", line 49, in <module>
    .from_build_pack('lib/additional_commands')
  File "/tmp/buildpacks/php-buildpack/lib/build_pack_utils/builder.py", line 189, in extensions
    process_extension(path, ctx, 'compile', process, args=[self])
-----> Composer command failed
  File "/tmp/buildpacks/php-buildpack/lib/build_pack_utils/utils.py", line 69, in process_extension
    success(getattr(extn, to_call)(*args))
  File "/tmp/buildpacks/php-buildpack/extensions/composer/extension.py", line 407, in compile
    return composer.compile(install)
  File "/tmp/buildpacks/php-buildpack/lib/extension_helpers.py", line 154, in compile
    self._compile(install)
  File "/tmp/buildpacks/php-buildpack/extensions/composer/extension.py", line 174, in _compile
    self.run()
  File "/tmp/buildpacks/php-buildpack/extensions/composer/extension.py", line 309, in run
    *self._ctx['COMPOSER_INSTALL_OPTIONS'])
  File "/tmp/buildpacks/php-buildpack/extensions/composer/extension.py", line 353, in run
    shell=True)
  File "/tmp/buildpacks/php-buildpack/lib/build_pack_utils/runner.py", line 109, in stream_output
    raise CalledProcessError(retcode, cmd)
build_pack_utils.runner.CalledProcessError: Command '<open file '<fdopen>', mode 'w' at 0x7ff506159810>' returned non-zero exit status 1
Staging failed: Buildpack compilation step failed

FAILED
BuildpackCompileFailed``

TIP: use 'cf.exe logs blog --recent' for more information`

**Comment by dmikusa-pivotal** [comment]
This looks like you're telling composer to run something for you at build time and whatever is supposed to run is failing.

```
Incenteev\ParameterHandler\ScriptHandler::buildParameters handling the post-install-cmd event terminated with an exception [InvalidArgumentException] The dist file "app/config/parameters.yml.dist" does not exist. Check your dist-file config or create it.
```

You might have the wrong path to the file.  Your app is going to exist at `/home/vcap/app`, depending on how your app is setup and what options you send to the build pack, your app files may or may not be in the docroot for the web server, which defaults to `htdocs` but could be anything if you're setting the value in options.json.

If you want to look at the directory structure the build pack sets up, deploy a simple test app and run `cf ssh` to look around the container.

**Comment by flavorjones** [comment]
@bootstraap - We're closing this issue because we believe Dan Mikusa provided the answers you needed. If you still need help, please comment here and we'll do what we can to help.
