### ISSUE TITLE
Enforce SSL nginx Bluemix

### ISSUE THREAD

**Issue by alensaqe** [cloudfoundry/php-buildpack#138]
How can i enforce ssl from a custom domain from bluemix without forking a repo and changing the nginx.conf i have been viewing this repo and there is the file php-buildpack/defaults/config/nginx/http-php.conf that maps the traffic 

    # set $https only when SSL is actually used.
    map $http_x_forwarded_proto $proxy_https {
        https on;
    }

Thanks in advance
PS: i am new to nginx.

Edit:

I have opened a ticked in here as well https://developer.ibm.com/answers/questions/257276/redirect-traffic-from-http-to-https-with-php-build/ 

If we solve this i will update the ticket there as well.

**Comment by dmikusa-pivotal** [comment]
Two ways:

1.) In your app code
2.) Include a custom config for Nginx.  See [here](https://github.com/cloudfoundry/php-buildpack/blob/master/docs/config.md#httpd-nginx-and-php-configuration)

**Comment by alensaqe** [comment]
This might work .bp-config/nginx/server-defaults.conf will do the trick. I just figured out bp stand for buildpack. Thank you @dmikusa-pivotal
