### ISSUE TITLE
Large File upload in PHP

### ISSUE THREAD

**Issue by sridhar2392** [cloudfoundry/php-buildpack#139]
When i try to upload a file of big size in PHP- Bluemix application, it is throwing me the following error. 

**> Service Unavailable**

> The  server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.

I referred [this](https://developer.ibm.com/answers/questions/193136/occasionally-getting-service-unavailable-when-tryi.html) forum on how to rectify this issue but I couldn't find a way to modify it. Is it something like option.json where we have to upload or do we have to edit the settings in Bluemix itself. 

If so then how to do it ?

**Comment by dmikusa-pivotal** [comment]
The default values for php.ini and php-fpm.conf try to be good for most applications, but can need adjusted on occasion.  You can do that in your application by including a custom configuration file.

See the docs here:  https://github.com/cloudfoundry/php-buildpack/blob/master/docs/config.md#httpd-nginx-and-php-configuration

**Comment by sridhar2392** [comment]
So for the service unavailable error, should I edit php.ini file or php-fpm.conf file ?

**Comment by dmikusa-pivotal** [comment]
The forum post you linked to says php-fpm.conf.

**Comment by sridhar2392** [comment]
When I configure the php-fpm.conf and push it , the instance is getting crashed. But when I try to push only php.ini file it is not. It just happens with php-fpm.conf. 
I placed both the files like the following
->.bpconfig    // 1st level
  ->options.json     // 2nd level
  ->PHP                // 2nd level
       ->php.ini              // 3rd level
       ->php-fpm.conf   // 3rd level

Where am I going wrong?   Also Need to know the parameters that I should change in php-fpm.conf so that I don't have to disturb the other parameters. I'm at loss here..  :'(

**Comment by dmikusa-pivotal** [comment]
>->.bpconfig // 1st level

You're missing a `-`.  It should be `.bp-config`

>->PHP (folder) // 2nd level

Make this lower case.  i.e.  `.bp-config/php/php.ini` and `.bp-config/php/php-fpm.conf`.

>Also Need to know the parameters that I should change in php-fpm.conf

I can't tell you that as I haven't debugged your problem, but it seems like the link you posted originally has some suggestions.  I would start by implementing those.

>so that I don't have to disturb the other parameters.

This is not possible.  When you include a custom config with your application it completely overrides the default `php.ini` or `php-fpm.conf` that come with the build pack.  What you should do is get a copy of the default, put that into your `.bp-config/php` folder and then edit as necessary.

Defaults are here:  https://github.com/cloudfoundry/php-buildpack/tree/master/defaults/config/php

Pick the one appropriate for your version of PHP.

Note:  there are some place holders in the config files, like `@{HOME}` and `#{WEBDIR}`.  Anything beginning with `@{..}` gets replaced at runtime (basically environment variables) and anything with `#{..}` gets replaced during staging (from the staging context).

**Comment by sridhar2392** [comment]
I checked my Log and it says as follows: 

> 2016-03-24T16:26:28.151+0530

> [App/0]

> out

> 10:56:28 httpd | [Thu Mar 24 10:56:28.142067 2016] [proxy_fcgi:error] [pid 58:tid 140412522055424] (70007)The timeout specified has expired: [client 168.1.44.88:16234] AH01075: Error dispatching request to : (polling), referer: http://dmrtcheck.au-syd.mybluemix.net/
> 2016-03-24T16:26:28.151+0530
> [App/0]
> out
> 10:56:28 httpd | 168.1.44.88 - - [24/Mar/2016:10:55:28 +0000] "POST /upload.php HTTP/1.1" 503 299 vcap_request_id=24dd3c5

> 
1-6619-45c5-7f49-544726535776 peer_addr=168.1.44.88

So i can tell is has something to do with request time out. I also have made those changes that you have mentioned but still no luck

**Comment by dmikusa-pivotal** [comment]
This looks like HTTPD is timing out.  You might want to raise the Timeout.

https://github.com/cloudfoundry/php-buildpack/blob/master/defaults/config/httpd/extra/httpd-default.conf#L1

Or add a [ProxyTimeout](https://httpd.apache.org/docs/2.4/mod/mod_proxy.html#proxytimeout).  ProxyTimeout is probably the better option.

**Comment by dmikusa-pivotal** [comment]
For what it's worth, these aren't build pack questions.  They're just general HTTPD & PHP tuning questions.  You're probably better asking about them on an HTTPD or PHP forum / mailing list.

**Comment by sridhar2392** [comment]
Thank you for the help.
