### ISSUE TITLE
Buildpack detects ASP.Net projects as PHP projects

### ISSUE THREAD

**Issue by degrim** [cloudfoundry/php-buildpack#141]
The buildpack is looking recursively through the directory structure for a file called 'composer.json' which leads to it detecting ASP.Net projects using Bower packages that contain this file.  Those files are located under 'wwwroot/scripts/lib/*/composer.json'.

**Comment by flavorjones** [comment]
As discussed on cf-dev, `bin/detect` is recursively searching the entire project directory hierarchy looking for a file named `composer.json`.

We should limit this search to the few places where it's reasonable for a PHP app to place `composer.json`. We may need help from @dmikusa-pivotal and the PHP community to determine the smallest sufficient set of locations.

**Comment by dmikusa-pivotal** [comment]
We made this change for the composer extension in the build pack a while ago.

https://github.com/cloudfoundry/php-buildpack/blob/master/extensions/composer/extension.py#L34-L69

I think the detect script just fell through the cracks.  We should update that so it searches similarly.

**Comment by Dannyzen** [comment]
@degrim Thanks for bringing our attention to this issue. It should now be fixed as of [php-buildpack 4.3.10](https://github.com/cloudfoundry/php-buildpack/releases/tag/v4.3.10)
