### ISSUE TITLE
Compression & Cache (etag) not enabled, modules not loaded

### ISSUE THREAD

**Issue by arsenyspb** [cloudfoundry/php-buildpack#142]
I may have misunderstood the structure, but I believe the buildpack doesn't load anything related to compression and caching.

As per best-practice test-case of Google, when pushed the semi-static app to BlueMix, then parsed it via: https://developers.google.com/speed/pagespeed/insights/?url=try-the-buildpack-here.mybluemix.net

**Comment by dmikusa-pivotal** [comment]
I don't think this happens automatically (i.e. out of the box).  Your app would need to set these headers or you'd need to configure HTTPD to do this for you.

You can set a custom HTTPD config here or you can use a .htaccess file.

https://github.com/cloudfoundry/php-buildpack/blob/master/docs/config.md#httpd-nginx-and-php-configuration

I don't know Nginx as well, but I'd suspect it has similar configuration options available.

**Comment by arsenyspb** [comment]
Why do you think it's not a good idea to load mod_deflate and enable compression by default? This is best practice AFAIR.

**Comment by hairmare** [comment]
I'm using the nginx/fpm combo and had no issues with enabling compression by overriding the nginx config through `.bp-config/nginx/server-locations.conf`.

We did have some (unrelated) issues while deploying that, so I ended up creating a simple test app that verfies that it actually works: https://github.com/hairmare/cf-ex-php-compression.

Since mod_deflate is part of apache core you should probably be able to do something similar as long as you base your override on the default file in https://github.com/cloudfoundry/php-buildpack/tree/master/defaults/config/httpd. You can copy just the files you want to change to your local `.bp-options/httpd` folder and it will override the buildpacks defaults.

**Comment by dmikusa-pivotal** [comment]
>Why do you think it's not a good idea to load mod_deflate and enable compression by default? This is best practice AFAIR.

I'm not going to say if it's a good or bad thing to do that.  What I can tell you is the rationale behind the current defaults.

One of my main goals when I wrote the build pack was to disable as much as possible in HTTPD to keep the memory foot print low.  Less memory required by HTTPD, more memory for your PHP apps, and in some CF installations memory == money, so the more efficient we can be out of the box the less money it costs to run your apps.  HTTPD has a certain reputation when it comes to memory but if configured correctly it can run very efficiently in a small amount of memory.  The defaults try to limit the number of modules that are loaded as this helps to limit the memory required.  

The secondary goal of the build pack is flexibility.  I knew that the defaults wouldn't work for everyone, so I wanted it to be possible for app devs to customize and change them to their needs.  

When you put these two goals together it makes sense to start with a bare minimum and allow people to turn on things that are important to them.  You can do that at the application level, or if you have lots of apps you could consider a fork of the build pack to enable say a company specific set of defaults.  Just fork with caution as it means you have to forever merge in upstream changes and keep your build pack up-to-date.

So while that was my main rationale, I also had a secondary concern that I didn't want to step on the toes of the application.  There's a lot of different ways to do things in PHP so I didn't want to force something at the build pack level that conflicts with the way a framework or application does things.  Again, it made sense to have the build pack do as little as possible and provide ways for users to easily enable features.

As @hairmare pointed out, you can easily override the HTTPD or Nginx config to enable this for your app.  If you're using HTTPD you can also use `.htaccess` file to override the config.  This is a more standard way of overriding HTTPD config that's not specific to CF.  You'll see a lot of frameworks and large apps (i.e. Wordpress) ship with these out of the box.

Having said all that, it may make sense to enable additional configuration or change the defaults, but before we do that I think discussion on the changes needs to occur.  Topics for discussion:  what are the use cases for the change, can these use cases be met with the existing options, what are the drawbacks of the existing options, how does this impact existing users, are there any backwards compatibility concerns?  Ideally we'd get some general support for the change from others in the community.

**Comment by flavorjones** [comment]
If it's worth comparing what we've done in other buildpacks; in the staticfile-buildpack we configure nginx to compress by default, but we decided *not* to enable caching to make sure the default config was low on memory.

I'd vote to turn on compression, but I still think caching should be something that must be opted-in.

**Comment by arsenyspb** [comment]
Understood on the resource footprint, but if you think about it, the
overall picture with compression turned on is not RAM is more of CPU
matter, -- and instances are losing revenue (not cost) due to excessive RTT
to mobile clients, to serve uncompressed content (even minimized JS and
CSS)... then it makes small sense to ship *without* compression, especially
with CPU cost bias, not RAM. Quick google search reveals articles that say:

*Enabling mod_deflate can reduce the bandwidth usage on a particular file
by up to 70%, but also reduces the maximum load a server can handle and may
actually reduce site performance if the site compresses large dynamic
files.*

I agree with Mike that caching on php-buildpack probably isn't worth
enabling, since there's a staticfile-buildpack, but default compression on
php-biuldpack definitely gets my vote since it's a best-practice
_generally_.

Maybe worth downgrading my expectation on default caching. But clearly
default compression on, please?..

On 30 March 2016 at 08:02, Mike Dalessio <notifications@github.com> wrote:

> If it's worth comparing what we've done in other buildpacks; in the
> staticfile-buildpack we configure nginx to compress by default, but we
> decided *not* to enable caching to make sure the default config was low
> on memory.
>
> I'd vote to turn on compression, but I still think caching should be
> something that must be opted-in.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/cloudfoundry/php-buildpack/issues/142#issuecomment-203148021>
>



-- 
Regards,
Arseny Chernov
arseny.chernov@gmail.com

**Comment by dmikusa-pivotal** [comment]
As I mentioned above I'm not arguing for or against, just trying to provide some historical context.  Personally I'm +0, I think there's arguments for and against, but if other build packs are doing it by default, that's good enough for me.  -1 on caching as well.

I think there's probably some room for debate on how this is configured.  It needs to work across Nginx, HTTPD and for dynamic content generated by PHP.  It probably also needs to exclude content that's already compresses like images, movies and pre-compressed files, since recompressing that is a waste.

HTTPD's mod_deflate is one way, but there's also [ob-gzhandler](http://php.net/manual/en/function.ob-gzhandler.php) in PHP.

**Comment by flavorjones** [comment]
I'm in favor of turning on compression by default.

**Comment by arsenyspb** [comment]
Hello,

I tried building version off php-buildpack with compression enabled, but after several attempts it still didn't work out. I believe I'm missing out the details of how php-buildpack is structured.

Is there anyone who can instruct myself, or, rather, create a wiki subsection on building a variant with compression?

**Comment by arsenyspb** [comment]
Hey there, anyone keen to expand wiki on build-your-own intruction off this great buildpack, to switch on _at_least_ compression as an opt-in?..

**Comment by dmikusa-pivotal** [comment]
>I tried building version off php-buildpack with compression enabled, but after several attempts it still didn't work out. I believe I'm missing out the details of how php-buildpack is structured.
>Is there anyone who can instruct myself, or, rather, create a wiki subsection on building a variant with compression?

You don't need to build anything.  You just need to configure HTTPD to use compression.  Doing that is outside the scope of the support I can give you hear, but you can probably google how to do it or research in the HTTPD manual.

Once you know what configuration needs to change, you can override the build pack default configuration by including configuration with your application.  

Instructions here:  https://github.com/cloudfoundry/php-buildpack/blob/master/docs/config.md#httpd-nginx-and-php-configuration

I haven't looked at Nginx to know if it has the right support compiled into it for compression.  It might be similar to HTTPD and you just need to add config options to enable compression or Nginx might actually need to be recompiled with the right options enabled to support compression.  If it's the latter, that would be more difficult.

**Comment by davidjahn** [comment]
@dmikusa-pivotal On a related note, there are actually issues with enabling compression by default on HTTPD with the php-buildpack, i.e it doesn't work. It may have to do with interactions between the httpd `mod_deflate.so` and the `fcgi` module, but we're currently investigating the issue.

Compression is enabled by default in nginx for the php buildpack, and we validated that it is functioning.

**Comment by Dannyzen** [comment]
Hi there! We've committed changes to the develop branch to support compression as the default. Currently, the PHP buildpack supports etag support for static (.html) files. We'd like to better understand the use case for etag support for dynamic (.php) files.

**Comment by geramirez** [comment]
@dmikusa-pivotal Do you still want to discuss ETAG support for dynamic files? If not we will close this out.

**Comment by dmikusa-pivotal** [comment]
Feel free to close this out.  I think it's great the way you've got it set now.  ETAGs for static content only.  Users / apps can decide when and how to set ETAGs for dynamic content.

Dan

**Comment by jvshahid** [comment]
Sounds good. Closing issue.
