### ISSUE TITLE
pre-install-cmd/post-install-cmd scripts declared in composer.json fail to run 

### ISSUE THREAD

**Issue by joshisa** [cloudfoundry/php-buildpack#143]
Using PHP Buildpack v4.3.8, we have noticed that our project's composer.json (scripts section) pre-install-cmd and post-install-cmd entries are ignored.  Possibly a bug or behavior change resulting from the update of composer to 1.0.0-beta2 . This syntax works fine in v4.3.7 and earlier.

I've attached [unit-testing-hello-world-php.zip](https://github.com/cloudfoundry/php-buildpack/files/203048/unit-testing-hello-world-php.zip) :: a sample CF project that clearly replicates the problem using a minimal php hello-world application.

2 Files within the zip to inspect:
  post-install-cmd-trace-v4_3_7.txt :: stdout capture illustrating pre/post install commands executing.
  post-install-cmd-trace-v4_3_8.txt :: stdout capture with no command activity.

**Comment by RochesterinNYC** [comment]
@joshisa According to Composer's documentation about pre and post install commands, a `composer.lock` file is required for these commands to run. The app you linked does not seem to have a `composer.lock` file. Could you try creating a `composer.lock` file via `composer install` and see if the issue still persists? Thanks.

**Comment by jvshahid** [comment]
closing this issue. @joshisa feel free to comment if you are still having an issue after trying to push with a lock file.
