### ISSUE TITLE
Mod security support

### ISSUE THREAD

**Issue by gberche-orange** [cloudfoundry/php-buildpack#144]
Our company (Orange) has the need to execute [mod security](https://www.modsecurity.org/) into applications staged with the php buildpack in order for security automated processes to be warned about incoming suspicious traffic. Some use-cases include running default OWASP rules that send warnings for suspicious traffic (such as SQL injection or XSS queries) on stdout/stderr which are then streamed using syslog to a central security event processing store (using the usual loggregator syslog support).

More about mod_security into https://modsecurity.org/about.html and https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual

Orange has prepared mod_sec support in the following two branches:
* https://github.com/Orange-OpenSource/binary-builder/tree/modsecurity
* https://github.com/Orange-OpenSource/php-buildpack/tree/modsecurity_rebased

We're wondering whether such support could be of interest to the CF community, and what would be required improvements for these two branches to be ready to be submitted as PRs  ?

Some additional detail about current status of this work:

* The latest mod_security version  (2.9.1) was used for both the module sources (https://github.com/SpiderLabs/ModSecurity) and the default [OWASP rules](https://www.owasp.org/index.php/Category:OWASP_ModSecurity_Core_Rule_Set_Project) (2.2.9 from https://github.com/SpiderLabs/owasp-modsecurity-crs/tree/master/base_rules) . This requires httpd 2.4.20 for compiling the mod_security sources (seems weird that integration tests [still reference 2.4.17](https://github.com/cloudfoundry/binary-builder/blob/73c9440b9674f31975a4b7eef06ccb54d025f3cd/spec/integration/httpd_spec.rb#L8-L9), fixed that) as well as adding the yajl library (version 2.1.0) used to output JSON formatted. 
* mod_security was integrated only for httpd. Nginx support is also a possible option we did not work on.
* The mod_security module is disabled by default (this is to avoid performance impacts and extra warning for users not wishing to receive them)
* The default mod_security configuration and security rules can be overriden on an app per app basis in the .bpconfig. This is currently proposed in a new buildpack extension (alternatively this could have been done by modifying the [httpd core support](https://github.com/cloudfoundry/php-buildpack/blob/761d1d9ea051174d3ec806130752e1b7ee5c3545/lib/httpd/extension.py#L42-L49)).
* The module is configured to output logs to stdout using "|/usr/sbin/tee". We observed that diego is currently splitting outputted lines after ~4 Kb. The following [diego story](https://www.pivotaltracker.com/n/projects/1003146/stories/111866195) should increase lengths of unsplitted lines to 60 Kb, which should be large enough for most mod_security warning logs.
* Some default security rules currently write to /tmp paths which may need to be customized to cflinux2rootfs layout and use $TMP_DIR instead.
* We don't yet have refined the integration tests to validate the mod_security module is properly loaded.
* We have not yet run the machete tests to validate potential regressions.
* We are yet lacking the documentation section to document support for mod_security and on how to [enable mod_security](https://github.com/cloudfoundry/php-buildpack/blob/master/docs/config.md#httpd-nginx-and-php-configuration) (need to enable both for mod_security and mod_unique_id) in .bpconfig/httpd/extra/httpd-modules.conf
   * The mod_security configuration and security rules can be overriden on an app per app basis in the .bpconfig.

Thanks in advance for your help,

Guillaume and David.

/CC @bonfilsd @ArthurHlt

**Comment by Dannyzen** [comment]
Hey @gberche-orange thanks for putting in an issue. We do think the idea is interesting but have not received any requests for the functionality and do not have the resources to support and maintain it. 

We would suggest you fork the php-buildpack, implement and maintain mod security support, and submit it to the cloudfoundry-incubator to obtain community feedback.

**Comment by gberche-orange** [comment]
thanks @Dannyzen for your response. We'll try maintaining a public fork of the php-buildpack and an associated ci.
