### ISSUE TITLE
/defaults/options.json not updated for PHP 7.0.6

### ISSUE THREAD

**Issue by BrainOfJ** [cloudfoundry/php-buildpack#149]
Someone forgot to update the PHP_70_LATEST key in options.json from "7.0.5" to "7.0.6".
I've confirmed manually overriding it on .bp-config/options.json deploys the correct version, so it's a minor issue.

**Comment by Dannyzen** [comment]
Thanks @BrainOfJ this is now in develop and should ship in an upcoming version of the PHP buildpack.

**Comment by Dannyzen** [comment]
I stand corrected, we'll be shipping with 7.0.7 in the next buildpack.
