### ISSUE TITLE
Removing nginx 1.9.x from PHP Buildpack and making nginx 1.11.2 default

### ISSUE THREAD

**Issue by Dannyzen** [cloudfoundry/php-buildpack#153]
Hi there,

In order to patch a [CVE Vulnerability](http://nginx.org/en/security_advisories.html) the CF Buildpacks team will be updating the PHP buildpack to include nginx 1.11.1 as the default version of Nginx.
 
In order to support use cases where nginx v1.9.15 are in use we have created a 30 day window in which this version will be kept in the PHP buildpack. It's notable to mention that nginx 1.8 has been scheduled to be removed in the next release (v.4.3.14) due this week. This notification was originally [posted May 17th](https://lists.cloudfoundry.org/archives/list/cf-dev@lists.cloudfoundry.org/message/WXP6PFYJDGIUZURCGID6DQE3KPSSGM67/).

If you need help migrating from 1.8.x or 1.9.x please feel free to contact us on our [public slack channel.](https://github.com/cloudfoundry/php-buildpack#help-and-support)

Note: As of 7/6 we've decided to change 1.11.1 to 1.11.2. For more information, see comment in thread.

**Comment by flavorjones** [comment]
For the record, I'd like to +1 this proposal to remove 1.9.x since it's no longer receiving security updates.

**Comment by ForestEckhardt** [comment]
Nginx 1.9.15 has been removed.

**Comment by geramirez** [comment]
For clarification, we'll be removing the nginx 1.9.x line on July 1, 2016.

**Comment by Dannyzen** [comment]
Nginx 1.11.2 arrived yesterday and in the interest of keeping the buildpack up to date with the latest releases we've opted to include 1.11.2 in the PHP buildpack instead of 1.11.1.

For information on changes made to nginx please see [nginx.org/changes](http://nginx.org/en/CHANGES)

**Comment by Dannyzen** [comment]
In addition, we'll be sticking to the same versioning precedent we've used in the past. The buildpack will include 1 nginx stable version and 1 nginx mainline version. As of the time of this comment, those would be:
Stable: 1.10.1
Mainline: 1.11.2

**Comment by jchesterpivotal** [comment]
For the interest of followers, [a story has been scheduled](https://www.pivotaltracker.com/story/show/124860331) for the 1.11.2 upgrade. As part of the work on that story, [1.9 has been removed from our development version](https://github.com/cloudfoundry/php-buildpack/commit/1ef27cc7b2b5fc30b3b07d07a62715f01efbff06). 

This change should surface for users at the [next PHP buildpack release](https://www.pivotaltracker.com/story/show/125871661), which we expect this week.
