### ISSUE TITLE
ioncube support?

### ISSUE THREAD

**Issue by dmikusa-pivotal** [cloudfoundry/php-buildpack#154]
What version of Cloud Foundry are you using?

PWS

What version of the buildpack you are using?

v4.3.15+

If you were attempting to accomplish a task, what was it you were attempting to do?

The release notes stop indicating that ioncube is supported by the build pack after v4.3.15.  Is this expected?  Was it discontinued for a particular reason?

It seems like binary-builder is still has a recipe for it.

https://github.com/cloudfoundry/binary-builder/blob/master/recipe/php5_meal.rb#L288-L290

Thanks

**Comment by RochesterinNYC** [comment]
Looks like PHP is still baking in ioncube? https://github.com/cloudfoundry/binary-builder/blob/master/recipe/php5_meal.rb#L158

The release notes are based off the modules key of each PHP dependency in the PHP Buildpack manifest, and that's populated via this: https://github.com/cloudfoundry/php-buildpack/blob/master/bin/populate-modules-in-manifest

So it's possible that the ioncube.so file is no longer present in the internal php directory it's looking for extensions in (https://github.com/cloudfoundry/php-buildpack/blob/master/bin/populate-modules-in-manifest#L11). This sounds fishy though as it used to be in the module list. I think this bears further investigation.

**Comment by dmikusa-pivotal** [comment]
For what it's worth, I pushed an app on PWS last night and looked for the extension file.  It wasn't present in the PHP extensions folder.

Also, and this is the reason I bring this up, when I was working with the builder recently I noticed some errors from the PHP 5.6 build related to ioncube.  I didn't have time to look into this more though.

**Comment by RochesterinNYC** [comment]
Verified that ioncube was not being included in the built php binaries properly. It should be fixed by the following change in binary-builder: https://github.com/cloudfoundry/binary-builder/commit/88807f67ba5b3093052216e945ad51fc3658099b

Thanks for the issue!
