### ISSUE TITLE
/app/httpd/bin/httpd -v does not work

### ISSUE THREAD

**Issue by GETandSELECT** [cloudfoundry/php-buildpack#155]
What version of Cloud Foundry are you using?

```
releases:
- name: cf
  version: "239"
```

What version of the buildpack you are using?

latest 

`cf push $APP -b https://github.com/cloudfoundry/php-buildpack.git`

If you were attempting to accomplish a task, what was it you were attempting to do?

see version of apache

http://unix.stackexchange.com/questions/6792/how-can-i-tell-what-version-of-apache-im-running

What did you expect to happen?

version number

What was the actual behavior?

```
$ ps -ef | grep http
vcap        34     7  0 13:49 ?        00:00:00 /bin/sh -c $HOME/httpd/bin/apachectl -f "$HOME/httpd/conf/httpd.conf" -k start -DFOREGROUND
vcap        35    34  0 13:49 ?        00:00:00 /bin/sh /home/vcap/app/httpd/bin/apachectl -f /home/vcap/app/httpd/conf/httpd.conf -k start -DFOREGROUND
vcap        38    35  0 13:49 ?        00:00:00 /app/httpd/bin/httpd -f /home/vcap/app/httpd/conf/httpd.conf -k start -DFOREGROUND
vcap        46    38  0 13:49 ?        00:00:00 /app/httpd/bin/httpd -f /home/vcap/app/httpd/conf/httpd.conf -k start -DFOREGROUND
vcap        47    38  0 13:49 ?        00:00:00 /app/httpd/bin/httpd -f /home/vcap/app/httpd/conf/httpd.conf -k start -DFOREGROUND
vcap        50    38  0 13:49 ?        00:00:00 /app/httpd/bin/httpd -f /home/vcap/app/httpd/conf/httpd.conf -k start -DFOREGROUND
vcap       250    38  0 13:54 ?        00:00:00 /app/httpd/bin/httpd -f /home/vcap/app/httpd/conf/httpd.conf -k start -DFOREGROUND
vcap       969   790  0 14:28 pts/0    00:00:00 grep --color=auto http


$ /app/httpd/bin/httpd -v
/app/httpd/bin/httpd: error while loading shared libraries: libaprutil-1.so.0: cannot open shared object file: No such file or directory
```

**Comment by RochesterinNYC** [comment]
Hi @GETandSELECT, try running the following command before checking the version of httpd: `export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/vcap/app/httpd/lib/`.

This should allow the libaprutil-1.so.0 file to be found.

**Comment by dmikusa-pivotal** [comment]
PS.  If you just want to see the version for reference, you can look at the output of the build pack.  It lists the version of HTTPD being installed.

**Comment by GETandSELECT** [comment]
thanks @RochesterinNYC 

```
vcap@65139366-b21f-4cdd-5f05-17851a132d57:~$ export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/vcap/app/httpd/lib
vcap@65139366-b21f-4cdd-5f05-17851a132d57:~$ /app/httpd/bin/httpd -v
Server version: Apache/2.4.23 (Unix)
Server built:   Jul 18 2016 19:31:07
```

@dmikusa-pivotal what you mean by "output of the build pack"? Which command?

sorry for user error ticket.

**Comment by dmikusa-pivotal** [comment]
When you run `cf push` or `cf restage`, the build pack will run.  The output should look something like this.

```
-------> Buildpack version 4.3.17
Installing HTTPD
Downloaded [file:///tmp/buildpacks/337f7217e48f99046431d7f2eea3da30/dependencies/https___buildpacks.cloudfoundry.org_concourse-binaries_httpd_httpd-2.4.23-linux-x64.tgz] to [/tmp]
Installing PHP
PHP 5.5.37
Downloaded [file:///tmp/buildpacks/337f7217e48f99046431d7f2eea3da30/dependencies/https___buildpacks.cloudfoundry.org_concourse-binaries_php_php-5.5.37-linux-x64-1468353118.tgz] to [/tmp]
The extension 'intl' is not provided by this buildpack.
The extension 'ioncube' is not provided by this buildpack.
Finished: [2016-08-23 14:39:07.994021]
```

You can see the version being installed in the link that's being downloaded, `httpd-2.4.23-linux-x64.tgz`.  As a side note, we could probably make it more clear like we do with PHP.

**Comment by RochesterinNYC** [comment]
That's actually a really good point/improvement. @sclevine

**Comment by sclevine** [comment]
Story to add HTTPD version: https://www.pivotaltracker.com/story/show/128914955

**Comment by RochesterinNYC** [comment]
Closing this issue as the appropriate work has been scheduled.
