### ISSUE TITLE
Phalcon 3 for PHP7

### ISSUE THREAD

**Issue by gabel** [cloudfoundry/php-buildpack#156]
> What version of the buildpack you are using?

php 4.3.18

> If you were attempting to accomplish a task, what was it you were attempting to do?

Run PHP7 with phalcon extension.

> What did you expect to happen?

Phalcon extension should be available for PHP7 version as well. It is official available for PHP7 now in Version 3. Please add this extension to PHP7 version.

> What was the actual behavior?

Phalcon extension is not available.

Please confirm where necessary:
* [x] I have included steps for reproduction

`.bp-config/options.json`
```json
{
    "PHP_VERSION": "7.0",
    "PHP_EXTENSIONS": ["phalcon"]
}
```

```bash

The extension 'phalcon' is not provided by this buildpack.

```

**Comment by RochesterinNYC** [comment]
Phalcon 3.0.1 support for PHP7 has been added by this commit that's currently on develop: https://github.com/cloudfoundry/php-buildpack/commit/23217a40b619ea9c63aba9ac2a1e0b51f2b64022

Thanks for this issue.

**Comment by gabel** [comment]
@RochesterinNYC Thank you! 👍
