### ISSUE TITLE
Support deploying custom PHP modules with application

### ISSUE THREAD

**Issue by sdeeg-pivotal** [cloudfoundry/php-buildpack#160]
This is an enhancement request to have the buildpack support deploying custom PHP extensions with an application.  I have written a Buildpack Extension to do this, and will be issuing a pull request.  Wanted to have an issue to track it against.

What version of Cloud Foundry are you using?
1.7

What version of the buildpack you are using?
4.3.17

If you were attempting to accomplish a task, what was it you were attempting to do?
I wanted to deploy a custom PHP extension with an application.

What did you expect to happen?
Wanted extension to be available to my app.

What was the actual behavior?
Wasn't available.

Please confirm where necessary:
* [ ] I have included a log output 
* [ ] My log includes an error message 
* [ ] I have included steps for reproduction

**Comment by RochesterinNYC** [comment]
Closing in relation to #161
