### ISSUE TITLE
Trouble to install global package with composer and run a php file for config ?!

### ISSUE THREAD

**Issue by marcocianci** [cloudfoundry/php-buildpack#163]
What version of Cloud Foundry are you using?
--> cf version 6.21.1+cd086c8-2016-08-18
What version of the buildpack you are using?
--> v4.3.10
If you were attempting to accomplish a task, what was it you were attempting to do?
--> I am installing the Yii2 framework.
What did you expect to happen?
--> I was hoping that the composer would install "fxp/composer-asset-plugin:~1.2.0", then install all the other dependencies, and run a php init (php file that configure yii framework).

What was the actual behavior?
--> The composer do not install the packege globally (fxp/composer-asset-plugin:~1.2.0), and all the others from composer.json thrown exeptions and console breaks when trying to run "php init" at "post-install-cmd".

my options.json looks like that:
{
  "ADDITIONAL_PREPROCESS_CMDS": [
    "cd ./app/lib/",
    "php -r \"readfile('https://getcomposer.org/installer');\" | php",
    "php composer.phar global require \"fxp/composer-asset-plugin:~1.2.0\"",
    "php composer.phar install",
    "cd ../../"
  ]
}

Please confirm where necessary:
* [X] I have included a log output 
* [X] My log includes an error message 
* [X] I have included steps for reproduction

---
ERROR LOG:
8/29/2016 10:22:53 PM	OUT	API	Updated app with guid 44380c03-878f-4fea-8fb4-3598f18f2cf8 ({"name"=>"labedu", "instances"=>1, "memory"=>128, "disk_quota"=>1024, "buildpack"=>"php_buildpack", "environment_json"=>"PRIVATE DATA HIDDEN"})
8/29/2016 10:23:01 PM	OUT	API	Updated app with guid 44380c03-878f-4fea-8fb4-3598f18f2cf8 ({"state"=>"STOPPED"})
8/29/2016 10:23:03 PM	OUT	DEA	Stopping app instance (index 0) with guid 44380c03-878f-4fea-8fb4-3598f18f2cf8
8/29/2016 10:23:03 PM	OUT	DEA	Stopped app instance (index 0) with guid 44380c03-878f-4fea-8fb4-3598f18f2cf8
8/29/2016 10:23:04 PM	OUT	DEA	Got staging request for app with id 44380c03-878f-4fea-8fb4-3598f18f2cf8
8/29/2016 10:23:19 PM	OUT	API	Updated app with guid 44380c03-878f-4fea-8fb4-3598f18f2cf8 ({"state"=>"STARTED"})
8/29/2016 10:23:19 PM	OUT	STG	-----> Downloaded app package (216K)
8/29/2016 10:23:19 PM	OUT	STG	-----> Downloaded app buildpack cache (13M)
8/29/2016 10:23:20 PM	OUT	STG	-------> Buildpack version 4.3.10
8/29/2016 10:23:20 PM	OUT	STG	Installing HTTPD
8/29/2016 10:23:21 PM	OUT	STG	Downloaded [file:///var/vcap/data/dea_next/admin_buildpacks/ee88f28c-4afb-47c3-bc0f-db9ddc1ebb1d_749aaae1e042fa80b3e79977ea60bb95de257452/dependencies/https___pivotal-buildpacks.s3.amazonaws.com_concourse-binaries_httpd_httpd-2.4.20-linux-x64.tgz] to [/tmp]
8/29/2016 10:23:21 PM	OUT	STG	WARNING: A version of PHP has been specified in both `composer.json` and `./bp-config/options.json`.
8/29/2016 10:23:21 PM	OUT	STG	WARNING: The version defined in `composer.json` will be used.
8/29/2016 10:23:21 PM	OUT	STG	Installing PHP
8/29/2016 10:23:21 PM	OUT	STG	PHP 5.6.20
8/29/2016 10:23:21 PM	OUT	STG	Downloaded [file:///var/vcap/data/dea_next/admin_buildpacks/ee88f28c-4afb-47c3-bc0f-db9ddc1ebb1d_749aaae1e042fa80b3e79977ea60bb95de257452/dependencies/https___pivotal-buildpacks.s3.amazonaws.com_concourse-binaries_php_php-5.6.20-linux-x64-1459869944.tgz] to [/tmp]
8/29/2016 10:23:23 PM	ERR	STG	The extension 'ctype' is not provided by this buildpack.
8/29/2016 10:23:24 PM	OUT	STG	Downloaded [file:///var/vcap/data/dea_next/admin_buildpacks/ee88f28c-4afb-47c3-bc0f-db9ddc1ebb1d_749aaae1e042fa80b3e79977ea60bb95de257452/dependencies/https___pivotal-buildpacks.s3.amazonaws.com_concourse-binaries_php_php-5.6.20-linux-x64-1459869944.tgz] to [/tmp]
8/29/2016 10:23:26 PM	OUT	STG	Downloaded [file:///var/vcap/data/dea_next/admin_buildpacks/ee88f28c-4afb-47c3-bc0f-db9ddc1ebb1d_749aaae1e042fa80b3e79977ea60bb95de257452/dependencies/https___pivotal-buildpacks.s3.amazonaws.com_php_binaries_trusty_composer_1.0.0_composer.phar] to [/tmp]
8/29/2016 10:23:26 PM	ERR	STG	Loading composer repositories with package information
8/29/2016 10:23:26 PM	ERR	STG	Installing dependencies from lock file
8/29/2016 10:23:26 PM	ERR	STG	Loading from cache
8/29/2016 10:23:26 PM	ERR	STG	- Installing bower-asset/jquery (2.2.4)
8/29/2016 10:23:26 PM	ERR	STG	Loading from cache
8/29/2016 10:23:26 PM	ERR	STG	- Installing bower-asset/jquery.inputmask (3.2.7)
8/29/2016 10:23:26 PM	ERR	STG	Loading from cache
8/29/2016 10:23:26 PM	ERR	STG	- Installing bower-asset/punycode (v1.3.2)
8/29/2016 10:23:26 PM	ERR	STG	Loading from cache
8/29/2016 10:23:26 PM	ERR	STG	- Installing bower-asset/yii2-pjax (v2.0.6)
8/29/2016 10:23:26 PM	ERR	STG	Loading from cache
8/29/2016 10:23:27 PM	ERR	STG	- Installing cebe/markdown (1.1.0)
8/29/2016 10:23:27 PM	ERR	STG	Loading from cache
8/29/2016 10:23:27 PM	ERR	STG	- Installing ezyang/htmlpurifier (v4.8.0)
8/29/2016 10:23:27 PM	ERR	STG	Loading from cache
8/29/2016 10:23:27 PM	ERR	STG	- Installing yiisoft/yii2 (2.0.9)
8/29/2016 10:23:27 PM	ERR	STG	Loading from cache
8/29/2016 10:23:27 PM	ERR	STG	- Installing bower-asset/bootstrap (v3.3.7)
8/29/2016 10:23:27 PM	ERR	STG	Loading from cache
8/29/2016 10:23:28 PM	ERR	STG	- Installing yiisoft/yii2-bootstrap (2.0.6)
8/29/2016 10:23:28 PM	ERR	STG	Loading from cache
8/29/2016 10:23:28 PM	ERR	STG	- Installing swiftmailer/swiftmailer (v5.4.3)
8/29/2016 10:23:28 PM	ERR	STG	Loading from cache
8/29/2016 10:23:28 PM	ERR	STG	- Installing yiisoft/yii2-swiftmailer (2.0.5)
8/29/2016 10:23:28 PM	ERR	STG	Loading from cache
8/29/2016 10:23:29 PM	ERR	STG	Generating autoload files
8/29/2016 10:23:29 PM	ERR	STG	> php init --env=Development --overwrite=y
8/29/2016 10:23:29 PM	OUT	STG	Could not open input file: init
8/29/2016 10:23:29 PM	ERR	STG	Script php init --env=Development --overwrite=y handling the post-install-cmd event returned with an error
8/29/2016 10:23:29 PM	ERR	STG	[RuntimeException]
8/29/2016 10:23:29 PM	ERR	STG	Error Output:
8/29/2016 10:23:29 PM	ERR	STG	install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-plugins] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--ignore-platform-reqs] [--] [<packages>]...
8/29/2016 10:23:29 PM	OUT	STG	-----> Composer command failed
8/29/2016 10:23:29 PM	ERR	STG	Traceback (most recent call last):
8/29/2016 10:23:29 PM	ERR	STG	File "/var/vcap/data/dea_next/admin_buildpacks/ee88f28c-4afb-47c3-bc0f-db9ddc1ebb1d_749aaae1e042fa80b3e79977ea60bb95de257452/scripts/compile.py", line 50, in <module>
8/29/2016 10:23:29 PM	ERR	STG	.from_build_pack('lib/additional_commands')
8/29/2016 10:23:29 PM	ERR	STG	File "/var/vcap/data/dea_next/admin_buildpacks/ee88f28c-4afb-47c3-bc0f-db9ddc1ebb1d_749aaae1e042fa80b3e79977ea60bb95de257452/lib/build_pack_utils/builder.py", line 208, in extensions
8/29/2016 10:23:29 PM	ERR	STG	process_extension(path, ctx, 'compile', process, args=[self])
8/29/2016 10:23:29 PM	ERR	STG	File "/var/vcap/data/dea_next/admin_buildpacks/ee88f28c-4afb-47c3-bc0f-db9ddc1ebb1d_749aaae1e042fa80b3e79977ea60bb95de257452/lib/build_pack_utils/utils.py", line 69, in process_extension
8/29/2016 10:23:29 PM	ERR	STG	success(getattr(extn, to_call)(*args))
8/29/2016 10:23:29 PM	ERR	STG	File "/var/vcap/data/dea_next/admin_buildpacks/ee88f28c-4afb-47c3-bc0f-db9ddc1ebb1d_749aaae1e042fa80b3e79977ea60bb95de257452/extensions/composer/extension.py", line 407, in compile
8/29/2016 10:23:29 PM	ERR	STG	return composer.compile(install)
8/29/2016 10:23:29 PM	ERR	STG	File "/var/vcap/data/dea_next/admin_buildpacks/ee88f28c-4afb-47c3-bc0f-db9ddc1ebb1d_749aaae1e042fa80b3e79977ea60bb95de257452/lib/extension_helpers.py", line 154, in compile
8/29/2016 10:23:29 PM	ERR	STG	self._compile(install)
8/29/2016 10:23:29 PM	ERR	STG	File "/var/vcap/data/dea_next/admin_buildpacks/ee88f28c-4afb-47c3-bc0f-db9ddc1ebb1d_749aaae1e042fa80b3e79977ea60bb95de257452/extensions/composer/extension.py", line 174, in _compile
8/29/2016 10:23:29 PM	ERR	STG	self.run()
8/29/2016 10:23:29 PM	ERR	STG	File "/var/vcap/data/dea_next/admin_buildpacks/ee88f28c-4afb-47c3-bc0f-db9ddc1ebb1d_749aaae1e042fa80b3e79977ea60bb95de257452/extensions/composer/extension.py", line 309, in run
8/29/2016 10:23:29 PM	ERR	STG	*self._ctx['COMPOSER_INSTALL_OPTIONS'])
8/29/2016 10:23:29 PM	ERR	STG	File "/var/vcap/data/dea_next/admin_buildpacks/ee88f28c-4afb-47c3-bc0f-db9ddc1ebb1d_749aaae1e042fa80b3e79977ea60bb95de257452/extensions/composer/extension.py", line 353, in run
8/29/2016 10:23:29 PM	ERR	STG	shell=True)
8/29/2016 10:23:29 PM	ERR	STG	File "/var/vcap/data/dea_next/admin_buildpacks/ee88f28c-4afb-47c3-bc0f-db9ddc1ebb1d_749aaae1e042fa80b3e79977ea60bb95de257452/lib/build_pack_utils/runner.py", line 109, in stream_output
8/29/2016 10:23:29 PM	ERR	STG	raise CalledProcessError(retcode, cmd)
8/29/2016 10:23:29 PM	ERR	STG	build_pack_utils.runner.CalledProcessError: Command '<open file '<fdopen>', mode 'w' at 0x7f452f0b88a0>' returned non-zero exit status 1
8/29/2016 10:23:29 PM	OUT	STG	Staging failed: Buildpack compilation step failed
8/29/2016 10:23:29 PM	ERR	API	encountered error: App staging failed in the buildpack compile phase

---
composer.json:
{
    "name": "yiisoft/yii2-app-advanced",
    "description": "Yii 2 Advanced Project Template",
    "keywords": ["yii2", "framework", "advanced", "project template"],
    "homepage": "http://www.yiiframework.com/",
    "type": "project",
    "license": "BSD-3-Clause",
    "support": {
        "issues": "https://github.com/yiisoft/yii2/issues?state=open",
        "forum": "http://www.yiiframework.com/forum/",
        "wiki": "http://www.yiiframework.com/wiki/",
        "irc": "irc://irc.freenode.net/yii",
        "source": "https://github.com/yiisoft/yii2"
    },
    "minimum-stability": "stable",
    "require": {
        "php": ">=5.4.0",
        "yiisoft/yii2": ">=2.0.6",
        "yiisoft/yii2-bootstrap": "*",
        "yiisoft/yii2-swiftmailer": "*"
    },
    "require-dev": {
        "yiisoft/yii2-codeception": "*",
        "yiisoft/yii2-debug": "*",
        "yiisoft/yii2-gii": "*",
        "yiisoft/yii2-faker": "*"
    },
    "config": {
        "process-timeout": 1800
    },
    "extra": {
        "asset-installer-paths": {
            "npm-asset-library": "vendor/npm",
            "bower-asset-library": "vendor/bower"
        }
    },
    "scripts": {
        "post-install-cmd": "php init --env=Development --overwrite=y"
    }
}

**Comment by dmikusa-pivotal** [comment]
I'm sorry, I'm not familiar with that framework.  Can you explain more about what you're trying to do here?

```
{
"ADDITIONAL_PREPROCESS_CMDS": [
"cd ./app/lib/",
"php -r \"readfile('https://getcomposer.org/installer');\" | php",
"php composer.phar global require \"fxp/composer-asset-plugin:~1.2.0\"",
"php composer.phar install",
"cd ../../"
]
}
```

Why do you need to install composer?  The build pack installs it for you.  It should be under `/home/vcap/app/php/bin/composer.phar`.  Why do you need this requirement installed globally?  Can you try limiting this to just the following?  I think that should use the build pack installed composer.phar file.

```
{
"ADDITIONAL_PREPROCESS_CMDS": [
"php /home/vcap/app/php/bin/composer.phar global require \"fxp/composer-asset-plugin:~1.2.0\"",
"php /home/vcap/app/php/bin/composer.phar install"
]
}
```

Also, what is this command doing? `php init --env=Development --overwrite=y`.

It's failing, saying "init" can't be found.

```
8/29/2016 10:23:29 PM ERR STG > php init --env=Development --overwrite=y
8/29/2016 10:23:29 PM OUT STG Could not open input file: init
8/29/2016 10:23:29 PM ERR STG Script php init --env=Development --overwrite=y handling the post-install-cmd event returned with an error
```

What's it supposed to do?  Is this failing because of the composer global requirement above?

Thanks!

**Comment by marcocianci** [comment]
1) "ADDITIONAL_PREPROCESS_CMDS" => I'm trying to install fxp globally.
2)
3)
4)

**Comment by marcocianci** [comment]
![yii2-folders](https://cloud.githubusercontent.com/assets/3075342/18075019/9cb964fc-6e47-11e6-9b0b-0b0be2173ce3.png)

**Comment by marcocianci** [comment]
Hi Daniel Mikusa,
1) "ADDITIONAL_PREPROCESS_CMDS" => I'm trying to install fxp globally.
2) It's ok! Works fine. I didn't found path correct. \o/
3) After installing composer (dependencies and fxp globallly), I need to run the "php init" in the project root folder.
have you any example ?

Thanks again!

**Comment by marcocianci** [comment]
Hi Daniel, following his suggestion I ran the following command and got the expected result, but crashed. :/
`  
"ADDITIONAL_PREPROCESS_CMDS": [
    "php /home/vcap/app/php/bin/composer.phar global require \"fxp/composer-asset-plugin:~1.2.0\"",
    "php /home/vcap/app/php/bin/composer.phar install",
    "cd /home/vcap/app/htdocs/",
    "php init --env=Development --overwrite=y"
  ]
`
At this time "ADDITIONAL PREPROCESS_CMDS" the files are already in htdocs (webserver online) ?

![yii2-clashed](https://cloud.githubusercontent.com/assets/3075342/18076022/9ce8ad8a-6e50-11e6-8833-dde490a6a287.png)

**Comment by marcocianci** [comment]
Hi Daniel Mikusa,
Item 3 is solved.

Now I have another problem, buildpack_php didn't copy folders to htdocs if they are empty. They are empty but versioned at git.
I will open a issue including steps for reproduction.

**Comment by dmikusa-pivotal** [comment]
@marcocianci - Can you share what you ended up doing to get this to work?  In case others might encounter the same issue?

Also, the issue with empty folders isn't a build pack problem.  The cf cli doesn't upload empty folders when you `cf push`.  If you have an empty folder that's not being uploaded and is needed server side, you can drop a hidden file in it like `.placeholder` and that will force the folder to be uploaded.

**Comment by marcocianci** [comment]
Hi @dmikusa-pivotal,

1) install (fxp/composer-asset-plugin) globally;
2) copy composer.json from root folder to htdocs. (I don't know why build package didn't copy only this file.)
3) enter inside folder application to run init, then composer.

"ADDITIONAL_PREPROCESS_CMDS": [
"cp /home/vcap/app/application/composer.json /home/vcap/app/htdocs/application/composer.json",
"php /home/vcap/app/php/bin/composer.phar global require \"fxp/composer-asset-plugin:~1.2.0\"",
"cd /home/vcap/app/htdocs/application",
"php init --env=Development --overwrite=y",
"php /home/vcap/app/php/bin/composer.phar install",
"php yii migrate <<< yes",
"cd /home/vcap/",
]
![dev-step1](https://cloud.githubusercontent.com/assets/3075342/18098109/20ee9b38-6eb7-11e6-9a7c-a4ff3c98503d.png)
![dev-step2](https://cloud.githubusercontent.com/assets/3075342/18098115/27f8f5c2-6eb7-11e6-96dd-f54a06af584a.png)
![dev-step3](https://cloud.githubusercontent.com/assets/3075342/18098122/2ca068b2-6eb7-11e6-8523-ffb7195aa705.png)
![dev-step4](https://cloud.githubusercontent.com/assets/3075342/18098422/84d668aa-6eb8-11e6-9615-294e7a988c97.png)


---
Hey Daniel, could you please tell me where can I configure Virtual Host, like that:
<VirtualHost *:80>
    ServerName yii2-app.mybluemix.net
    ServerAlias yii2-app.mybluemix.net
    ServerAdmin admin@admin.com
    DirectoryIndex index.php index.htm index.html
    DocumentRoot /home/vcap/app/htdocs/application/frontend/web
</VirtualHost>

**Comment by dmikusa-pivotal** [comment]
OK, so I see a few things I want to point out here.

1.) It looks like part of the complication here might be that you are actually pushing two applications (or at least one application that seems to have other nested in it).  I see a front end and a backend in the output you included.

The build pack isn't really designed for that.  It makes the assumption that there's one app.  I'm not saying it's impossible to get what you want, but your going to be facing an uphill battle.  The happy path is for users to push individual apps, ie. front end and backend as separate apps.

This lets you do a number of helpful things like:
  - assign routes and paths (i.e. map URLs) to each app individually
  - scale them independently, which is important as your application takes on more load
  - update applications independently

and probably other things I'm forgetting.  The way it simplifies your deployment is probably the biggest advantage though.

You can also still have them all appear under the same FQDN, for example if you want http://example.com/frontend and http://example.com/backend.  You're just adding a path to your route, and CF will make sure the right requests go to the right application.

2.) If you follow my advise in #1, you can then set WEBDIR in `.bp-config/options.json` to point to the `web` directory for each of your apps.  This will bypass the functionality in the build pack which copies files around and should make it easier for you to locate files in your project.  I think this will also help with the placement of composer.json.

3.) In some cases having the build pack run Composer for you just makes your life harder.  If you find you might be in one of these cases, what you can do is to prepare your application locally (i.e. run all your build steps & Composer).  When your app is ready to run, add a file `.cfignore` in the root of your project from where you push and put `composer.*` in the file.  This will instruct `cf push` to ignore the composer.json and composer.lock files (i.e not upload them), but push up everything else.  This includes all the vendored files that Composer installed locally when you ran and it should include everything you to run your app (perhaps with the exception of the empty folder issue).  The upside of this is that it's a simpler process, more like a classic PHP deployment where you're just FTP'ing or SCP'ing files to your server.  The downside is that you're sending more files which makes the upload take longer.

4.) All of the commands that you're setting in ADDITIONAL_PREPROCESS_CMDS run in your application container prior to your application starting up.  If the sum total of these commands plus your application start time take longer than 180 seconds then your app will fail to start / crash.  It's a long time, but just be aware in case you have long db migration scripts or anything like that which would need to run.

5.) As far as VirtualHosts, this is something that you could do but I really wouldn't recommend it.  As I mentioned above, it's much better to separate stuff into different apps on CF.  That lets you use the platform functionality to map routes & paths to your application and you don't need to worry about VirtualHost configuration.  The only case where this might make sense is if you have a lot of really tiny applications and where you could run enough of them with one 64 or 128M of RAM app instance that you are lowering your costs in a significant way (i.e. more than what your time costs to setup all the VirtualHosts).  If you really want to go this route, see the config options [here](http://docs.cloudfoundry.org/buildpacks/php/gsg-php-config.html#engine-configurations).  You can use that to set your own custom HTTPD config.

**Comment by marcocianci** [comment]
Hey Daniel, thanks again!
[Yii2](http://www.yiiframework.com/) is a framework that has 2 fronts (backend and frontend), but both use the same application like Models, Configurations are placed in a common folder, so it's  one application that can have one or more virtual hosts.
that's why I need to have 2 virtual hosts in the same buildpack.
I managed to make it works by creating Aliases in "httpd-directories.conf", I used this file because when I changed the "httpd.conf" it wasn't overwrite.
It was quite simple.
The bellow image works like a charm.
![dev-httpd-dir](https://cloud.githubusercontent.com/assets/3075342/18106689/3cded406-6edb-11e6-9f32-f41027d6f3d8.png)

The bellow image don't.
![dev-httpd-conf](https://cloud.githubusercontent.com/assets/3075342/18106681/37dbc28e-6edb-11e6-9378-29338ec9ccec.png)

![dev-httpd-conf-bluemix](https://cloud.githubusercontent.com/assets/3075342/18106789/7f4eac44-6edb-11e6-86e4-09be34a6c293.png)
bluemix > org > "your project" > Files > "httpd.conf"
Is this an issue or the default behavior ?

**Comment by dmikusa-pivotal** [comment]
>Yii2 is a framework that has 2 fronts (backend and frontend), but both use the same application like Models, Configurations are placed in a common folder, so it's one application that can have one or more virtual hosts.

Interesting.  Are there some demo apps or a sample tutorial that you could point me that demonstrate this?  I'd like to play around with a test case and see how the build pack is handling it and if we could possibly handle it better.

>I managed to make it works by creating Aliases in "httpd-directories.conf", I used this file because >when I changed the "httpd.conf" it wasn't overwrite.
>It was quite simple.

If that works for you, then by all means go ahead.  I do worry bit that you're overriding so much stuff in your app.  Could you make this work with a `.htaccess` file instead?  

It would be better in the long run.  When you override the build pack default files, you are completely overriding them.  This means that if we change / fix stuff upstream, your local copy will overwrite those changes / fixes.  This doesn't happen often, but could cause things to break or cause you to miss important configuration changes (like if we mitigate a security issue).  

If you're able to use  a `.htaccess` file this tends to blend better with the build pack change.  I'm not sure you can use aliases in `.htaccess` files, but if there's a way you can make it work with a `.htaccess` file you might want to consider it.

>Is this an issue or the default behavior ?

Not sure what you're asking here.  Sorry.

**Comment by marcocianci** [comment]
>>Is this an issue or the default behavior ?

> Not sure what you're asking here. Sorry. 

// It was my mistake! :-1:  sorry
About Yii framework here is the link: http://www.yiiframework.com/doc-2.0/guide-start-installation.html

To keep pretty routes .htaccess does not do the trick. So I only changed httpd.conf, by modifying DocumenRoot and adding an Alias.
>DocumentRoot` "${HOME}/#{WEBDIR}/application/frontend/web"
>Alias "/api" "${HOME}/#{WEBDIR}/application/backend/web"

Thanks
![dev-httpd-conf-end](https://cloud.githubusercontent.com/assets/3075342/18110012/8ea0bb0a-6eeb-11e6-9722-66cbcaf3c166.png)
