### ISSUE TITLE
Add a new server as an extension

### ISSUE THREAD

**Issue by adrianocr** [cloudfoundry/php-buildpack#164]
So I thoroughly read through the documentation and code but don't understand how the scripts downloads/compiles certain binaries. 

I want to add [Caddy Server](http://caddyserver.com) as an extension. I get that I'm going to create a Caddy directory under `/lib/` and add the extension.py file to it. However, how does it acquire the caddy binary? In the nginx extension there's a `.package('NGINX')` line of code. Where does this package come from? Can I run some kind of curl or wget command to pull caddy from a server? Or can I package it directly with the buildpack and have the buildpack "use it" from a directory inside the buildpack?

**Comment by jchesterpivotal** [comment]
Oh, and if it's OK with you, would you object to closing this if you're satisfied?
