### ISSUE TITLE
.profile is not triggered

### ISSUE THREAD

**Issue by avasseur-pivotal** [cloudfoundry/php-buildpack#165]
What version of Cloud Foundry are you using?
PCF 1.7

What version of the buildpack you are using?
PHP BP 4.3.19

If you were attempting to accomplish a task, what was it you were attempting to do?
use .profile script (not .profile.d/*.sh scripts)

What did you expect to happen?
.profile is executed at app start

What was the actual behavior?
nothing

Please confirm where necessary:
* [ ] I have included a log output 
* [ ] My log includes an error message 
* [ ] I have included steps for reproduction

see
https://github.com/cloudfoundry/php-buildpack/blob/fff9044e9ac2821cd8f902aade13519139f06da8/lib/build_pack_utils/builder.py

there is no .profile although there is .profile.d

**Comment by RochesterinNYC** [comment]
Hi @avasseur-pivotal, this functionality is not in PCF 1.7 as PCF 1.7 ships with CF Release `v235` and the `.profile` support was added in CF release `v238`.
