### ISSUE TITLE
SASL Support in memecached

### ISSUE THREAD

**Issue by clement360** [cloudfoundry/php-buildpack#166]
I need SASL Support enabled in memcached to use the memcached cloud service.

 PS I see a list of availiable modules, is there a list of valid extensions as well? 

![image](https://cloud.githubusercontent.com/assets/2770596/18689797/9e5b711e-7f50-11e6-80db-a91adc0030e1.png)

**Comment by clement360** [comment]
just realized this was added in a later version of the buildpack and bluemix defaults to an outdated version  :/

**Comment by clement360** [comment]
SASL support is enabled however I'm getting: Got error 'PHP message: PHP Warning:  Memcached::setSaslAuthData(): SASL support (memcached.use_sasl) isn't enabled in php.ini 

possibly related:
![image](https://cloud.githubusercontent.com/assets/2770596/18690470/e001fcde-7f53-11e6-931d-a803e175d666.png)

Any idea why I would receive this error? does memecached need to be enabled twice?

**Comment by clement360** [comment]
Sounds like I need to set memcached.use_sasl = 1 in php.ini how would I do this using the buildpack?

**Comment by dmikusa-pivotal** [comment]
>Sounds like I need to set memcached.use_sasl = 1 in php.ini how would I do this using the buildpack?

Correct.  An example of where this is being done is for the session persistence extension.  This can use memcached (and redis) and the build pack extension auto configures `memcached.use_sasl` to `On`.

https://github.com/cloudfoundry/php-buildpack/blob/master/extensions/sessions/extension.py#L66-L72

**Comment by clement360** [comment]
maybe I'm misunderstanding you, but are you saying that the memcached extension auto configures memcached.use_sasl to On? I have the memcached extension added in my options.json but it still says memcached.use_sasl = 0

**Comment by dmikusa-pivotal** [comment]
No, sorry I didn't explain that well.  The build pack has extensions too.  I was referring to the extension for the PHP build pack that enables session persistence through either Redis or Memcached.  It enables this functionality for you when the build pack runs and part of that is setting the php.ini setting you mentioned to turn on sasal for memcached.  

In short, I was just trying to confirm that you're on the right track and you need to set that manually.

**Comment by LongZaiAiYueLiang** [comment]
Hello, sir. I have the same problem as you. How did you solve it? I am confused now.

**Comment by dmikusa-pivotal** [comment]
@LongZaiAiYueLiang - I believe this was the fix.

>Figured it out: http://docs.cloudfoundry.org/buildpacks/php/gsg-php-sessions.html#using_session
>needed to bind a memecached service with the name memcached-sessions then redeploy. Thanks
