### ISSUE TITLE
Files deleted during staging & post-install-cmd not executed

### ISSUE THREAD

**Issue by lucaskuperman** [cloudfoundry/php-buildpack#167]
Hi, 
  I am forking the [WordPress@Bluemix](https://hub.jazz.net/project/jstart/WordPress%20on%20Bluemix/overview) project (a Composer-based project), and trying to add my company's custom theme to it, before pushing it into IBM's Bluemix platform. For that, I am attempting to: 
-install a custom wordpress theme during wordpress installation, by providing the theme as a Composer dependency of type=path, and,
- override the final app/htdocs/wp-config.php file with a version of my own, as part of the post-installation-cmd script. 
  However I am facing strange behaviors (from buildpack?) during staging phase, which I don't understand and need help clarifying. After preliminary checks from Slack's @buildpacks-team, I am opening this ticket based on their suggestion.

1) The first question is about missing files and folders after staging completes. Take as example, the wp-config.php file, or the ibmNorthstartTheme folder, both located at the root level of my [git project](https://hub.jazz.net/git/kuper/WordPress-on-Bluemix-kuper-1920). They will disappear after staging, and I don't understand why. I expect files don't disappear when staging. @slevine also expects the same.
NOTE1: @slevine showed me that files are indeed being uploaded when pushing, but disappear during staging. This happens with Bluemix's buildpacks 4.3.7 & 4.3.20, and also with OSS buildpack 4.3.17.
NOTE2: I already checked the .gitignore and .cfignore rules. They shouldn't impact the files/folders mentioned.
NOTE3: curiously, 'composer.json' inside ibmNorthstartThem folder is not removed, but all other files in that folder are removed. Is this as expected?
NOTE4: folder 'lib' always remains after staging, but placing my custom php files in 'lib' folder does not sound like the right solution for me.
NOTE5: this strange behavior is encountered when no htdocs folder exists in my project, or when an empty htdocs folder exists. But from the moment the htdocs folder contains at least 1 file (even an empty dummy file), behavior changes and all the files and folders are not deleted anymore (including wp-config.php file and the entire ibmNorthstartTheme folder). I need to understand if this is expected or not to decide if I have to leave the dummy file in the htdocs folder, or not.

2) In an effort to identify what was going on, I ran the builds against Bluemix's php-buildpacks 4.3.7 and 4.3.20 with same end result. But strangely, I found that 4.3.20 (and 4.3.17 per @slevine tests) doesn't execute the post-install-cmd of my composer.json. Any explanation about this? I expect post-install-cmd be executed (like in buildpack 4.3.7) so that I can replace files after app installation, like the wp-config.php file.

I summarize data for this behavior reproduction:
1) clone [sample git project](https://hub.jazz.net/git/kuper/WordPress-on-Bluemix-kuper-1920)
2) push against buildpacks 4.3.7, 4.3.17 or 4.3.20 (
3) check location of wp-config.php or ibmNorthstarTheme folder post staging. They are not found

**Comment by dmikusa-pivotal** [comment]
>1) The first question is about missing files and folders after staging completes. 

This sounds like expected behavior.  The build pack by default will assume that everything you upload is part of your PHP application and as such will helpfully move those files into the doc root (i.e. `htdocs`).  This is generally the correct approach for an application that puts all it's files into a publicly accessible docroot, like a default Wordpress install (i.e. extract WP and push files).  

BTW, It doesn't move composer.json because you would not generally want that to be public and anything moved will be in the docroot so thus potentially public.

This behavior doesn't work / isn't desirable for other cases (like some frameworks, CakePHP is one that comes to mind) and you can disable it.  There are two ways.  The first is to create a `htdocs` folder in your project and put everything that should be public into that folder.  The second is to set `WEBDIR` in `.bp-config/options.json` and point it to an existing directory that should be your docroot.  In your case, I think you want to create a `htdocs` folder and install everything to there.  

For what it's worth, you can also combine the two and create a folder `public` (or whatever) and then point `WEBDIR` to that folder.

>2) In an effort to identify what was going on, I ran the builds against Bluemix's php-buildpacks 4.3.7 and 4.3.20 with same end result. But strangely, I found that 4.3.20 (and 4.3.17 per @slevine tests) doesn't execute the post-install-cmd of my composer.json. Any explanation about this? I expect post-install-cmd be executed (like in buildpack 4.3.7) so that I can replace files after app installation, like the wp-config.php file.

No.  It should execute that and I've seen cases where it does execute.  It's actually composer that runs the script though.  eg. build pack runs composer, composer runs your post-install-cmd.  First thing would be to check that Composer is running in those cases.  Then maybe enable debug logging for Composer and see what it's doing.

Hope that helps!

**Comment by sclevine** [comment]
FYI, I'm @sclevine on Github.

I confirmed with @lucaskuperman on Slack that his `wp-config.php` file disappears from the app container completely. It does not appear in the `htdocs` folder.

Also, the composer post-install-cmd doesn't show any staging output in 4.3.17, and it does show output in 4.3.7. Not sure if it's actually not running though.

**Comment by lucaskuperman** [comment]
Thanks @sclevine for jumping in and clarifying my points: files/folders are removed from the entire app container for some reason I can't see. And @dmikusa-pivotal actually confirms -then- there is a deviation from expected result.
As for the `post-install-cmd`, I ran it with `-vvv`. Attaching output. I believe it Composer does not run `post-install-cmd` at all
[log.txt](https://github.com/cloudfoundry/php-buildpack/files/496902/log.txt)

**Comment by dmikusa-pivotal** [comment]
In regards to the post-install-cmd issue, I pushed a [test app](https://github.com/cloudfoundry-samples/cf-ex-composer) which uses post post-install-cmd and it worked fine for me.

```
Installing dependencies from lock file
  - Installing doctrine/lexer (v1.0.1)
    Downloading
  - Installing gregwar/cache (v1.0.10)
    Downloading
  - Installing twig/twig (v1.22.1)
    Downloading
  - Installing symfony/translation (v2.7.4)
    Downloading
  - Installing symfony/templating (v2.7.4)
    Downloading
  - Installing symfony/stopwatch (v2.7.4)
    Downloading
  - Installing symfony/security-core (v2.7.4)
    Downloading
  - Installing symfony/security-csrf (v2.7.4)
    Downloading
  - Installing symfony/routing (v2.7.4)
    Downloading
  - Installing symfony/http-foundation (v2.7.4)
    Downloading
  - Installing symfony/event-dispatcher (v2.7.4)
    Downloading
  - Installing psr/log (1.0.0)
    Downloading
  - Installing symfony/debug (v2.7.4)
    Downloading
  - Installing symfony/http-kernel (v2.7.4)
    Downloading
  - Installing symfony/filesystem (v2.7.4)
    Downloading
  - Installing symfony/dependency-injection (v2.7.4)
    Downloading
  - Installing symfony/config (v2.7.4)
    Downloading
  - Installing doctrine/annotations (v1.2.7)
    Downloading
  - Installing symfony/framework-bundle (v2.7.4)
  - Installing symfony/asset (v2.7.4)
  - Installing gregwar/image (v2.0.20)
    Downloading
  - Installing gregwar/image-bundle (v2.0.21)
    Downloading
  - Installing monolog/monolog (1.0.2)
    Downloading
Generating autoload files
> php -r 'print "Hello World!
";'
Hello World!
> php -r 'print "Memory: " . ini_get("memory_limit") . "
";'
Memory: 256M
```

Did that with 4.3.19 & master branch (on PWS).  Both same results.  Can you try the sample app and see if it works for you?

**Comment by dmikusa-pivotal** [comment]
In regards to the files moving, set `BP_DEBUG=true` and the build pack will dump a bunch of extra output.  This should say if it's moving files and what files.

Ex:

```
---
applications:
- name: <app-name>
  memory: 128M
  instances: 1
  path: .
  env:
    BP_DEBUG: "True"
```

or `cf set-env <app> BP_DEBUG True`.

**Comment by dmikusa-pivotal** [comment]
>NOTE4: folder 'lib' always remains after staging, but placing my custom php files in 'lib' folder does not sound like the right solution for me.

It's probably also worth noting that `lib` is another special directory.  It's not moved but the files end up on the PHP include path.  If you don't intend for this special behavior, you can set `LIBDIR` to something else in `.bp-config/options.json`.  Setting it to something that doesn't exist is fine, so if you just want to treat `lib` as a normal directory you could set `"LIBDIR": "ignore_this"`.

**Comment by lucaskuperman** [comment]
@dmikusa-pivotal sorry for late response:
1) yes, I tried the composer sample app and I confirm it executes the `post-install-cmd`, in buildpacks 4.3.7, 4.3.10 and 4.3.20. So I then remembered @sclevine warning me that there's an explicit reference to buildpack 4.3.7 in `manifest.yml`. I investigated the original [WordpressOnBluemix](https://hub.jazz.net/git/jstart/WordPress.on.Bluemix) project and found this in their git log:

> Updated manifest.yml with explicit reference to Cloud Foundry PHP Buildpack 4.3.7.
A newer released 4.3.8 Buildpack pulls in a newer composer which is breaking the current post-install-cmd declaration within this project's composer.json

Sorry about not finding this earlier. I guess the post-install-cmd '_issue_' is in the project side. Do you have any hunch (or heard before) about 4.3.8 and post-install-cmd issues? I'm willing to contribute to the fix, and maybe you can point me in the right direction. Other than that, this item can be considered answered.

2) I tried `BP_DEBUG: "True"` and I do see debug information (attaching). But I can't find something useful (at least for me). No clue which one could be deleting my files. So this item I still consider it open.
[log_with_composer_debug.txt](https://github.com/cloudfoundry/php-buildpack/files/499024/log_with_composer_debug.txt)

3) Thx about `lib` explanation. It is aligned with what I knew about it, and helped me decide not to use `lib` in this case.

**Comment by dmikusa-pivotal** [comment]
>Sorry about not finding this earlier. I guess the post-install-cmd 'issue' is in the project side. Do you have any hunch (or heard before) about 4.3.8 and post-install-cmd issues?

I have not, but you can explicitly set the version of Composer you want.  So if you know which version of Composer is OK with your settings (perhaps whatever is being used in 4.3.7 by default), you might be able to use the latest build pack and just use an older Composer version.

https://docs.cloudfoundry.org/buildpacks/php/gsg-php-composer.html#configuration

> mv vendor/ibmjstart/wp-bluemix-config/.user.ini htdocs
> mv wp-config.php htdocs
> mv vendor htdocs/vendor
> mv lib/.htaccess htdocs

I looked through the log and I don't see the build pack moving your files.  If it were to move the files, then it would log that.

Ex of bp moving files:

```
2016-09-28 18:48:56,108 [DEBUG] builder - Copying files from [/tmp/buildpacks/php-buildpack/bin] to [/tmp/staged/app/.bp/bin]
2016-09-28 18:48:56,109 [DEBUG] builder - Copying [/tmp/buildpacks/php-buildpack/bin/start] to [/tmp/staged/app/.bp/bin/start]
2016-09-28 18:48:56,109 [DEBUG] builder - Copying [/tmp/buildpacks/php-buildpack/bin/rewrite] to [/tmp/staged/app/.bp/bin/rewrite]
```

It would be interesting to insert some additional commands to confirm the state of things before and after your mv commands run.  For example: `cwd`, `ls -la`, `ls -la htdocs`.  You might also try using full paths to remove dependence on the current working directory.

Hope that helps!

**Comment by RochesterinNYC** [comment]
@lucaskuperman does using @dmikusa-pivotal's helpful log debugging tips help?

**Comment by lucaskuperman** [comment]
@RochesterinNYC I didn't try yet, but I still don't understand this switching behavior when there's an htdocs folder in my project, or not. Will keep you posted

**Comment by dmikusa-pivotal** [comment]
It boils down to this.  If your project has an `htdocs` folder (or more generically whatever `WEBDIR` in `.bp-config/options.json` points to) then the build pack assumes you know what you're doing and configures that to be the public folder (i.e. doc root, what's public and visible to end users).

If there is no `htdocs` (or whatever `WEBDIR` is set to) folder then the build pack assumes that everything should be public, it creates an `htdocs` folder and moves everything into that folder.  Apache HTTPD or Nginx is then configured to serve up *everything* from this folder.

Two examples:

1.) When pushing a traditional PHP app, where you just have a bunch of PHP files that will be directly accessed (ex of this would be WordPress), all you need to do is push the files up.  The build pack will take everything and configure HTTPD or Nginx to serve up those files (technically PHP files are proxied to php-fpm, but it's basically the same thing).  

This is a very trivial [example](https://github.com/cloudfoundry/php-buildpack/tree/master/cf_spec/fixtures/php_app), but can help to demonstrate the behavior.  When you push this app, there is no `htdocs` folder so the build pack will move everything, which in this case is just index.php, into an `htdocs` folder that the build pack creates.

2.) When pushing a framework like CakePHP, there is often a designated "public" or "static" or "html" folder which contains everything that should be directly accessible.  In this case, you don't want the build pack to move things around, so you configure WEBDIR to point to the framework's public folder.  The build pack will see this, not move anything and configure HTTPD or Nginx to serve files from there.  

[Actual Example](https://github.com/cloudfoundry/php-buildpack/tree/master/cf_spec/fixtures/cake_with_remote_dependencies).  Note how [options.json](https://github.com/cloudfoundry/php-buildpack/blob/master/cf_spec/fixtures/cake_with_remote_dependencies/.bp-config/options.json#L2) is configured.  The build pack sees this setting and the fact that the referenced folder exists, so it will *not* move anything around.  It just configures HTTPD to serve up files from that location.

Hope that helps!

**Comment by sesmith177** [comment]
@lucaskuperman do you have further questions here? Thanks.

**Comment by sesmith177** [comment]
@lucaskuperman, just checking in. Have you had success?

**Comment by RochesterinNYC** [comment]
Closing due to lack of response. Please re-open if you have any updates.
