### ISSUE TITLE
LD_LIBRARY_PATH not set when using `cf ssh`

### ISSUE THREAD

**Issue by mweibel** [cloudfoundry/php-buildpack#168]
**What version of Cloud Foundry are you using?**
1.6 and also tested on PCF 1.8

**What version of the buildpack you are using?**
4.3.20

**If you were attempting to accomplish a task, what was it you were attempting to do?**
I ran `cf ssh` to SSH into an instance and then ran `~/app/php/bin/php -c ~/app/php/etc/php.ini -i` to check whether an extension was enabled or not.

**What did you expect to happen?**
The amqp/rabbitmq extension should have been loaded correctly and the LD_LIBRARY_PATH is being set correctly. 

**What was the actual behavior?**
PHP reports it can't find the shared library `amqp.so`:
```PHP Warning:  PHP Startup: Unable to load dynamic library '/home/vcap/app/php/lib/php/extensions/no-debug-non-zts-20151012/amqp.so' - librabbitmq.so.4: cannot open shared object file: No such file or directory in Unknown on line 0```

This is because the `LD_LIBRARY_PATH` is not set when running PHP from the CLI. It is however set correctly when using PHP-FPM because there the shell is loading `$HOME/app/.profile.d/bp_env_vars.sh` where `LD_LIBRARY_PATH` is being exported as `$LD_LIBRARY_PATH:$HOME/php/lib`.

Is there a reason why the normal shell is not having these env variables loaded and could this be added to this buildpack?

Please confirm where necessary:
* [x] I have included a log output 
* [ ] My log includes an error message 
* [x] I have included steps for reproduction

**Comment by sclevine** [comment]
I believe that this is the expected behavior of `cf ssh`. Have you tried following [these instructions](https://docs.cloudfoundry.org/devguide/deploy-apps/ssh-apps.html#ssh-env)?

**Comment by mweibel** [comment]
Ah I see. No this documentation is what I was looking for before opening the issue but somehow didn't find it :D 
Thanks. Makes all sense now after reading the docs.
