### ISSUE TITLE
Docs page links to 404

### ISSUE THREAD

**Issue by joshq00** [cloudfoundry/php-buildpack#172]
The [Development Documentation](https://github.com/cloudfoundry/php-buildpack/blob/master/docs/development.md) link in [the docs](http://docs.cloudfoundry.org/buildpacks/php/gsg-php-config.html#buildpack-extensions) sends users to a non existent file in the repo

**Comment by RochesterinNYC** [comment]
@joshq00 thanks for the heads-up. We've submitted the appropriate change to the docs: https://github.com/cloudfoundry/docs-buildpacks/pull/104
