### ISSUE TITLE
Can't get CGI to work

### ISSUE THREAD

**Issue by joshq00** [cloudfoundry/php-buildpack#173]
What version of the buildpack you are using?

> master

If you were attempting to accomplish a task, what was it you were attempting to do?

> include a cgi script

What did you expect to happen?

> the script would be executed

What was the actual behavior?

> the script was served for download

I have added "cgi" to the `options.json` and, inspecting the droplet, it appears to have added fast cgi, but I am hoping to have plain apache `cgi-bin` behavior. When calling the  script URL, the browser prompts for download. The same script behaves properly on shared hosting

**Comment by dmikusa-pivotal** [comment]
Including "cgi" in options.json only make sure that the binary is installed (and that is technically not necessary anymore as we install everything, all the time).

Adding that option, does not configure anything to use CGI. Out of the box the PHP build pack will only configure Fast-CGI. It does not configure regular CGI or mod_php. If you want to use either of those deployment methods then you'd need to reconfigure your web server (HTTPD or Nginx) and perhaps also some of the PHP config.

http://docs.cloudfoundry.org/buildpacks/php/gsg-php-config.html#engine-configurations

Is there a particular reason you can't use the FastCGI configuration? Can you explain more about the use case where you must have CGI to run a PHP script? Or are you trying to run a non-PHP CGI script?

**Comment by RochesterinNYC** [comment]
@joshq00 have you had a chance to review @dmikusa-pivotal's response and questions about your use case?

**Comment by joshq00** [comment]
Hey, sorry I've been out of pocket the last two weeks.

From what I've read, fast CGI requires an app to be listening on some port and binds to it. What I'm trying to do is exactly as you said at the end: run an arbitrary binary via plain CGI and use its output as the response. If this requires doing a lot of special twisting and poking, I can find another way (forced to shell out?)

**Comment by dmikusa-pivotal** [comment]
It is not something the PHP build pack configures out-of-the-box.  I'm sure it could be done though, and without forking the build pack.  It's just a matter of providing the proper HTTPD or Nginx config, which ever one you prefer.

My suggestion would be to start with either the [default HTTPD config](https://github.com/cloudfoundry/php-buildpack/tree/master/defaults/config/httpd) or the [default Nginx config](https://github.com/cloudfoundry/php-buildpack/tree/master/defaults/config/nginx) and adjust that to suite your needs.

As I mentioned before, you can [override the config from your application](http://docs.cloudfoundry.org/buildpacks/php/gsg-php-config.html#engine-configurations), so no need to fork the build pack.

If you decide to go this route, drop a comment here and let us know what config you changed.  Perhaps it will help someone else.

**Comment by sesmith177** [comment]
@joshq00 are you still having an issue with your configuration?

**Comment by joshq00** [comment]
@sesmith177 - I've been trying with many different configurations but haven't gotten one to work yet. If I do, I'll share it here

**Comment by RochesterinNYC** [comment]
@joshq00 We may be able to help investigate a little further if you provide a sample app of some kind.

**Comment by joshq00** [comment]
I finally got the proper configuration. I've pushed a [sample repo](https://github.com/joshq00/cgi-using-php-buildpack) for reference

**Comment by athornton2012** [comment]
@joshq00 thanks for providing the sample app for reference. Closing
