### ISSUE TITLE
Nginx HTTP2

### ISSUE THREAD

**Issue by stalmok** [cloudfoundry/php-buildpack#174]
What version of Cloud Foundry are you using? 6.22.2+a95e24c-2016-10-27
What version of the buildpack you are using? v4.3.21

I'm trying to enable HTTP2 on Nginx: `listen @{PORT} ssl http2;`, but I'm getting the error:

 ```
the "http2" parameter requires ngx_http_v2_module in /...
```

Is there a way to enable `ngx_http_v2_module`? If not, would you consider including it by default?

**Comment by jchesterpivotal** [comment]
Hi @stalmok,

At the moment, no.

Currently, the [official Nginx documentation says that the `ngx_http_v2_module` is experimental](https://nginx.org/en/docs/http/ngx_http_v2_module.html), and so we do not build and include it in our binaries.

We've [asked the Nginx project whether the documentation is still relevant](https://trac.nginx.org/nginx/ticket/1117#comment:3). 

This was [previously raised for another buildpack](https://github.com/cloudfoundry/staticfile-buildpack/issues/81), we're hoping that we get a resolution soon.

**Comment by dmikusa-pivotal** [comment]
Pardon me for asking, but what would be the point of having HTTP/2 support when CF does not support HTTP/2?  Aren't there other parts of the system like gorouter that would need to support HTTP/2 before adding it to the build pack would be relevant?

**Comment by jchesterpivotal** [comment]
You're right, @dmikusa-pivotal, I didn't realise that. Looking in the [GoRouter README](https://github.com/cloudfoundry/gorouter#http2-support), they specifically say that the router won't proxy HTTP/2 connections to backends.

@crhino, I see [this story in the router Tracker](https://www.pivotaltracker.com/story/show/128015611). Any sense of whether HTTP/2 is on a roadmap for the router?

**Comment by jchesterpivotal** [comment]
Hi @stalmok,

Having looked into this some more, we're going to close for now because of the GoRouter limitation. 

Once the router team give the thumbs up for HTTP/2 support, we'll schedule a story to pull in the `ngx_http_v2_module` with a warning about its experimental status.

**Comment by stalmok** [comment]
Sounds good, thanks.
