### ISSUE TITLE
Possible incorrect match PHP version specified

### ISSUE THREAD

**Issue by bonfilsd** [cloudfoundry/php-buildpack#176]
Hi, in the current last version of buildpack PHP (4.3.22), I've noticed that the file https://github.com/cloudfoundry/php-buildpack/blob/master/defaults/options.json#L12-L13 don't match with the real lastest version mentionned there :
- https://github.com/cloudfoundry/php-buildpack/blob/master/manifest.yml#L251
- https://github.com/cloudfoundry/php-buildpack/blob/master/manifest.yml#L369

Would you mind telling me if I right ?

Thanks a lot.

**Comment by bonfilsd** [comment]
Hi, my links was for master branch

This is for 4.3.22 tags version :
- https://github.com/cloudfoundry/php-buildpack/blob/v4.3.22/defaults/options.json#L12-L13
and 
- https://github.com/cloudfoundry/php-buildpack/blob/v4.3.22/manifest.yml#L251
- https://github.com/cloudfoundry/php-buildpack/blob/v4.3.22/manifest.yml#L369

Enjoy ;)

Have a good day.

**Comment by jchesterpivotal** [comment]
Hi @bonfilsd, thanks for bringing this to our attention! We lost sight of this interaction when we backfitted the `default_versions` functionality developed in other buildpacks.

**Comment by sesmith177** [comment]
Hello @bonfilsd, 

It turns out this has already been fixed on develop: https://github.com/cloudfoundry/php-buildpack/commit/63ce4e4695f5da8613eb60cd88d05799d7d40dd3

So the next release should be correct

**Comment by bonfilsd** [comment]
@sesmith177 ok thks a lot.
