### ISSUE TITLE
Broken URLs

### ISSUE THREAD

**Issue by eodchop** [cloudfoundry/php-buildpack#178]
What version of Cloud Foundry are you using?
1.7.2

What version of the buildpack you are using?
4.3.22
If you were attempting to accomplish a task, what was it you were attempting to do?
cf push

What did you expect to happen?
To be able to download files from dropbox. Urls are broken, getting a 404

What was the actual behavior?
buildpack fails to download files. All the files in options are broken.

Please confirm where necessary:
* [ ] I have included a log output 
* [] My log includes an error message 
* [x I have included steps for reproduction

[drupal-buildpack-errors.txt](https://github.com/cloudfoundry/php-buildpack/files/620315/drupal-buildpack-errors.txt)

**Comment by dmikusa-pivotal** [comment]
>What did you expect to happen?
>To be able to download files from dropbox. Urls are broken, getting a 404

There have not been files on dropbox for a long time now.  Files are now, and have been for quite some time, hosted on AWS S3.

Looking at the log you attached, the URL is definitely broken.  Not sure why.  Can you enable BP_DEBUG and attach a new set of logs?

https://docs.cloudfoundry.org/buildpacks/php/gsg-php-usage.html#troubleshooting

Thanks!

**Comment by RochesterinNYC** [comment]
@eodchop additionally, it seems like you're using a modified version of the php buildpack ? It's unclear from your log output what all the modifications are, but it is evident that the buildpack you are staging your app with is not [`v4.3.22`](https://github.com/cloudfoundry/php-buildpack/releases/tag/v4.3.22) as it was released. 

PHP Buildpack `v4.3.22` had httpd version `2.4.23`, but your staging logs indicate that `HTTPD 2.4.17` is being used.

It'd be helpful as well if you could either provide the source for the modified buildpack (if you have access to that) or some detail about how the buildpack is different/modified.

**Comment by athornton2012** [comment]
@eodchop any thoughts on @RochesterinNYC's comments?

**Comment by keaty** [comment]
Closing due to lack of response.
