### ISSUE TITLE
Buildpack will use default PHP version if an unsupported PHP version is explicitly specified

### ISSUE THREAD

**Issue by RochesterinNYC** [cloudfoundry/php-buildpack#181]
Buildpack version: `v4.3.13`

If you were attempting to accomplish a task, what was it you were attempting to do?
Push a PHP app using PHP `7.0.13` as specified by the `.bp-config/options.json` file:

```
{
    "PHP_EXTENSIONS": ["rdkafka"],
    "PHP_VERSION": "7.0.13"
}
```

What did you expect to happen?

The app to stage with PHP `7.0.13` or error out saying that my specified PHP version was not available.

What was the actual behavior?

The app staged with the default PHP version of `5.5.36`.

Reproducible app:

`index.php`:

```
<?php phpinfo() ?>
```

`.bp-config/options.json`:

```
{
    "PHP_VERSION": "7.0.13"
}
```

**Comment by keaty** [comment]
This has been prioritized: https://www.pivotaltracker.com/story/show/135526371

**Comment by sclevine** [comment]
This issue will be addressed in the story. Closing here.
