### ISSUE TITLE
Connection per SSH does not fully setup PHP environment

### ISSUE THREAD

**Issue by lbayerl** [cloudfoundry/php-buildpack#182]
**Steps to reproduce:**
1) Connect to an PHP buildpack based app with `cf ssh`.
2) Call `php -v`

**Actual Result:**
Bash complains that php cannot be found
**Expected Result:**
PHP CLI version is shown.

I learned that by calling `HOME=$HOME/app source app/.profile.d/bp_env_vars.sh` directly after logging into the app with cf ssh PHP CLI is available loaded/enabled extensions etc.

I am wondering whether this should be done implicitly by cf ssh.

Link to original question and answer on [StackOverflow](http://stackoverflow.com/questions/40999038/how-to-use-enable-php-extensions-for-cli-on-swisscomdev-cloudfoundry-php-buildba)

**Comment by dmikusa-pivotal** [comment]
To my knowledge there's nothing the build pack itself can do about this.  When you `cf ssh` into the environment, `.profile.d` scripts are not sourced.  That would need to be handled by the platform.  Maybe @RochesterinNYC or someone else from the build pack's team might have some ideas...

My $0.02, we could probably document this better.  I searched and couldn't readily find this in the docs.

**Comment by athornton2012** [comment]
@dmikusa-pivotal @lbayerl this is documented [here](https://docs.cloudfoundry.org/devguide/deploy-apps/ssh-apps.html#ssh-env) for future reference! Thanks
