### ISSUE TITLE
Ditch PHP 5.5 & Add PHP 7.1

### ISSUE THREAD

**Issue by dmikusa-pivotal** [cloudfoundry/php-buildpack#185]
What version of Cloud Foundry are you using? latest
What version of the buildpack you are using? 4.3.24 (all)

PHP 5.5 is out of support (since July) and not getting security fixes either -> https://secure.php.net/supported-versions.php

PHP 7.1 has been released -> https://secure.php.net/downloads.php

We should follow suite, drop 5.5 binaries and add 7.1 binaries.  That would bump the default version to 5.6, or we may want to bump it to 7.0 and push users in that direction.

Please comment with thoughts, especially on the choice of default version.

**Comment by sesmith177** [comment]
@dmikusa-pivotal We've been holding off on 7.1 so far because ioncube only supports up to 7.0.x. Ideally we'd like our PHP 7.0 and PHP 7.1 binaries to be built with the same extensions + versions. I think ioncube is the only extension right now that we include PHP 7.0 but has not released a version that supports PHP 7.1

That said, we only added ioncube support to PHP 7.0 in buildpack v4.3.23.

I agree that if PHP 5.5 isn't supported we should remove it.

**Comment by sclevine** [comment]
I'll send out a 30 day notice for removal of PHP 5.5 ASAP. We may want to consider creating tooling to monitor buildpack dependencies for EOL.

Dan, what are your thoughts on waiting for ioncube support before shipping PHP 7.1?

**Comment by dmikusa-pivotal** [comment]
They took forever to add support for 7.0.  IMHO we shouldn't wait on them.  PCF is supposed to encourage and help people to use the latest technologies.  We should try to get 7.1 into our user's hands as early as possible.  I was suggesting it now because the first stable release is available.

Could we perhaps make the ioncube recipe more robust so that it knows what PHP versions it supports and is conditionally build & included?  I was thinking that we could just temporarily hack around this until it's released, but we'll probably hit this same issue when PHP 7.2 or 7.5 or whatever is next is released.  Why not put in a proper fix now and do our future selves a favor :)

**Comment by sclevine** [comment]
Okay, I buy it. 7.1 story is unblocked, and notice for the 5.5 removal will go out soon.

**Comment by sesmith177** [comment]
Build 7.1 story: https://www.pivotaltracker.com/story/show/135296909

Remove 5.5. NOTICE: https://www.pivotaltracker.com/story/show/137306075

Closing issue.
