### ISSUE TITLE
Incorrect matches PHP versions specified

### ISSUE THREAD

**Issue by bonfilsd** [cloudfoundry/php-buildpack#191]
Hi, in the current last version of buildpack PHP (4.3.26), I've noticed that the file https://github.com/cloudfoundry/php-buildpack/blob/v4.3.26/defaults/options.json#L12-L14 doesn't match with the real latest version mentionned there :

* https://github.com/cloudfoundry/php-buildpack/blob/v4.3.26/manifest.yml#L186
* https://github.com/cloudfoundry/php-buildpack/blob/v4.3.26/manifest.yml#L322
* https://github.com/cloudfoundry/php-buildpack/blob/v4.3.26/manifest.yml#L476

Would you mind telling me if I right ?

Enjoy ;)

Have a good day.

**Comment by sclevine** [comment]
Thanks for the report!
Here's the story to address this mismatch: https://www.pivotaltracker.com/story/show/138616423

**Comment by sesmith177** [comment]
@bonfilsd This has been fixed on develop: https://github.com/cloudfoundry/php-buildpack/commit/0a82a58973910c7609bce37db2a42d2294df20ee. We also added a test to prevent this from happening again.

**Comment by bonfilsd** [comment]
@sesmith177 Thanks you for fix and test
