### ISSUE TITLE
Need instructions to have a buildpack with DB2/DashDB support with PDO

### ISSUE THREAD

**Issue by avibrazil** [cloudfoundry/php-buildpack#199]
I'm on Bluemix with buildpack 5.5.34.

How to extend it to support PDO capable of connecting to an IBM DB2 database ?

I see the binary-builder project and read its instructions, but was not clear for me the context and expected results, even if I'm used to compile, integrate and package open source software.

Thank you in advance.

**Comment by sclevine** [comment]
Seems like @fishfin is already working on this:
https://github.com/cloudfoundry/php-buildpack/pull/189/files

The binary-builder is a tool that helps us build the existing buildpack dependencies. You could extend it to build the IBM DB2 dependencies for your own use, but this is not necessary if you already have built versions of those dependencies.

**Comment by fishfin** [comment]
I am not clear on the binary-builder, so I am not working on it. I have however added PDO_IBM extension support to my repo (haven't had chance to test it, but shows up correctly in phpinfo()), so @avibrazil could use it.

**Comment by sclevine** [comment]
Closing this issue. Further PDO_IBM discussion can happen in #189.
