### ISSUE TITLE
Suggestion for php extension file

### ISSUE THREAD

**Issue by bonfilsd** [cloudfoundry/php-buildpack#201]
Hello all,

I would like to asking you a question.

Indeed, why don't have you kept the same directory tree for overload system of php extension file ?

In others terms, in https://github.com/cloudfoundry/php-buildpack/blob/v4.3.28/lib/php/extension.py#L134 file

why 
```python
.from_application('.bp-config/php') # noqa
```

wouldn't become 
```python
.from_application('.bp-config/php/%s.x' % major_minor') # noqa
```

like it's the case for defaults configuration file with 
```python
.or_from_build_pack('defaults/config/php/%s.x' % major_minor)
```
and who would allow us to switch with configuration file for different php version ?

I hope to have been specific in my speech.

Thank in advance for your answer.

Have a good day.

**Comment by dmikusa-pivotal** [comment]
>Indeed, why don't have you kept the same directory tree for overload system of php extension file ?

I don't recall any specific reason.  Likely just not something that we thought users would need.  

What I've typically seen is users focus on one branch of PHP and use that for a long time.  Not a lot of switching back and forth between say 5.5 and 5.6 or 5.6 and 7.0.  When you're ready to upgrade, if you have specific PHP configuration for your app then you'd just migrate it and bump the PHP version at the same time.  It's a one time thing.

Do you have a particular use case in mind?  Can you explain why you would need the build pack to handle multiple versions of PHP configuration in your app?

Thanks!

**Comment by bonfilsd** [comment]
No more specific case in mind. Just a reflexion for an eventualy automation for propose the PHP version on GUI and a reflexion on directory tree system like for httpd with the 'extra' directory.

Thanks.

**Comment by sclevine** [comment]
Closing this for now. We can re-visit if we're presented with a specific use-case.
