### ISSUE TITLE
The default timeout when using HTTPD & PHP is only 60 seconds

### ISSUE THREAD

**Issue by dmikusa-pivotal** [cloudfoundry/php-buildpack#212]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?

```
{
   "name": "",
   "build": "",
   "support": "https://support.run.pivotal.io",
   "version": 0,
   "description": "Cloud Foundry sponsored by Pivotal",
   "authorization_endpoint": "https://login.run.pivotal.io",
   "token_endpoint": "https://uaa.run.pivotal.io",
   "min_cli_version": "6.22.0",
   "min_recommended_cli_version": "latest",
   "api_version": "2.84.0",
   "app_ssh_endpoint": "ssh.run.pivotal.io:2222",
   "app_ssh_host_key_fingerprint": "e7:13:4e:32:ee:39:62:df:54:41:d7:f7:8b:b2:a7:6b",
   "app_ssh_oauth_client": "ssh-proxy",
   "routing_endpoint": "https://api.run.pivotal.io/routing",
   "doppler_logging_endpoint": "wss://doppler.run.pivotal.io:443",
   "user": "fb1b3b31-5963-464a-8c0f-40532114f2ac"
}
```

```
$ cf -v
cf version 6.26.0+9c9a261fd.2017-04-06
```

What version of the buildpack you are using?

4.3.33

If you were attempting to accomplish a task, what was it you were attempting to do?

If you send a slow request (>60s) to a PHP application, the FPM request from HTTPD to PHP will timeout.

```
2017-06-08T16:07:04.37-0400 [RTR/1] OUT php-info.cfapps.io - [2017-06-08T20:06:04.319+0000] "GET /slow.php?time=61 HTTP/1.1" 503 0 299 "-" "curl/7.54.0" "10.10.66.216:53173" "10.10.147.129:61028" x_forwarded_for:"50.4.153.215" x_forwarded_proto:"http" vcap_request_id:"4ae17531-0ddb-491a-69db-b98b7e7cc777" response_time:60.060113409 app_id:"54cccad6-9bba-45c6-bb52-83f56d765ff4" app_index:"0" x_b3_traceid:"d09e185aa1d1468c" x_b3_spanid:"d09e185aa1d1468c" x_b3_parentspanid:"-"
2017-06-08T16:07:04.37-0400 [RTR/1] OUT
2017-06-08T16:07:04.38-0400 [APP/PROC/WEB/0] OUT 20:07:04 httpd   | [Thu Jun 08 20:07:04.382603 2017] [proxy_fcgi:error] [pid 61:tid 140154379433728] (70007)The timeout specified has expired: [client 50.4.153.215:4484] AH01075: Error dispatching request to : (polling)
```

Note how the response time is almost exactly 60s.  This is coming from the Timeout [here](https://github.com/cloudfoundry/php-buildpack/blob/master/defaults/config/httpd/extra/httpd-default.conf#L1).

What did you expect to happen?
What was the actual behavior?

A timeout of 60s seems unnecessarily short.  The gorouter will let a request run for 900s by default.  It would be nice if the build pack could do something like gorouter timeout - 5s.  I'm not sure how you'd get the gorouter's timeout value though in the build pack.  Maybe we could make this more easily configurable for users?  Worst case, I think it would be reasonable to have a larger default timeout like something just shy of the gorouter's default.

I think the idea would be to append a ProxyTimeout setting [here](https://github.com/cloudfoundry/php-buildpack/blob/master/defaults/config/httpd/extra/httpd-php.conf).

Ex:

```
# Allow the proxy to wait for up to 895 seconds
#  this is just short of the default gorouter timeout of 900s
ProxyTimeout 895
```

Please confirm where necessary:
* [x] I have included a log output
* [x] My log includes an error message
* [x] I have included steps for reproduction

**Comment by sclevine** [comment]
(FYI: this was prioritized last week.)

**Comment by dgodd** [comment]
The default timeout for gorouter in code is 60s
https://github.com/cloudfoundry/gorouter/blob/2c94d87bcbbf5fecd942a051b08d1e0de4eaf2f9/config/config.go#L210

The default timeout for gorouter in bosh release config values is 900s
https://github.com/cloudfoundry-incubator/routing-release/blob/f322e85bce2bf97601beacb8af2e5ae7f6b88e68/jobs/gorouter/spec#L206-L208

We see two real options

**Option 1:**
buildpackapplifeccyle bosh release accepts request_timeout_in_seconds and sets an env variable for buildpacks during staging / runtime

**Option 2:**
Invent something similar to linkerd http header l5d-ctx-deadline.
Add it to gorouter and make PHP read it.
eg. PHP could set set-time-limit


Thoughts @dmikusa-pivotal  @sclevine

**Comment by sclevine** [comment]
Option 1 seems reasonable, and we could introduce this option once we break out the lifecycle into a standalone BOSH release. For now, we could just use 900s.

**Comment by dmikusa-pivotal** [comment]
@sclevine - Were we going to add ProxyTimeout into the config with a fixed value for now?  I don't see that in the config.  Or did we get option #1 implemented?

**Comment by dmikusa-pivotal** [comment]
It does not appear like this was ever fixed.

To manually fix:

1.) Download [this file](https://github.com/cloudfoundry/php-buildpack/blob/master/defaults/config/httpd/extra/httpd-php.conf) and put it into `.bp-config/httpd/extra/httpd-php.conf`.

2.) Edit the file from #1 and append the following to the end of the file.  Save.

```
# Allow the proxy to wait for up to 895 seconds
#  this is just short of the default gorouter timeout of 900s
ProxyTimeout 895
```

3.) Push your application.

The buildpack should pick up this file and override the default, applying the ProxyTimeout setting so that it waits up to 895 seconds for a response from the PHP FPM backend.

**Comment by ajitrishabh** [comment]
Hi @dmikusa-pivotal , this is not working in my case . im on HTTPD
how do i update max_execution_time (or any other suggestion) so that i should not get 504 error?

**Comment by ajitrishabh** [comment]
How i updated my max_execution_time.
1. go to this buildpack default folder (based on your PHP version)
[https://github.com/cloudfoundry/php-buildpack/tree/master/defaults/config/php](url)

2. take php.ini from the respective php version folder 
3. update php.ini and save the file in your project path below
[C:\xampp\htdocs\mindsphere\cfphpapp\sync-asset-master-app\local\.bp-config\php\php.ini.d](url)

4. push your app and check phpinfo

**Comment by dmikusa-pivotal** [comment]
That's one option, although you don't need to put the full php.ini file into `.bp-config/php/php.ini.d`. That folder will take snippets and they'll get merged into the default php.ini from the buildpack. In short, you could put a file like `exe_time.ini` with just `max_execution_time = xx` in that folder and it should work.

Alternatively, you can change php.ini settings in code or with a `.user.ini` file.

**Comment by ajitrishabh** [comment]
phpinfo is updated but still I'm getting 504 error. 
Most of the time only one page in my app is getting 504 error and this page fetch more api calls.
But after 2- 3 refresh it come and go.
What I can do to resolve this issue.

**Comment by dmikusa-pivotal** [comment]
Did you [apply this fix](https://github.com/cloudfoundry/php-buildpack/issues/212#issuecomment-396211189)? If so, you might be hitting a separate issue. What is the output from `cf logs` when your request gets a 504?

**Comment by ajitrishabh** [comment]
yes i apply the give suggestion but still im getting 504
log:
`2019-08-30T11:37:50.92+0530 [RTR/8] OUT sisreapp-ipmindev.apps.eu1.xxxxx.io - [2019-08-30T06:07:50.927+0000] "GET /js/series-label.js HTTP/1.1" 200 0 2704 "https://ipmindev-sreapp-ipmindev.eu1.xxxxx.io/kw_solar" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36" "172.16.xxx.61:58016" "172.16.xxx.36:61011" x_forwarded_for:"165.225.xxx.131, 18.195.xxx.204, 172.16.xxx.61" x_forwarded_proto:"https,https" vcap_request_id:"a62c8e13-979a-4d31-4d58" response_time:0.001885784 app_id:"0853469d-4dc5-49f8-aa07" app_index:"0"`

`i did cf logs APP_NAME --recent`

if anything else i have see please do let me know. we in bad situation because of this.

**Comment by dmikusa-pivotal** [comment]
That's not a 504, that's a 200, and the response time is less than a second. Try running `cf logs <app> > app.log` and then reproducing the error. Then look in `app.logs` for a request that has a status of 504. You need to see if it's coming from HTTPD or Gorouter or neither.

**Comment by ajitrishabh** [comment]
Okay will do as guided. and share the log here.

**Comment by ajitrishabh** [comment]
after doing this `cf logs <app> > app.log` nothing is happening when i reproduce the error.
i could not find `app.logs` file.
can you pls let me know where is `app.logs` file is stored

**Comment by dmikusa-pivotal** [comment]
It should write `app.log` (not `app.logs`) to the current directory. If it doesn't, you can always just run `cf logs your-app-name` and it'll write to STDOUT. It is just easier to share logs if you write them to a file.

**Comment by ajitrishabh** [comment]
Thanks, i was looking into container directory. but the log file is in local working directory.

please see the log file attached. i could not find anything wrong but as per my debug into the code i found if i assign non defined variable to below code it shows `504 error`
if i change `$totalWaterUtilization` variable to non existing variable like eg. `$totalWaterUtilizationTest` than i am getting `504 error`
```
$waterFile=fopen("kwWaterMonthData.json","w+");
fwrite($waterFile,json_encode($totalWaterUtilization));
fclose($waterFile);
```

[app.log](https://github.com/cloudfoundry/php-buildpack/files/3593751/app.log)

**Comment by dmikusa-pivotal** [comment]
There are hundreds of notice and warning messages in that file. It's going to be impossible for me to tell you anything from it. I would suggest clearing those up. Perhaps it'll help you narrow in on the issue.

**Comment by ajitrishabh** [comment]
Is there anyway I which I can I should not get notice and warning in the log file? 
But what about non existing variable part. If I put some different variable in the fwrite I got 504.

**Comment by dmikusa-pivotal** [comment]
The notices and warnings in that file are generated because of things being done in the app code. You would need to review your app code and see why those warnings are happening.

**Comment by ajitrishabh** [comment]
`   2019-09-11T15:39:40.98+0530 [RTR/4] OUT 
   2019-09-11T15:39:41.81+0530 [RTR/8] OUT sisreapp-ipmindev.apps.eu1.mindsphere.io - [2019-09-11T10:09:11.818+0000] "GET /kw_water HTTP/1.1" 499 0 22 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36" "172.16.100.68:33144" "172.16.102.52:61025" x_forwarded_for:"165.225.106.120, 18.195.251.204, 172.16.100.68" x_forwarded_proto:"https,https" vcap_request_id:"68af8dbc-404c-4d9a-40bf-fd0cb17da8ce" response_time:30.000547871 app_id:"0853469d-4dc5-49f8-aa07-fdbf68f7f9c6" app_index:"0"`

i think this is happening because of  **response_time:30.000547871**  this if my app takes more than 30s it send 504

i tried [this fix](https://github.com/cloudfoundry/php-buildpack/issues/212#issuecomment-396211189) pls check the attach file is it correct?

[httpd-php.conf.txt](https://github.com/cloudfoundry/php-buildpack/files/3600222/httpd-php.conf.txt)

**Comment by dmikusa-pivotal** [comment]
The default timeout is 60s. In your case, it's only making it 30s, so I don't think you are hitting the default timeout, at least not the one referenced in this issue. You are also getting a 499 response code, not 504. 499 means the client gave up before the response completed. In short, whatever is consuming the request from your app is not waiting long enough.
