### ISSUE TITLE
PHP_SELF not working correctly

### ISSUE THREAD

**Issue by macribas** [cloudfoundry/php-buildpack#216]
$_SERVER[PHP_SELF] should return the path to the current script. In the current version of the buildpack it is only returning the name of the script. 
For example: https://www.example.com/app/script.php should return /app/script.php but it is currently returning only /script.php.
It was running fine at least until v4.3.26.

**Comment by dmikusa-pivotal** [comment]
Looks like this is a known issue with HTTPD 2.4.26.

https://stackoverflow.com/questions/44657362/wrong-script-filename-php-self-in-apache-2-4-26/44714794#44714794

@sclevine - FYI, this might be what we were seeing [here](https://github.com/cloudfoundry/php-buildpack/issues/214#issuecomment-313873467) too.

**Comment by dmikusa-pivotal** [comment]
and this is fixed in 2.4.27 which just dropped:

```
  *) COMPATIBILITY: mod_proxy_fcgi: Revert to 2.4.20 FCGI behavior for the
     default ProxyFCGIBackendType, fixing a regression with PHP-FPM. PR 61202.
     [Jacob Champion, Jim Jagielski]
```

**Comment by sclevine** [comment]
Awesome, 2.4.27 should be in the next release.

**Comment by sclevine** [comment]
Fixed in the latest release.
