### ISSUE TITLE
mysqli library missing

### ISSUE THREAD

**Issue by whitfiea** [cloudfoundry/php-buildpack#22]
Hi,

I have been using this buildpack in cf/bluemix and everything was working as expected with my PHP/mysql app. Then the recent buildpack update to PHP 5.4.31 has broken my app as the mysql_\* and mysqli_\* functions are no longer found as the mysqli extension doesn't appear to be installed by default.

Was this an expected change?

**Comment by anirudhbagri** [comment]
How to add PHP_EXTENSIONS in PCF? I am not able to find ` .bp-config/options.json`. Do I need to create a new build-pack?

**Comment by dmikusa-pivotal** [comment]
FYI, while `PHP_EXTENSIONS` still works.  It has been deprecated in favor of the method describe here.

https://docs.cloudfoundry.org/buildpacks/php/gsg-php-config.html#php-extensions

**Comment by anirudhbagri** [comment]
Got it. Thanks a lot!

But how do I enable the extension in the build-pack?

**Comment by dmikusa-pivotal** [comment]
You don't.  You follow the instructions in the docs to enable PHP extensions for your application.

Is there a reason why you want to enable it in the buildpack?

**Comment by anirudhbagri** [comment]
My bad, I just want to enable it for my application, but I am not able to understand how to enable it in it my application as I am not able to find any .bp-config folder in my app.

**Comment by dmikusa-pivotal** [comment]
No worries.  `.bp-config` is a folder that is specific to the buildpack.  It's where it looks for configuration.  You don't need to have that folder with your app, but if you want to override the default configuration used by the buildpack, for example to enable specific PHP extensions, you would need to create the `.bp-config` under the root of your project (i.e. where you run `cf push`).

**Comment by anirudhbagri** [comment]
I want to add sqlite extension in my application. However I am not able to create `.bp-config` folder. (I am on windows machine).
After I create this folder do I need to create this? another folder structure like php/php.ini.d/mysqli.ini?

**Comment by dmikusa-pivotal** [comment]
You can create this folder on Windows.  You might need to tell File Explorer to show hidden files.  You could also do it via the Command Prompt or Powershell.  

>After I create this folder do I need to create this? another folder structure like php/php.ini.d/mysqli.ini?

Yes.  You need to create the folder structure *exactly* as described in the docs.

**Comment by anirudhbagri** [comment]
Thank a lot man!
