### ISSUE TITLE
Request for php extension

### ISSUE THREAD

**Issue by noo-zh** [cloudfoundry/php-buildpack#222]
Hi guys,

I would like to encrypt emails with PGP - could you add gnupg extension? I believe it would be great to have it in buildpack at least for PHP 7.1+

About: [GnuPG](http://php.net/manual/en/book.gnupg.php)

Many thanks!

**Comment by dmikusa-pivotal** [comment]
@noo-zh - I submitted a couple PRs that I believe should work here.  I've got a test setup if you want to try.  You can point your build pack here -> https://github.com/dmikusa-pivotal/php-buildpack#binary-build-tests

**Comment by noo-zh** [comment]
@dmikusa-pivotal I'll test it and let you know. Thanks!

**Comment by noo-zh** [comment]
@dmikusa-pivotal Tested, it works ;-)

**Comment by noo-zh** [comment]
It's merged now
