### ISSUE TITLE
Request memcached support for PHP 7.1

### ISSUE THREAD

**Issue by libnux** [cloudfoundry/php-buildpack#223]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?
cf: "api_version": "2.56.0",
cf cli: cf version 6.22.2+a95e24c-2016-10-27

What version of the buildpack you are using?
v4.3.37

If you were attempting to accomplish a task, what was it you were attempting to do?

What did you expect to happen?

According to https://github.com/php-memcached-dev/php-memcached, memcached extension now supports PHP 7.1.  
Could you please add the support of memcached for PHP 7.1? 

What was the actual behavior?
memcached is not supported yet.

Please confirm where necessary:
* [ ] I have included a log output
* [ ] My log includes an error message
* [ ] I have included steps for reproduction

**Comment by dmikusa-pivotal** [comment]
I submitted a couple PRs which I think should add support for Memcached in PHP 7.0 & 7.1.

**Comment by libnux** [comment]
Thank you. @dmikusa-pivotal. I'll have a try. 

Could you please tell me where I can find the list of extensions supported in your buildpack?

**Comment by dmikusa-pivotal** [comment]
Take a look at [manifest.yml](https://github.com/dmikusa-pivotal/php-buildpack/blob/master/manifest.yml).  Ex: PHP 7.1.8 -> https://github.com/dmikusa-pivotal/php-buildpack/blob/master/manifest.yml#L325-L377

**Comment by libnux** [comment]
Thanks, @dmikusa-pivotal.

**Comment by sclevine** [comment]
@dmikusa-pivotal anything left to do here?

**Comment by dmikusa-pivotal** [comment]
@sclevine - This says merged, but I don't see the memcached extension available, at least according to our release notes.

**Comment by dmikusa-pivotal** [comment]
@sclevine - I looked in the binary builder extension files and I see memcached.  I also see the extension if I `cf ssh` into a test container.  However, I don't see it listed in the buildpack manifest.yml, rather it's listed but only for the two PHP 5.6 versions.

Can we get this added for 7.0-7.2?  Thanks!

**Comment by ndon55555** [comment]
@dmikusa-pivotal & I confirm that current versions of php-buildpack have memcached extension included in the manifest.yml for all included versions of PHP. If you're still having issues feel free to reopen. Thanks!
