### ISSUE TITLE
pivotal cloud foundry throwing error with node

### ISSUE THREAD

**Issue by texirv0203** [cloudfoundry/php-buildpack#229]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?

What version of the buildpack you are using?

If you were attempting to accomplish a task, what was it you were attempting to do?

What did you expect to happen?

What was the actual behavior?

Please confirm where necessary:
* [ ] I have included a log output
* [ ] My log includes an error message
* [ ] I have included steps for reproduction

**Comment by sclevine** [comment]
Closing as this issue has no details and does not appear to be related to the PHP buildpack. If you have an issue with the Node.js buildpack, please open it [here](https://github.com/cloudfoundry/nodejs-buildpack/issues), with logs and a sample app if possible.
