### ISSUE TITLE
Critical: Argon2 algorithm not working in latest PHP 7.2

### ISSUE THREAD

**Issue by noo-zh** [cloudfoundry/php-buildpack#237]
Buildpack version: 4.3.46
Nginx version: 1.13.7
PHP version: 7.2.0

I have absolutely no idea how it is possible but when I try to use `password_hash($pwd, PASSWORD_ARGON2I)` on Cloud Foundry (via IBM Cloud) that should work in PHP 7.2 (and it actually works on my local PHP 7.2.0 environment), I get this: `use of undefined constant PASSWORD_ARGON2I`, so it doesn't work at all.

Maybe this issue is related to my second issue with [sodium](https://github.com/cloudfoundry/php-buildpack/issues/236) that should also works but doesn't.

It's really weird. Maybe broken source https://buildpacks.cloudfoundry.org/dependencies/php7/php7-7.2.0-linux-x64-1d0ba22b.tgz?

I will do more research.

**Comment by noo-zh** [comment]
Ok, so it seems that PHP must be compiled with `–with-password-argon2` to support Argon2. Could you do it? :-)

**Comment by sclevine** [comment]
Seems like other binary distributions of PHP 7.2 have this enabled (or are planning to enable it). Prioritizing this for next week.

**Comment by dgodd** [comment]
@noo-zh This actually requires libargon to be installed. Currently there is not a version of libargon for ubuntu trusty which is the upstream for cflinuxfs2. We are considering adding libargon to cflinuxfs3 which will be released in several months. Do you have a use case for needing this sooner?

**Comment by noo-zh** [comment]
@dgodd I see. Well, we've already upgraded our systems to PHP 7.2 and would like to use Argon2 for password hashing (especialy because we provide a new kind of authentication platform and would be nice to have latest measures). So I vote for adding libargon (as well as libsodium as I've created #236 - I expect it's a similar issue) as soon as possible but if it's not easy to add it sooner, we are able to wait and continue using bcrypt.

**Comment by dmikusa-pivotal** [comment]
@dgodd - Would you consider the solution where we bundle libargon with PHP?  We do this now for a number of libraries that are required by PHP & PHP extensions.  That would not require it to be included with the rootfs, however, it would require a new buildpack version if there is an update to libargon.  I have no idea how fast that library moves, so I'm not sure how often that might trigger a new buildpack. 

If it's something that would be acceptable, I can work on a PR to binary-builder.

**Comment by dgodd** [comment]
@dmikusa-pivotal We plan to include libargon in the buildpack. The story should already be scheduled in tracker

**Comment by dmikusa-pivotal** [comment]
👍

**Comment by noo-zh** [comment]
Hey guys, any news?

**Comment by respinoza** [comment]
@dmikusa-pivotal any news on this? Lets say that at this point of time it is not ideal to have to disable the argon2 hashing for apps deployed to CF.

Is there anything we can do to help out to get this done?

Thank you.

**Comment by astrieanna** [comment]
Hi @noo-zh @respinoza, this story is tagged `scheduled` because it's in our backlog. You can see our public backlog here https://www.pivotaltracker.com/n/projects/1042066 ; the story for this issue is https://www.pivotaltracker.com/story/show/153864475 .

While the backlog is always changing, it currently looks like we'd get to this story in the next few weeks.

**Comment by dmikusa-pivotal** [comment]
FYI, I have a fix for this. Working on a PR for binary-builder.

**Comment by dmikusa-pivotal** [comment]
@noo-zh @respinoza - I have submitted a PR for this. If you want to test, you can use this buildpack which will be available until the PR is merged.

https://github.com/dmikusa-pivotal/php-buildpack.git#argon2-enabled

It only packages PHP 7.2.9, so you need to specifically request that version.

Ex:

```
$ cat .bp-config/options.json
{
    "PHP_VERSION": "7.2.9"
}
```

This was my test which worked OK:

```
$ cat htdocs/argon.php
<?php
  print('password hash of "hello-world": ' . password_hash('hello-world!', PASSWORD_ARGON2I));
?>
```

Output:

```
password hash of "hello-world": $argon2i$v=19$m=1024,t=2,p=2$Sy83bG9nSnd0emVlbHFqOA$Fr8HIxc5VWDRUugaUu1GrF1FqJmzWw7IAHe4oSu+rUE
```

**Comment by respinoza** [comment]
@dmikusa-pivotal sorry for the late reply. I tested that argon is there like your test and seems fine, I couldn't test with a project as other extensions are missing like mbstring, bz2, etc. probably because of this being a branch and how it was packaged?
Anyhow, the important part is that argon2i is there out of the box.
Thank you again for tackling this issue. Looking forward for the next release.

**Comment by dmikusa-pivotal** [comment]
Those extensions should be there. I built it with the full complement of extensions. You probably just need to enable them. They are not enabled by default.

https://docs.cloudfoundry.org/buildpacks/php/gsg-php-config.html#php-extensions

**Comment by noo-zh** [comment]
Can confirm that Argon2 works. Looking forward PR to be merged.

**Comment by anyu** [comment]
Closing because we merged in [PR 38](https://github.com/cloudfoundry/binary-builder/pull/38/commits/da71d3e60922eeb25238b00543bf29eab7612889).

**Comment by rust-rs** [comment]
Should definitely install a newer version of `PHP` -> `brew install php`
