### ISSUE TITLE
Composer settings in `.bp-config\options.js` ignored

### ISSUE THREAD

**Issue by pburkholder** [cloudfoundry/php-buildpack#243]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?

```
{
   "name": "",
   "build": "",
   "support": "",
   "version": 0,
   "description": "",
   "authorization_endpoint": "https://login.fr.cloud.gov",
   "token_endpoint": "https://uaa.fr.cloud.gov",
   "min_cli_version": null,
   "min_recommended_cli_version": null,
   "api_version": "2.101.0",
   "app_ssh_endpoint": "ssh.fr.cloud.gov:2222",
   "app_ssh_host_key_fingerprint": "redacted",
   "app_ssh_oauth_client": "ssh-proxy",
   "doppler_logging_endpoint": "wss://doppler.fr.cloud.gov:443",
   "user": "redacted"
}
```

```
$ cf version
cf version 6.32.0+0191c33d9.2017-09-26
```

What version of the buildpack you are using?

```
buildpack: https://github.com/cloudfoundry/php-buildpack.git
```

If you were attempting to accomplish a task, what was it you were attempting to do?

I'm attempting to pass options to composer but nothing worked. So with these
.bp-config/options.js

```

{
  "WEB_SERVER": "httpd",
  "ADMIN_EMAIL": "your-email@example.com",
  "COMPOSER_INSTALL_OPTIONS": [
    "--this-should-fail"
  ],
  "COMPOSER_VENDOR_DIR": "pbtest"
}
```

What did you expect to happen?

I expected `cf push` to fail with an invalid option as it does on the CLI:

```
composer --this-should-fail


  [Symfony\Component\Console\Exception\RuntimeException]
  The "--this-should-fail" option does not exist.
```

And I expected composer to vendor stuff into `pbtest`

What was the actual behavior?

* No failure
* SSH into container and `find . -name 'pbtest'` turns up nothing

Completed run, no errors.

Please confirm where necessary:
* [ ] I have included a log output
* [ ] My log includes an error message
* [x] I have included steps for reproduction

See https://github.com/pburkholder/php-micro

**Comment by pburkholder** [comment]
@lbayerl you've had helpful insight on these types of issues before. Did this happen on older PHP buildpacks? Thanks.

**Comment by dmikusa-pivotal** [comment]
I tried to replicate this issue, but wasn't able to on PWS.

My `.bp-config/options.json`

```
{
    "COMPOSER_INSTALL_OPTIONS": ["--this-should-fail"],
    "COMPOSER_VENDOR_DIR": "pbtest"
}
```

My manifest.yml:

```
---
applications:
- name: composer-demo
  memory: 128M
  instances: 1
  host: composer-demo
  path: .
  buildpack: https://github.com/cloudfoundry/php-buildpack.git
  env:
    BP_DEBUG: true
```

and the result of staging is

```
  [Symfony\Component\Console\Exception\RuntimeException]
  The "--this-should-fail" option does not exist.

install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--] [<packages>]...
-----> Composer command failed
```

which appears to be the expected behavior.  I will also try with your test app.

**Comment by dmikusa-pivotal** [comment]
I think I see the issue.  You have `.bp-config/options.js`, but it should be `.bp-config/options.json`.  Breaks as expected if I rename the file.

**Comment by pburkholder** [comment]
https://media.giphy.com/media/AjYsTtVxEEBPO/giphy.gif
