### ISSUE TITLE
Install latest newrelic agent version to support PHP 7.2

### ISSUE THREAD

**Issue by Tobion** [cloudfoundry/php-buildpack#244]
The latest release https://github.com/cloudfoundry/php-buildpack/releases/tag/v4.3.47 includes `newrelic 7.6.0.201` which does not support PHP 7.2. According to https://docs.newrelic.com/docs/release-notes/agent-release-notes/php-release-notes it needs PHP Agent 7.7.0.203. Please release a new buildpack version with the upgraded newrelic agent.

What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?
"api_version": "2.65.0"
cf version 6.26.0+9c9a261.2017-04-06

What version of the buildpack you are using?
v4.3.47

If you were attempting to accomplish a task, what was it you were attempting to do?
Run PHP 7.2 with newrelic support.

What did you expect to happen?
The newrelic extension is loaded successfully.

What was the actual behavior?
> PHP Warning:  PHP Startup: Unable to load dynamic library '/home/vcap/app/newrelic/agent/x64/newrelic-20170718.so' (tried: /home/vcap/app/newrelic/agent/x64/newrelic-20170718.so (/home/vcap/app/newrelic/agent/x64/newrelic-20170718.so: cannot open shared object file: No such file or directory), /home/vcap/app/php/lib/php/extensions/no-debug-non-zts-20170718//home/vcap/app/newrelic/agent/x64/newrelic-20170718.so.so (/home/vcap/app/php/lib/php/extensions/no-debug-non-zts-20170718//home/vcap/app/newrelic/agent/x64/newrelic-20170718.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0

Please confirm where necessary:
* [x] I have included a log output
* [x] My log includes an error message
* [x] I have included steps for reproduction

**Comment by dgodd** [comment]
@Tobion This has already been changed on the develop branch (See: https://www.pivotaltracker.com/story/show/154221500). I expect that to be released in the next few days.

**Comment by Tobion** [comment]
Thanks @dgodd
