### ISSUE TITLE
How to install or enable oauth into this buildpack?

### ISSUE THREAD

**Issue by westerjn** [cloudfoundry/php-buildpack#249]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?

{
   "name": "",
   "build": "",
   "support": "https://support.pivotal.io",
   "version": 0,
   "description": "",
   "min_cli_version": "6.23.0",
   "min_recommended_cli_version": "6.23.0",
   "api_version": "2.75.0",
   "app_ssh_oauth_client": "ssh-proxy",
}

If you were attempting to accomplish a task, what was it you were attempting to do?
As a user, I need to enable oauth in my php app using a github repo only [no root access when ssh into my image]

What did you expect to happen?
perform 'cf push my_app' then view a php page (based on fireeagle php example) with oauth url, client_id, client_secret and have it authenticate with oauth end point.

What was the actual behavior?
oauth could not be found

**Comment by westerjn** [comment]
I have a test app in php that basically uses the FireEagle (http://php.net/manual/en/oauth.examples.fireeagle.php) as the client to connect to a Pivotal SSO Tile.  I guess my operational steps are:

1.  Create a new php app using the fireeagle.php page as the index page (home.php)
2. cf push authapp
3. bind SSO Tile service to authapp
4. complete service config so SSO Tile generates CLIENT_ID, CLIENT_SECRET
5. cf push authapp again (optionally) to make sure the service is bound to app
6. go to the app home page

At this point I get the error in logs:
AH01071: Got error 'PHP message: PHP Notice: Undefined index: state in /home/vcap/app/htdocs/home.php on line 13\nPHP message: PHP Fatal error: Uncaught Error: Class 'OAuth' not found in /home/vcap/app/htdocs/home.php:15\nStack trace:\n#0 {main}\n thrown in /home/vcap/app/htdocs/home.php on line 15\n'

I am guessing I need the PHP OAuth extension, however, my ISP has turned off root access for ssh, so I need to install the extension and the docs don't say how to install it in .bp-config/options.json

Ideally, I'd just like to add an extension to the options.json but will take any best practice how to add this extension, or prefered practice to get an oauth library installed (constraint: ISP has locked root access in our droplets).

I have my options.json here for reference:
https://github.com/westerjn/Pivotal-SSO-Client

**Comment by dmikusa-pivotal** [comment]
>I am guessing I need the PHP OAuth extension, 

I took a look at the example you linked, thanks for that, and it appears to be using the following PECL extension.  We don't ship this with the buildpack currently, but I don't see any reason we can't add it.

https://secure.php.net/manual/en/oauth.installation.php
https://pecl.php.net/package/oauth

>I am guessing I need the PHP OAuth extension, however, my ISP has turned off root access for ssh, so I need to install the extension and the docs don't say how to install it in .bp-config/options.json

This is could be due to PCF.  When you SSH into an application on PCF, you do not and cannot get root access.  That's normal.

>Ideally, I'd just like to add an extension to the options.json but will take any best practice how to add this extension, or prefered practice to get an oauth library installed (constraint: ISP has locked root access in our droplets).

We used to add them through options.json, but there is a new preferred way, adding `php.ini` snippets.  You can see the instructions here.

https://docs.cloudfoundry.org/buildpacks/php/gsg-php-config.html#php-extensions

Again, you'll have to wait until we can get that extension build and added.  It shouldn't be too difficult as it's just a PECL extension.  I can submit a PR for that.  Stay tuned.

**Comment by westerjn** [comment]
Ok cool.

In the meantime, will adding `extension=oauth.so` to php,ini install oauth to the droplet?

And/or;  in general, how are people plugging oauth into php pivotal containers currently?

**Comment by dmikusa-pivotal** [comment]
I submitted a PR, so the oauth extension should get picked up in the next buildpack release after the PR is merged.  I added a couple other unrelated extensions in that PR, don't worry about those for the purposes of this issue.

In the meantime, you can try it out by using my forked buildpack.

https://github.com/dmikusa-pivotal/php-buildpack/tree/v4.3.49_bonus

Just set the buildpack for your app to `https://github.com/dmikusa-pivotal/php-buildpack#v4.3.49_bonus`, then create the file `.bp-config/php/php.ini.d/extensions.ini` with the following in it.

```
extension=oauth.so
```

Then push your app, and the extension should be available.

<img width="954" alt="screen shot 2018-02-19 at 10 23 28 pm" src="https://user-images.githubusercontent.com/4643262/36406255-928d7b42-15c3-11e8-8c8b-ab639f09ef35.png">

**Comment by westerjn** [comment]
Thank you so much!  There are a bunch of teams here that will be grateful since security is requiring Pivotal SSO Tile.

**Comment by dmikusa-pivotal** [comment]
@westerjn - the latest PHP buildpack now has the oauth extension included.

https://github.com/cloudfoundry/php-buildpack/releases/tag/v4.3.51

Please give it a try and let us know if there are any problems, otherwise we'll go ahead and close out this issue.

**Comment by tylerphelan** [comment]
@westerjn closing, feel free to open again if you have problems
