### ISSUE TITLE
PHP Extension Review

### ISSUE THREAD

**Issue by dmikusa-pivotal** [cloudfoundry/php-buildpack#250]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?

N/A

What version of the buildpack you are using?

4.3.49

If you were attempting to accomplish a task, what was it you were attempting to do?

Reviewing which extensions are included across versions 5.6, 7.0, 7.1 and 7.2.

What did you expect to happen?

Roughly the same extension ship with every version, where compatibility permits.

What was the actual behavior?

I did a review of the extensions that ship with 5.6, 7.0, 7.1 and  7.2.  Here are the discrepancies I found.

## Dead

The following extensions ship if 5.6, but not in 7+.

 - gearman -> replaced by a pure [PHP library](http://gearman.org/download/#net_gearman)
 - suhosin -> appears dead, there is an pre-alpha branch for 7.0, but it hasn't been updated in years
 - twig -> no longer necessary, replaced by pure PHP library of the same name.
 - xcache -> appears dead, there are no 7.0 compatible releases and the latest is from 2014
 - protocolbuffers -> appears dead, last release was alpha and from 2014
 - sundown -> appears dead, last release was beta and in 2014

The following have some support for 7+.
 - mcrypt -> this has been removed from PHP in 7.2, users need to migrate their code.
 - solr -> this does not appear to have a 7.2 compatible release yet, but is being maintained so we can package one as soon as it's released

The above is informational only.  With the exception of solr, the extensions above do not appear like they will ever have 7+ support, thus do not appear like they'll be included in the buildpack going forward.  

## Need Replaced

These are currently not in PHP 7+, but have alternatives with which they can be replaced.

- mssql, pdo_mssql, pdo_dblib -> removed (pdo_dblib not technically removed but equally replaced), but replaced by [sqlsrv](https://pecl.php.net/package/sqlsrv) and [pdo_sqlsrv](https://pecl.php.net/package/pdo_sqlsrv) which appears to be MIT licensed -> https://github.com/Microsoft/msphpsql
- xhprof -> the official release is dead and no 7+ support, however there seem to be unofficial forks.  the most promising looks to be called tideways.

## Broken

The following should be supported but look to have issues with our build scripts.

- ~~ioncube -> for some reason we are not including it with 7.1, but it is compatible~~
- ~~readline -> not consistent, it's being built as a shared extension for 5.6, but added statically for 7+~~
- ~~phalcon -> for some reason we are not including it with 7.1, but it is compatible~~

Please confirm where necessary:
* [X] I have included a log output
* [X] My log includes an error message
* [X] I have included steps for reproduction

**Comment by dmikusa-pivotal** [comment]
PR to address ioncube & phalcon for PHP 7.1.

https://github.com/cloudfoundry/binary-builder/pull/34

**Comment by dmikusa-pivotal** [comment]
PR to possibly address readline for PHP7+.

https://github.com/cloudfoundry/binary-builder/pull/35

**Comment by dgodd** [comment]
HI @dmikusa-pivotal , having read this I'm not sure if this is anything to do (other than your existing PRs). Have I missed something?

**Comment by dmikusa-pivotal** [comment]
It was mostly for reference, if people see an extension disappear, this will hopefully point to why.

I think these are the two action items remaining:

- mssql, pdo_mssql, pdo_dblib -> removed (pdo_dblib not technically removed but equally replaced), but replaced by sqlsrv and pdo_sqlsrv which appears to be MIT licensed -> https://github.com/Microsoft/msphpsql
- xhprof -> the official release is dead and no 7+ support, however there seem to be unofficial forks. the most promising looks to be called tideways.

Right now these extensions are in the 5.6 binaries, but not in any of our 7+ binaries.  Not urgent, but I suspect users will want these to be included.

I'd be happy to submit PRs.  I don't think they'll be too much work.  I just have to find some time :)

**Comment by dmikusa-pivotal** [comment]
For reference, buildpack 4.3.5.1 has the ioncube + phalcon fixes.

https://github.com/cloudfoundry/php-buildpack/releases/tag/v4.3.51

**Comment by dmikusa-pivotal** [comment]
Buildpack 4.3.51 didn't pick up the readline extension for 7+ because the build system was not told to compile that extension.  PR to resolve that here -> https://github.com/cloudfoundry/public-buildpacks-ci-robots/pull/6

**Comment by dmikusa-pivotal** [comment]
I looked into msphpsql.  It looks like it will require Ubuntu 16.04+, there are no builds for the driver download from Microsoft for 14.04.  It also looks like while we can package the PHP extension, we probably can't ship the driver which is a binary from Microsoft, not OSS.  Once we're on a more recent Ubuntu version, I think we could just bundle the OSS bits and users could use the apt buildpack to install the Microsoft bits which are available from their apt repos.

**Comment by jfeeny** [comment]
Hey @dmikusa-pivotal, are there more action items on this issue, or can we close it?

**Comment by dmikusa-pivotal** [comment]
I think MSSQL is still missing.  That could be a while though cause it's going to require a newer rootfs.  Can we keep this on hold I know we're gearing up for cflinuxfs3?

**Comment by lenisha** [comment]
@dmikusa-pivotal  Hi Daniel, I have compiled msphpsql for Ubuntu 14 (it worked on Ununtu 14LTS) and now trying to include them along with the application  in `php/php.d.ini/` example here https://github.com/lenisha/cf-php . But staging does not attempt to load them. What is wrong with the approach?

**Comment by dmikusa-pivotal** [comment]
You have a typo, it should be `.bp-config` not `.bp_config`. If you fix that, it should load your custom ini snippet.

I think the issue is that the buildpack tries to validate the extensions you're loading and it's going to fail because sqlsrv and pdo_sqlsrv are not in the buildpack's metadata (manifest.yml). You might be able to hack around this, but it'd be better if you used binary-builder to package them in a PHP build. Then you can build your own buildpack using buildpack packager that has your custom PHP binary in it.

**Comment by lenisha** [comment]
Thank you for the catch -it started processing but fails validating the extensions as they are indeed not inside buildpack. Is there a way to load custom extensions? 
```
File "/tmp/buildpackdownloads/22b926f1d331aee7ce1d8a51f2849125/lib/php/extension.py", line 142, in _compile validate_php_ini_extensions(ctx)
     File "/tmp/buildpackdownloads/22b926f1d331aee7ce1d8a51f2849125/lib/compile_helpers.py", line 177, in validate_php_ini_extensions
       raise RuntimeError("The extension '%s' is not provided by this buildpack." % ext)
```

**Comment by dmikusa-pivotal** [comment]
Yes, that is what I mentioned above. The buildpack checks your included extensions and bails if you ask for one that we do not package. This fail fast gives feedback when required extensions are missing.

You can probably hack around this by adding a `.profile` file to your project and dynamically adding your extensions to the `php.ini.d/` snippet file. The profile script runs after staging but before your app starts so it's the perfect time to make such an adjustment.

**Comment by tylerphelan** [comment]
@dmikusa-pivotal I think we can close this since we added `sqlsrv` https://www.pivotaltracker.com/story/show/162546591

Please re-open if I'm mistaken!
