### ISSUE TITLE
options.json PHP_EXTENSIONS deprecated; by what?

### ISSUE THREAD

**Issue by drnic** [cloudfoundry/php-buildpack#252]
I'm seeing the warning:

```
   Warning: PHP_EXTENSIONS in options.json is deprecated. See: http://docs.cloudfoundry.org/buildpacks/php/gsg-php-config.html
```

My `.bp-config/options.json` file looks like:

```json
{
   "PHP_MODULES": [ "cli",  "pear", "fpm" ],
   "PHP_EXTENSIONS": [ "openssl" ],
   "PHP_VERSION": "{PHP_71_LATEST}"
}
```

In fixture https://github.com/cloudfoundry/php-buildpack/blob/master/fixtures/php_71_all_modules/.bp-config/options.json#L3 it still shows this as the example for installing extensions.

Is there an example/fixture that shows how you'd like PHP_EXTENSIONS to be specified? I tried reading the documentation but as a non-PHP person I wasn't able to discern how I was supposed to change my project.

**Comment by dmikusa-pivotal** [comment]
This is the most relevant doc -> https://docs.cloudfoundry.org/buildpacks/php/gsg-php-config.html#php-extensions

Here's an example fixture -> https://github.com/cloudfoundry/php-buildpack/blob/master/fixtures/php_5_with_php_ini_d/.bp-config/php/php.ini.d/php.ini

There are similar for php7+, but how you do this does not depend on the version.

Hope that helps!

**Comment by drnic** [comment]
Ok, I've created `.bp-config/php/php.ini.d/openssh.ini`:

```ini
[PHP]

extension = openssl.so
```

During `cf push` there is no output related to using/installing the extension. I guess I now miss my warning - at least it mentioned it was going to do it but it just wasn't happy about it :)

**Comment by dmikusa-pivotal** [comment]
@drnic  - No news is good news!  The buildpack will validate the extensions that you put into that file.  If you insert one that does not exist (i.e. not shipped by the buildpack), you will get an error.

>The extension 'doesnotexist' is not provided by this buildpack.

https://github.com/cloudfoundry/php-buildpack/blob/master/lib/compile_helpers.py#L171

If you want positive confirmation, you can validate after the fact in your php code.  The easiest way is to drop in a test file, like `info.php` with the contents:

```
<?php
  phpinfo();
?>
```

Or you can run `cf ssh <app-name> -t -c "/tmp/lifecycle/launcher /home/vcap/app bash ''"` then run `php -i`.  That should give you similar output.

Both will give you a breakdown of what's installed into PHP & how it's configured.

**Comment by drnic** [comment]
Thanks!
