### ISSUE TITLE
Move auth.json for composer into the root directory

### ISSUE THREAD

**Issue by ocean90** [cloudfoundry/php-buildpack#258]
The composer extension [moves](https://github.com/cloudfoundry/php-buildpack/blob/86861d985f6240ba5a8ec445c2a7b8255a5df22b/extensions/composer/extension.py#L306-L319) `composer.json` and `composer.lock` into the root directory but not `auth.json` if it exists.

[`auth.json`](https://getcomposer.org/doc/articles/http-basic-authentication.md) can be used to provide basic authentication credentials. By default composer searches them in `COMPOSER_HOME` or besides the `composer.json`. Since only the composer files are moved composer can't find the `auth.json` anymore. Therefore I suggest to move the file as well.

Is there a way to run a command _before_ the buildpack/composer starts? I guess that can be used too but I haven't found such a way yet.

**Comment by dmikusa-pivotal** [comment]
I can't think of a way to work around this short of a code fix.  The code fix is pretty simple, if you want to fork and edit so you can have a temporary fix.

Basically, you need to edit [this section](https://github.com/cloudfoundry/php-buildpack#adding-extensions).  It's what moves the composer json and lock files into the correct location.  You could probably do something like...

1. Get the director of the composer.json file by stripping composer.json off the end
2. Check if composer.json directory contains auth.json
3. If it does, move the file to the same directory where composer.json is moved.

After that, it should just work.  auth.json should be in the right place for Composer to see it.

**Comment by tylerphelan** [comment]
@sclevine this may be something to pull in ^ thoughts?

**Comment by ameyer-pivotal** [comment]
@ocean90 Thanks for bringing this up. We've addressed it, so keep an eye out for it in the next release, v4.3.53!
