### ISSUE TITLE
Enable opcache by default

### ISSUE THREAD

**Issue by CAFxX** [cloudfoundry/php-buildpack#265]
> OPcache improves PHP performance by storing precompiled script bytecode in shared memory, thereby removing the need for PHP to load and parse scripts on each request.

Opcache can be used ([1](https://symfony.com/doc/current/performance.html#performance-use-opcache), [2](https://haydenjames.io/php-benchmarks-opcache-performance-tweaks/), [3](https://blog.appdynamics.com/engineering/why-every-php-application-should-use-an-opcache/)) to decrease CPU usage at the expense of increased memory usage (up to 64mb by default), and it is normally recommended to run with opcache enabled for maximum performance of "complex" applications. The [default configuration](http://jp2.php.net/manual/en/opcache.configuration.php) of opcache is pretty conservative and it is unlikely to cause problems - especially in immutable applications. The documentation also includes [recommendations about the configuration](http://jp2.php.net/manual/en/opcache.installation.php#opcache.installation.recommended).

Unless there are significant concerns, would it be reasonable to enable opcache by default?

Optionally, to address the memory usage concern, one could imagine to enable opcache only if the application is running with e.g. 256MB or more of memory; or alternatively to configure the maximum memory that opcache can use as a fraction of the container memory.

**Comment by ameyer-pivotal** [comment]
@CAFxX Sounds reasonable. I'd be curious what @dmikusa-pivotal and @sclevine think of this idea.

**Comment by dmikusa-pivotal** [comment]
-1 for enabling it by default.  I think the PHP we ship should be as lean as possible out of the box.  Include all the extensions possible, but don't enable them unless a user specifically needs them.  It's also super easy to turn on extensions when you need them (php.ini snippets or your composer.json), so I'm not sure why we'd want to turn this or any other extensions on by default.

The suggestion of auto enabling it is is intriguing.  If there's over a certain amount of RAM or perhaps based on the presence of certain framework files?  Like enable it for symphony apps or others where it's know to help.  I think either of those would be OK.

**Comment by CAFxX** [comment]
Enabling it only in certain cases may be a little surprising, but if clearly documented then I see no big problems.

**Comment by sclevine** [comment]
@dmikusa-pivotal @CAFxX I'm willing to prioritize this if you can agree on the correct criteria for enabling opcache.

**Comment by dmikusa-pivotal** [comment]
It looks like this will change if we update the php.ini defaults per this issue -> https://github.com/cloudfoundry/php-buildpack/issues/303

I'm going to flip-flop here to make this easy and say let's just go with the defaults in php.ini.production.

My main concern was someone running an app with a small amount of memory, which you can do with PHP, and having this suddenly start pushing them over their memory limit. I think that's probably not a huge audience and I think we can get around that so long as we make some sort of announcement about the change & provide instructions for disabling it (which are pretty easy, a php.ini snippet or .user.ini file).

Sound good?

**Comment by ForestEckhardt** [comment]
@dmikusa-pivotal and I have updated the PHP buildpack to use the latest version of php.ini from PHP.net (for 7.1, 7.2 and 7.3). This change is in the develop branch if you're interested in testing it and should get picked up in the next release.

**Comment by dfreilich** [comment]
@CAFxX  Thanks for suggesting it! As mentioned above, it will be released in the next PHP Buildpack (`v4.3.80`), and it is already in our new [php-web-cnb](https://github.com/cloudfoundry/php-web-cnb/commit/fdbd12d0c356c8a73202ffa890820c1c00ab5390).
