### ISSUE TITLE
license of some modules in php-buildpack 4.3.51

### ISSUE THREAD

**Issue by luisapace** [cloudfoundry/php-buildpack#266]
Hi, my team would like to use php-buildpack 4.3.51 and to approve that I've to analyze it's source code and the code of its dependencies chain, so be sure that they don't have problematic licenses.

Now I've found that there are the modules found at:

<img width="592" alt="image" src="https://user-images.githubusercontent.com/27818611/41229562-c40e7e26-6d7c-11e8-88e8-a08ac16a49e7.png">

coming from:
https://github.com/cloudfoundry/php-buildpack/tree/v4.3.51/fixtures/symfony_2_local_deps/vendor/doctrine/orm/lib/Doctrine/ORM

and those found at:

<img width="510" alt="image" src="https://user-images.githubusercontent.com/27818611/41230202-2e8d5252-6d7f-11e8-9d0c-708ca07b0b4c.png">

that indicate MIT as license in the first part of the module, but some rows after reference LGPL license ( * @license     http://www.opensource.org/licenses/lgpl-license.php LGPL)

as you can see - as example - in: 

https://github.com/cloudfoundry/php-buildpack/blob/v4.3.51/fixtures/symfony_2_local_deps/vendor/doctrine/orm/lib/Doctrine/ORM/Event/PreFlushEventArgs.php 

Could you please indicate me what is the license of those modules and - if MIT - tell me what is the part under LGPL?

Thanks a lot.

**Comment by dmikusa-pivotal** [comment]
Just an FYI, but everything under `fixtures/` is a test case for the buildpack.  It only runs or is needed when you are building/testing the buildpack.  

Also, anything under a `vendor/` directory is a third party dependency, one that we are just using.  You may have better luck directing questions about third party dependency licenses to the third party directly.

**Comment by luisapace** [comment]
Thanks for your quick answer. 

If everything under fixtures/ is a test case for the buildpack, is it included in the buildpack, after it's built? or the build does not contain everything under fixtures/ anymore? 

Thanks again.

**Comment by dmikusa-pivotal** [comment]
It does not look like `fixtures/` is actually included in the release buildpack.  See here -> https://github.com/cloudfoundry/php-buildpack/releases

**Comment by luisapace** [comment]
Great! Thanks a lot again for your quick followup.
