### ISSUE TITLE
Suppress download progress

### ISSUE THREAD

**Issue by ocean90** [cloudfoundry/php-buildpack#272]
**What version of Cloud Foundry and CF CLI are you using?**

2.114.0 and 6.37.0+a40009753.2018-05-25

**What version of the buildpack you are using?**

4.3.57

**What did you expect to happen?**

When running `cf push` no download stats without context should be displayed.

**What was the actual behavior?**

```
   Installing Nginx
   Downloaded [https://buildpacks.cloudfoundry.org/dependencies/nginx/nginx-1.15.0-linux-x64-fcf8f112.tgz] to [/tmp]
   NGINX 1.15.0
   WARNING: A version of PHP has been specified in both `composer.json` and `./bp-config/options.json`.
   WARNING: The version defined in `composer.json` will be used.
   Installing PHP
   PHP 7.1.17
   Downloaded [https://buildpacks.cloudfoundry.org/dependencies/php7/php7-7.1.17-linux-x64-5306e01c.tgz] to [/tmp]
   Downloaded [https://buildpacks.cloudfoundry.org/dependencies/php7/php7-7.1.17-linux-x64-5306e01c.tgz] to [/tmp]
   Downloaded [https://buildpacks.cloudfoundry.org/dependencies/composer/composer-1.6.5-67bebe9d.phar] to [/tmp]
     % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                    Dload  Upload   Total   Spent    Left  Speed
     0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
   100   387  100   387    0     0    797      0 --:--:-- --:--:-- --:--:--   799
   -----> Using custom GitHub OAuth token in $COMPOSER_GITHUB_OAUTH_TOKEN
     % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                    Dload  Upload   Total   Spent    Left  Speed
     0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
   100   387  100   387    0     0    905      0 --:--:-- --:--:-- --:--:--   908
   Installing WP-CLI
   Downloaded [https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar] to [/tmp/wp]
   Finished: [2018-07-04 15:33:56.341171]
   Exit status 0
```

**Comment by ocean90** [comment]
Good question. I think the first issue ist that I have four "Downloaded …" messages but only two stats. If the last one is for WP-CLI, why is it before "Installing WP-CLI"? If the first one is for composer, why is it displayed after the "Downloaded" message?

This is a bit related to #271 which has a more detailed log attached. Let me know if you need more info.

**Comment by dmikusa-pivotal** [comment]
This is probably coming from [here](https://github.com/cloudfoundry/php-buildpack/blob/master/extensions/composer/extension.py#L237-L275).  It's shelling out to curl for some reason & the download progress looks like that of `curl`.  Easiest fix would be to add `-s` to `curl`, but I don't think there's any reason to use `curl`.  It would probably make more sense to just use `urllib` to send the request in Python.

**Comment by dfreilich** [comment]
I'm going to close this, for lack of activity. This issue may not be taken care of in the php-buildpack, but it doesn't appear to be present in the new php-web-cnb.
