### ISSUE TITLE
Enable igbinary serialization for Redis extension

### ISSUE THREAD

**Issue by Tobion** [cloudfoundry/php-buildpack#273]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?

latest

What version of the buildpack you are using?

latest

If you were attempting to accomplish a task, what was it you were attempting to do?

I'd like to use the igbinary serialiation when using Redis. But apparently the Redis extension is not configured with it. Even if you explicitly list "ext-igbinary" as dependency, it only installs igbinary but not the integration with Redis (ext-redis). It seems like you need to enable that when installing Redis `--enable-redis-igbinary`: https://github.com/phpredis/phpredis/blob/develop/INSTALL.markdown#installation-from-sources

What did you expect to happen?

phpinfo() should output

Redis Support => enabled
Redis Version => 4.0.0
Available serializers => php, igbinary

What was the actual behavior?

Redis Support => enabled
Redis Version => 4.0.0
Available serializers => php

Please confirm where necessary:
* [ ] I have included a log output
* [ ] My log includes an error message
* [x] I have included steps for reproduction

**Comment by dmikusa-pivotal** [comment]
Sorry, I thought we had it configured to do this.  It looks like we don't though, or maybe we were relying on default behavior with the redis extension that changed.

We'll need to adjust the binary-builder to compile this extension with the additional parameter to enable igbinary support.  We'll need to add a new recipe here.

https://github.com/cloudfoundry/binary-builder/blob/master/recipe/php_common_recipes.rb

**Comment by dmikusa-pivotal** [comment]
Sorry, I thought we had it configured to do this.  It looks like we don't though, or maybe we were relying on default behavior with the redis extension that changed.

I've submitted a couple PRs that should fix this.  See above.

You can use https://github.com/dmikusa-pivotal/php-buildpack.git if you'd like to test.  I have a custom build of PHP 7.2 which has the redis library with igbinary support.  I also enabled lzf compression support while I was at it.  See here for example where the extension is running.

https://php-info.cfapps.io/info.php
