### ISSUE TITLE
GD support broken?

### ISSUE THREAD

**Issue by MatthiasWinzeler** [cloudfoundry/php-buildpack#274]
> What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?
```
{
   "name": "",
   "build": "",
   "support": "https://developer.swisscom.com/contact",
   "version": 0,
   "description": "Cloud Foundry provided by Swisscom",
   "authorization_endpoint": "https://login.lyra-836.appcloud.swisscom.com",
   "token_endpoint": "https://uaa.lyra-836.appcloud.swisscom.com",
   "min_cli_version": "6.32.0",
   "min_recommended_cli_version": "latest",
   "api_version": "2.115.0",
   "app_ssh_endpoint": "ssh.lyra-836.appcloud.swisscom.com:2222",
   "app_ssh_host_key_fingerprint": "6d:d2:8c:09:64:b6:fc:2b:50:3c:a9:cb:2e:be:d4:a7",
   "app_ssh_oauth_client": "ssh-proxy",
   "doppler_logging_endpoint": "wss://doppler.lyra-836.appcloud.swisscom.com:443",
   "routing_endpoint": "https://api.lyra-836.appcloud.swisscom.com/routing",
   "user": "1cb4b6e5-2ea2-4254-9188-e368cb27b0da"
}
cf version 6.36.1+e3799ad7e.2018-04-04
```

> What version of the buildpack you are using?

Latest from github, i.e. `2018-07-31T10:57:44.89+0000 [STG/0] OUT -------> Buildpack version 4.3.58`

> If you were attempting to accomplish a task, what was it you were attempting to do?

I wanted to use the GD library. My example app contains `<?php var_dump(gd_info()); ?>`

> What did you expect to happen?

gd info output is shown

> What was the actual behavior?

`   2018-07-31T11:00:17.67+0000 [APP/PROC/WEB/0] OUT 11:00:17 httpd   | [Tue Jul 31 11:00:17.641195 2018] [proxy_fcgi:error] [pid 57:tid 140484365694720] [client 100.106.160.70:28044] AH01071: Got error 'PHP message: PHP Fatal error:  Call to undefined function gd_info() in /home/vcap/app/htdocs/index.php on line 6\n'`

Do I somehow have to activate this module?

Please confirm where necessary:
* [x] I have included a log output
* [x] My log includes an error message
* [x] I have included steps for reproduction

**Comment by dmikusa-pivotal** [comment]
Did you include the `gd` extension?  It's not included by default.  See here for instructions on how to add all the extensions you need.

https://docs.cloudfoundry.org/buildpacks/php/gsg-php-config.html#php-extensions

**Comment by MatthiasWinzeler** [comment]
@dmikusa-pivotal Thanks for pointing this out - I overlooked this part, sorry. 
Everything works fine if I add `extension=gd.so` to `.bp-config/php/php.ini.d/gd.ini`.
