### ISSUE TITLE
Display extensions version in change log?

### ISSUE THREAD

**Issue by respinoza** [cloudfoundry/php-buildpack#275]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?
CF is 275 and CLI 6.37.0+a40009753.2018-05-25

What version of the buildpack you are using?
4.3.57

If you were attempting to accomplish a task, what was it you were attempting to do?
Reading the change log to check the provided extensions with their version

What did you expect to happen?
Change log to contain the version for all the extensions

What was the actual behavior?
Only the extension name is in the changelog

Please confirm where necessary:
* [ ] I have included a log output
* [ ] My log includes an error message
* [ ] I have included steps for reproduction

**Comment by respinoza** [comment]
This will be very useful so we know which versions to target for developing. A typical case will be Doctrine upgrading to use next version of the Mongo driver but still not available in the buildpack.

The only way right now to test this is to try to install the latest and then check what was installed, I am not sure if there is another way to check this but I still think it belongs to the change log.

**Comment by dfreilich** [comment]
@respinoza Thanks for the issue, and I'm sorry it went without a response for so long! The versions are now in our releases (see, for example, [here](https://github.com/cloudfoundry/php-buildpack/releases/tag/v4.3.78). Thanks for the suggestion!
