### ISSUE TITLE
Does the buildpack include tidy?

### ISSUE THREAD

**Issue by johnwen84** [cloudfoundry/php-buildpack#279]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?
 6.29.1+d5129d6.2017-08-17

What version of the buildpack you are using?
 It's the buildpack for PHP 5.6.31
("PHP_VERSION": "{PHP_56_LATEST}")

If you were attempting to accomplish a task, what was it you were attempting to do?
I need to use extension tidy in my PHP application. I tried to add it in both .bp_config/options.json and .bp_config/php/php.ini.d/extensions.ini but my app kept saying that tidy is not available. I finally downloaded the php-5.6.31-linux-x64-e7df655a.tgz file and unzipped it, but was unable to find tidy.so in the lib/php/extensions/no-debug-non-zts-20131226 directory. I wonder if tidy is included in the buildpack at all?

What did you expect to happen?
After added this to "PHP_EXTENSIONS" in options.json ("tidy", I also tried php_tidy and a few other names) I expect tidy to be available in my app when pushed with the buildpack

What was the actual behavior?
tidy is not available. 

Please confirm where necessary:
* [ ] I have included a log output
* [ ] My log includes an error message
* [ ] I have included steps for reproduction

**Comment by dmikusa-pivotal** [comment]
You can see a list of all the extensions that are supported for a given PHP version here.

https://github.com/cloudfoundry/php-buildpack/releases

You'll also need the buildpack version, which you can find with `cf buildpacks`. I do not see that one on the list.

**Comment by dmikusa-pivotal** [comment]
Is this the extension you're referring to? It seems very old.

https://pecl.php.net/package/tidy

If there's a version somewhere that's compatible with PHP 7+, I can add it into the buildpack.

**Comment by johnwen84** [comment]
@dmikusa-pivotal yes that's the extension I was looking for. The latest stable version is 1.2 I believe. It would be great if you can add it the 5.6 too. I know it works on PHP 5.6 and my application request 5.6, never tried it on 7. Thanks!

**Comment by dmikusa-pivotal** [comment]
Oh, so it looks like this is bundled into PHP for 5+.

https://secure.php.net/manual/en/tidy.installation.php

It shouldn't be too hard to enable this. I'll see what I can do to get a PR together.

**Comment by johnwen84** [comment]
Yes it's a PHP core extension and so I was really surprised to not seeing it in the buildpack. Just curious, how do you guys select what extensions to include, or not include?

**Comment by johnwen84** [comment]
Ah I see. Yeah it would be nice if there were a switch to pull all of them in.
Thanks @dmikusa-pivotal, and please let me know when the extension is in. Can't wait to try it out!

**Comment by johnwen84** [comment]
@dmikusa-pivotal Hi, I'm wondering if you have a timeline of when this will be fixed?
 - Thanks

**Comment by dmikusa-pivotal** [comment]
I have a PR that I'm about to submit. I've got binaries built for 5.6, 7.0, 7.1 & 7.2 on cflinuxfs2 & 7.0, 7.1 and 7.2 on cflinuxfs3 (5.6 wouldn't build for what looks like an unrelated reason). I've done a little bit of testing.

Can you test more & let me know how they work for you?

Here's how you can try it out.

Set up your `manifest.yml` and point to my test buildpack: `https://github.com/dmikusa-pivotal/php-buildpack.git#develop`.

Example:

```
---
applications:
- name: php-info
  memory: 64M
  instances: 1
  path: .
  buildpacks:
  - https://github.com/dmikusa-pivotal/php-buildpack.git#develop
  route:
    - php-info.cfapps.io
```

It only packages PHP 7.2.10, so you need to specifically request that version.

Ex:

```
$ cat .bp-config/options.json
{
    "PHP_VERSION": "7.2.10"
}
```

You also need to enable the extension:

```
$ cat .bp-config/php/php.ini.d/extensions.ini
extension=tidy.so
```

phpinfo() should then report the extension as available.

<img width="964" alt="screen shot 2018-10-02 at 12 17 02 am" src="https://user-images.githubusercontent.com/4643262/46328964-86349180-c5d8-11e8-89da-05701f150e5f.png">

Let me know if you see any issues & I'll get the PR submitted sometime this week.

**Comment by dmikusa-pivotal** [comment]
>Buildpack version 4.3.39

It doesn't seem to be picking up the buildpack. The version should be much newer. It should also default to PHP 7.2 in the latest buildpack, not 5.6.

Check your `cf` cli version. You might need to upgrade. The `buildpacks:` attribute in manifest.yml is pretty new. It used to only support a single item and was named `buildpack:`. You could try making that switch, if you can't upgrade. You could also set the `-b https://github.com/dmikusa-pivotal/php-buildpack.git#develop` to the `cf push` command. This will override everything else.

**Comment by johnwen84** [comment]
Sweet! that was it. I upgraded cf cli from 6.29 to 6.39 and it worked. Tidy is there and everything looks good. Thanks @dmikusa-pivotal. Really appreciate all your help!

**Comment by dmikusa-pivotal** [comment]
OK, here are the PRs for this:

- https://github.com/cloudfoundry/binary-builder/pull/40
- https://github.com/cloudfoundry/buildpacks-ci/pull/46

Until this is merged, you can continue using the instructions above for your app.

**Comment by johnwen84** [comment]
@dmikusa-pivotal sorry to bother you again. I'm wondering what is the status of this fix. Is it pushed to the official buildpack release? I tried both the official buildpack and https://github.com/dmikusa-pivotal/php-buildpack.git#develop but Tidy seems in neither currently.

**Comment by dmikusa-pivotal** [comment]
I don't think the PR has been merged yet & I had to take down my repo for other work I'm doing. Sorry about that, I left it up as long as I could.

If you want to host your own, you could go that route until the PR is merged. You'd need to do the following:

 - Check out the PR. Use steps #1-6 [here](https://help.github.com/articles/checking-out-pull-requests-locally/#modifying-an-inactive-pull-request-locally).
 - Do [this](https://github.com/cloudfoundry/binary-builder#building-php) to build a PHP bundle that's consumable by the PHP buildpack.
 - Upload that bundle to an HTTP server or S3. It needs to be accessible from your Cloud Foundry environment.
 - Fork the PHP buildpack. Check out tag for the version you want to use. Edit the `manifest.yml` file. This tells the buildpack where to find resources. Either edit the record for an existing version of PHP to point to your build (update link & sha hash) or add a new record.
 - You can then commit your changes and push to Github or you can [build](https://github.com/cloudfoundry/php-buildpack#building-the-buildpack) your own offline buildpack and `cf create-buildpack` it to your platform.

**Comment by johnwen84** [comment]
OK I'll give it a try. Thanks!

**Comment by johnwen84** [comment]
@dmikusa-pivotal Hi, You mentioned earlier 2 PR's in 2 different repositories for this fix,
cloudfoundry/binary-builder#40
cloudfoundry/buildpacks-ci#46
Do I need both to build the PHP bundle? Or is it suffice if I just get cloudfoundry/buildpacks-ci#46?
Thanks
John

**Comment by tylerphelan** [comment]
Looks like the PR was merged https://github.com/cloudfoundry/binary-builder/pull/40

Thanks @dmikusa-pivotal and @johnwen84!
