### ISSUE TITLE
phpiredis extension broken

### ISSUE THREAD

**Issue by respinoza** [cloudfoundry/php-buildpack#281]
What version of the buildpack you are using?
v4.3.64

If you were attempting to accomplish a task, what was it you were attempting to do?
use the phpiredis extension

What did you expect to happen?
to be working as usual

What was the actual behavior?

```
missing symbols
`/home/vcap/app/php/lib/php/extensions/no-debug-non-zts-20170718/phpiredis.so: undefined symbol: redisReplyReaderCreate`
```

The phpiredis project locks the hiredis version to be `v0.13.3` but they recently released `v0.14.0` (a few years in between). The changelog from `v0.14.0` announces BC breaks and one of these are the renaming of the C functions. Now, I don't know when the author or someone else is going to fix this (I might), there is already an issue in the phpiredis repo, but for now I would say it will be a good idea to lockdown the hiredis version being used to build the extension.

Thank you

Please confirm where necessary:
* [x] I have included a log output
* [x] My log includes an error message
* [x] I have included steps for reproduction

**Comment by sclevine** [comment]
Thanks for the report! Prioritizing this now.

**Comment by sclevine** [comment]
Could you provide a sample phpiredis app that fails to push with the latest buildpack?

**Comment by respinoza** [comment]
@sclevine Here it is https://gitlab.com/respinozanature/phpiredis-app

**Comment by Ben16** [comment]
Hi @respinoza,

Thank you for the sample app! We were able to reproduce the issue and pushed a fix. You should be able to find the changes on the develop branch.

If you encounter further issues, please let us know.

**Comment by respinoza** [comment]
@sclevine I tried with the `develop` branch and worked fine, thank you for the quick fix.
