### ISSUE TITLE
Deployer Issue PHP Warning:  require(/tmp/app/vendor/autoload.php)

### ISSUE THREAD

**Issue by methodeprog** [cloudfoundry/php-buildpack#283]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?

cf version 6.34.1+bbdf814.2018-04-10, Cloud Foundry command line tool

What version of the buildpack you are using?

Buildpack version 4.3.51

If you were attempting to accomplish a task, what was it you were attempting to do?

Deployment after a build stage

What did you expect to happen?
Finish deployment an accès home page

What was the actual behavior?

 Script cache:clear returned with error code 255
   !!  PHP Warning:  require(/tmp/app/vendor/autoload.php): failed to open stream: No such file or directory in /tmp/app/bin/console on line 11
   !!  PHP Fatal error:  require(): Failed opening required '/tmp/app/vendor/autoload.php' (include_path='../lib/php:/tmp/app/lib') in /tmp/app/bin/console on line 11
   !!  
   -----> Composer command failed
   Traceback (most recent call last):
     File "/tmp/buildpacks/693e21bb4084391c7c10edffefaa6993/scripts/compile.py", line 59, in <module>
       .from_build_pack('lib/additional_commands')
     File "/tmp/buildpacks/693e21bb4084391c7c10edffefaa6993/lib/build_pack_utils/builder.py", line 209, in extensions
       process_extension(path, ctx, 'compile', process, args=[self])
     File "/tmp/buildpacks/693e21bb4084391c7c10edffefaa6993/lib/build_pack_utils/utils.py", line 69, in process_extension

Please confirm where necessary:
* [yes ] I have included a log output
* [yes ] My log includes an error message
* [no ] I have included steps for reproduction

**Comment by dmikusa-pivotal** [comment]
Can you a.) try with the latest buildpack, v4.3.64 at time of writing, and b.) reply with the full output of staging, everything including your `cf push` command all the way through the end of the output from `cf push`.

If you have a simple test app you can provide to trigger the error, that's even better. Thanks!

**Comment by lbayerl** [comment]
Has this been working before or is it your first try to deploy a Symfony application on CloudFoundry?
Which Symfony env do you use?
How does your composer.json look like?

**Comment by methodeprog** [comment]
Hi Ibayerl !
The build is right now ! Great !
But with a little error here.
////////////// Display message
Oops! An Error Occurred
The server returned a "500 Internal Server Error".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.
//////////
1/ Ive set all my environment variables
2/ set app on prod
///////////// Display logs on Kibana
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx - [2018-12-05T10:01:52.509+0000] "GET / HTTP/1.1" 500 0 918 "https://cloud.ibm.com/apps/5267c15d-4dec-47ca-b7b7-2c730b4bb3ca?paneId=overview&ace_config=%7B%22region%22%3A%22eu-gb%22%2C%22crn%22%3A%22crn%3Av1%3Abluemix%3Apublic%3Abluemix%3Aeu-gb%3As%2F412af461-a421-4409-8d04-c7de0ad31fa4%3A%3Acf-application%3A5267c15d-4dec-47ca-b7b7-2c730b4bb3ca%22%2C%22resource_id%22%3A%225267c15d-4dec-47ca-b7b7-2c730b4bb3ca%22%2C%22orgGuid%22%3A%22432c04fd-d13d-4f63-87a0-63920069f312%22%2C%22spaceGuid%22%3A%22412af461-a421-4409-8d04-c7de0ad31fa4%22%2C%22redirect%22%3A%22https%3A%2F%2Fcloud.ibm.com%2Fresources%22%2C%22bluemixUIVersion%22%3A%22v6%22%7D&env_id=ibm:yp:eu-gb" "Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36" "10.164.95.244:13776" "158.175.85.108:61184" x_forwarded_for:"160.154.128.51, 10.164.95.244" x_forwarded_proto:"https" vcap_request_id:"46e13380-d51b-4bbd-6a6e-5ab68ba1d407" response_time:1.02413138 app_id:"5267c15d-4dec-47ca-b7b7-2c730b4bb3ca" app_index:"0" x_global_transaction_id:"434533965" true_client_ip:"-" x_b3_traceid:"ca29fd9799b8123a" x_b3_spanid:"ca29fd9799b8123a" x_b3_parentspanid:"-"
If this can tell something, i'm trying to  fix ! but found nothing at the moment !

Best regards

**Comment by methodeprog** [comment]
I use this action 
**HOME=$HOME/app source app/.profile.d/bp_env_vars.sh #this will make your env variables available**
But get this:
**bash: app/.profile.d/bp_env_vars.sh: No such file or directory**

**Comment by methodeprog** [comment]
It working noooooooooow ! Greaaaaat ! 
We love this plateform and its awesome please help us !
