### ISSUE TITLE
Error staging application - An App was not detected by buildpack

### ISSUE THREAD

**Issue by jitheshktv** [cloudfoundry/php-buildpack#285]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?
> PCF 1.12.x
> CLI: 6.34.1

What version of the buildpack you are using?
> 4.3.66

If you were attempting to accomplish a task, what was it you were attempting to do?
> Deploy a php application on PCF.

What did you expect to happen?
> Iterating through the buildpacks based on the position, the offline php buildpack installed on the PCF foundation should detect the php application, and stage/deploy it.

What was the actual behavior?
> Staging failed with the error: An app was not successfully detected by any available buildpack

Completed log below.
bash-4.1$ pwd
/tmp
bash-4.1$ mkdir my-php-app
bash-4.1$ cd my-php-app/
bash-4.1$ cat << EOF > index.php
> <?php
>   phpinfo();
> ?>
> EOF
bash-4.1$

bash-4.1$ cf push my-php-app -m 128M
Pushing app my-php-app to org TEST / space development as admin...
Getting app info...
Creating app with these attributes...
+ name:       my-php-app
  path:       /tmp/my-php-app
+ memory:     128M
  routes:
+   my-php-app.cfapps-dev001.xxx.xxx.xxx

Creating app my-php-app...
Mapping routes...
Comparing local files to remote cache...
Packaging files to upload...
Uploading files...
 160 B / 160 B [==================================================================================================================================] 100.00% 1s

Waiting for API to complete processing files...

Staging app and tracing logs...
   Downloading python-test-buildpack...
   Downloading staticfile_buildpack...
   Downloading java_buildpack_offline...
   Downloading ruby_buildpack...
   Downloading nodejs_buildpack...
   Downloaded nodejs_buildpack
   Downloading go_buildpack...
   Downloaded java_buildpack_offline
   Downloading python_buildpack...
   Downloaded ruby_buildpack
   Downloading php_buildpack...
   Downloaded python-test-buildpack
   Downloaded staticfile_buildpack
   Downloading binary_buildpack...
   Downloading dotnet-core-buildpack...
   Downloaded go_buildpack
   Downloading dotnet_core_buildpack...
   Downloaded dotnet-core-buildpack
   Downloaded python_buildpack
   Downloaded php_buildpack
   Downloaded dotnet_core_buildpack
   Downloaded binary_buildpack
   Creating container
   Successfully created container
   Downloading app package...
   Downloaded app package (160B)
   Traceback (most recent call last):
     File "/tmp/buildpacks/1d885f3be616a6707cd3cd0b9f5ec2f0/scripts/detect.py", line 20, in <module>
       (Builder()
     File "/tmp/buildpacks/1d885f3be616a6707cd3cd0b9f5ec2f0/lib/build_pack_utils/builder.py", line 946, in configure
       self._ctx = CloudFoundryUtil.initialize()
     File "/tmp/buildpacks/1d885f3be616a6707cd3cd0b9f5ec2f0/lib/build_pack_utils/cloudfoundry.py", line 64, in initialize
       ctx = CloudFoundryUtil.update_default_version(dependency, manifest_file, ctx)
     File "/tmp/buildpacks/1d885f3be616a6707cd3cd0b9f5ec2f0/lib/build_pack_utils/cloudfoundry.py", line 75, in update_default_version
       exit_code, output = compile_exts.default_version_for(manifest_file, dependency)
     File "/tmp/buildpacks/1d885f3be616a6707cd3cd0b9f5ec2f0/lib/build_pack_utils/compile_extensions.py", line 19, in default_version_for
       exit_code, default_version = self.call_compile_extensions_script('default_version_for', manifest_file_path, dependency)
     File "/tmp/buildpacks/1d885f3be616a6707cd3cd0b9f5ec2f0/lib/build_pack_utils/compile_extensions.py", line 9, in call_compile_extensions_script
       process = subprocess.Popen([os.path.join(self._buildpack_dir, 'compile-extensions', 'bin', script)] + list(args), stdout=subprocess.PIPE)
     File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
       errread, errwrite)
     File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
       raise child_exception
   OSError: [Errno 2] No such file or directory
   None of the buildpacks detected a compatible application
   Exit status 222
   Stopping instance d3339df5-abc5-4526-9251-b66a01fe9e1b
   Destroying container
   Successfully destroyed container
Error staging application: An app was not successfully detected by any available buildpack

TIP: Use 'cf buildpacks' to see a list of supported buildpacks.
FAILED
bash-4.1$

Please confirm where necessary:
* [x] I have included a log output
* [x] My log includes an error message
* [x] I have included steps for reproduction

**Comment by dmikusa-pivotal** [comment]
```
File "/tmp/buildpacks/1d885f3be616a6707cd3cd0b9f5ec2f0/lib/build_pack_utils/compile_extensions.py", line 9, in call_compile_extensions_script
process = subprocess.Popen([os.path.join(self._buildpack_dir, 'compile-extensions', 'bin', script)] + list(args), stdout=subprocess.PIPE)
File "/usr/lib/python2.7/subprocess.py", line 710, in init
errread, errwrite)
File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
raise child_exception
OSError: [Errno 2] No such file or directory
```

This is trying to call out to a compile-extensions script. These scripts are pulled in via a submodule. It seems like they are missing in your buildpack, which could possibly be due to not pulling in that submodule before building the buildpack.

Taking a step back, where did you get your version of the buildpack? If you're building it, make sure you run step #1 here.

https://github.com/cloudfoundry/php-buildpack#building-the-buildpack

**Comment by jitheshktv** [comment]
@dmikusa-pivotal  you are right!. the submodule was missing. It's working now. Thank you.
