### ISSUE TITLE
NOTICE: Removal of PHP 5.x and 7.0.x after 2019-02-10

### ISSUE THREAD

**Issue by shanks3012** [cloudfoundry/php-buildpack#286]
The first release of the PHP buildpack after February 10, 2019 will no longer include any versions of PHP 5.x or 7.0.x. These PHP versions are no longer supported upstream [1]. Please migrate your PHP apps to supported versions of PHP before that time.

[1] http://php.net/supported-versions.php

**Comment by kardolus** [comment]
Thanks for pointing this out. We will prioritize it.
