### ISSUE TITLE
not getting PHP_AUTH_USER and PHP_AUTH_PW

### ISSUE THREAD

**Issue by sgdmediagroup** [cloudfoundry/php-buildpack#287]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?
PCF 1.9 & PCF 1.7

What version of the buildpack you are using?
master

If you were attempting to accomplish a task, what was it you were attempting to do?

need to get PHP_AUTH_USER and PHP_AUTH_PW

What did you expect to happen?

rceive PHP_AUTH_USER and PHP_AUTH_PW information in $_SERVER, but the keys aren't there.

What was the actual behavior?

Not getting PHP_AUTH_USER and PHP_AUTH_PW

Please confirm where necessary:
* [ ] I have included a log output
* [ ] My log includes an error message
* [ ] I have included steps for reproduction

**Comment by sgdmediagroup** [comment]
From this issue https://github.com/cloudfoundry/php-buildpack/issues/190 I tried to set in my `.htaccess` `CGIPassAuth On`, but still not getting the variables.

**Comment by dmikusa-pivotal** [comment]
What are `PHP_AUTH_USER and PHP_AUTH_PW`? I don't recognize those as something the buildpack is providing. Are they headers your client is sending? or something like that?
