### ISSUE TITLE
use go module to build the cached buildpack

### ISSUE THREAD

**Issue by aad** [cloudfoundry/php-buildpack#290]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?
N/A

What version of the buildpack you are using?
v4.3.67 and v4.3.70

If you were attempting to accomplish a task, what was it you were attempting to do?
buildpack-packager build -stack "${buildpack_stack}" --cached=true

buildpack_stack is either cflinuxfs2 or cflinuxfs3

What did you expect to happen?
build can complete successfully

What was the actual behavior?
error while creating zipfile: No matching default dependency `newrelic` for stack `cflinuxfs2`

probably the reason is 8.1.0.209 doesn't conform to the semver?

Please confirm where necessary:
* [x] I have included a log output
* [x] My log includes an error message
* [x] I have included steps for reproduction

**Comment by Zanadar** [comment]
This buildpack is slightly differant from all the others (because reasons). You need to follow directions in the readme to build: https://github.com/cloudfoundry/php-buildpack#building-the-buildpack
