### ISSUE TITLE
missing extension

### ISSUE THREAD

**Issue by segunmicheal27** [cloudfoundry/php-buildpack#296]
I download php 7.2 with buildpack_url but some extension are mission like mbstring and many more, i will love have a great step by step good explanation how to add missing extension to php extension

**Comment by lbayerl** [comment]
Did you read documentation?

**Comment by segunmicheal27** [comment]
Yeah over and over again
i found out that buildpack_URL: php_buildpack will only give us version of 7.0 by default 
and i have created php.ini files to indicate all modules settings:
which made me to have this in my php.ini file:
`extension_dir=/home/vcap/app/php/lib/php/extensions/no-debug-non-zts-20131226
extension=pdo.so
extension=pdo_mysql.so
extension=pdo_pgsql.so
extension=pdo_sqlite.so
extension=gd.so
;extension=mbstring.so
zend_extension=mbstring.so
extension=zlib.so
extension=curl.so
;extension=mcrypt.so
zend_extension=mcrypt.so
extension=zip.so
extension=exif.so
extension=gettext.so
extension=mysqli.so
extension=openssl.so
extension=tokenizer.so
extension=soap.so
extension=sockets.so
extension=fileinfo.so
extension=gmp.so`

**Comment by segunmicheal27** [comment]
extension_dir=/home/vcap/app/php/lib/php/extensions/no-debug-non-zts-20131226
extension=pdo.so
extension=pdo_mysql.so
extension=pdo_pgsql.so
extension=pdo_sqlite.so
extension=gd.so
;extension=mbstring.so
zend_extension=mbstring.so
extension=zlib.so
extension=curl.so
;extension=mcrypt.so
zend_extension=mcrypt.so
extension=zip.so
extension=exif.so
extension=gettext.so
extension=mysqli.so
extension=openssl.so
extension=tokenizer.so
extension=soap.so
extension=sockets.so
extension=fileinfo.so
extension=gmp.so

**Comment by dmikusa-pivotal** [comment]
>I download php 7.2 with buildpack_url 

It's not clear where you're downloading the buildpack from, nor is it clear how you're using it. Do you have `cf push -b` set? or are you using `cf create-buildpack` to uploading a buildpack? Please give more detail what you're doing.

>extension_dir

Do not put `extension_dir` in your INI snippet. 

>zend_extension=mbstring.so
>zend_extension=mcrypt.so

These are not `zend_extension`'s. Load them with `extension=`.

>extension=fileinfo.so

I believe fileinfo and tokenizer and a few other extensions are built directly into the PHP binary, thus they don't need an `extension=`. Please refer to the output of `phpinfo()` to see exactly what's built-in.

If you make the changes above and still need help:

a.) Include the full output of `phpinfo()`.
b.) `cf ssh` into your app and include the output of `/home/vcap/app/php/lib/php/extensions/no-debug-zts-20131226`.

Thanks

**Comment by lbayerl** [comment]
@dmikusa-pivotal I highly respect your patience!

**Comment by segunmicheal27** [comment]
I later solve my issue by enabling debugging mode to know what is going on, i found that its on support dependency destroying the app staging

I think video tutorial for get started on dashboard and all documentation will be of great help
Opinion notice
1. Difficulties in custom build of php_buildpack
2. Server too fragile or flexible any error found on the file server refuse to start, then user we have to recreate the resources again and delete the old one
3. Out-dated Linux OS, there is no proper guide to install or updated OS on the stack. php 7.3 can only be found on the latest os itself

Thank you

**Comment by Zanadar** [comment]
Closing. Please reopen if @dmikusa-pivotal didn't adequately answer your question and document our path forward.
