### ISSUE TITLE
GeoIP/GeoLite DB Support

### ISSUE THREAD

**Issue by dmikusa-pivotal** [cloudfoundry/php-buildpack#298]
What version of the buildpack you are using? 
v4.3.72

The GeoLite legacy databases from MaxMind have been deprecated for a long time. On Jan 1, 2019, they were finally discontinued and are no longer supported.

The PHP buildpack has support to help users automatically download the legacy DBs. This is now broken since they no longer exist.

https://github.com/cloudfoundry/php-buildpack/blob/master/extensions/geoip/extension.py

We need to evaluate if it's necessary to update the buildpacks support for GeoLite2 databases & if so, update the buildpack with this support.

If you are using the PHP buildpack with GeoIP/Maxmind, please add comments here and upvote this issue. Thanks!

**Comment by dfreilich** [comment]
@dmikusa-pivotal Given that there were no comments, should I close the issue? Do we have to take things out of php-buildpack as a result?

**Comment by dmikusa-pivotal** [comment]
Given there's been no feedback, I'd say this is something that we defer to the PHP CNBs.

**Comment by dfreilich** [comment]
In that case, I'll close it, and if someone needs GeoIP/GeoLite DB Support in the CNBs, they'll file an issue.
