### ISSUE TITLE
unknow issue

### ISSUE THREAD

**Issue by segunmicheal27** [cloudfoundry/php-buildpack#301]
The deployment was working at a time suddenly i just see this error 
` 
[RuntimeException]                                                                                         
     Could not scan for classes inside "htdocs/database/seeds" which does not appear to be a file nor a folder 
`
Then application stopped

**Comment by dmikusa-pivotal** [comment]
Can you provide the full output of running `cf push`, including the full command you're running & an manifest.yml file, if you are using one? Thanks.

**Comment by segunmicheal27** [comment]
here is my manifest:
`----
applications:
- name: Metier Hub
  memory: 128MB
  buildpack: https://github.com/cloudfoundry/php-buildpack.git#v4.3.72
  services:
    - Compose for MySQL-7c
  env:
    CF_STAGING_TIMEOUT: 45
    CF_STARTUP_TIMEOUT: 5
    BP_DEBUG: true`

Here is the console error:
`[RuntimeException]                                                                                  
     Could not scan for classes inside "htdocs/database/seeds" which does not appear to be a file nor a folder `

**Comment by segunmicheal27** [comment]
Trying to re-deploy laravel project

**Comment by dmikusa-pivotal** [comment]
Is that all you're seeing as output from running `cf push`? 

I really need to see the entire output from when you run `cf push` all the way through to where it fails. Just copy and paste everything here. It will provide some much-needed context as to where you're seeing this problem. Thanks!

**Comment by dmikusa-pivotal** [comment]
Or link me to a demo project that can reproduce the issue.

**Comment by Zanadar** [comment]
Closing. PLease reopen if you can provide a way to repro.
