### ISSUE TITLE
Outdated default php.ini

### ISSUE THREAD

**Issue by Tobion** [cloudfoundry/php-buildpack#303]
The php.ini that comes with the buildpack is very outdated and sets configs which are very unexpected.

If you compare the ini from PHP https://github.com/php/php-src/blob/PHP-7.3/php.ini-production to the one shipped with the buildpack https://github.com/cloudfoundry/php-buildpack/blob/master/defaults/config/php/7.3.x/php.ini you see that the buildpack still uses outdated values for some configs. For example it uses `serialize_precision = 17` instead of the new default `serialize_precision = -1`. It also sets configs that do not exist anymore like `session.hash_function = 0`.

Please update the buildpack ini according to the new recommendations.

**Comment by kardolus** [comment]
Hi @Tobion, thanks for bringing this to our attention. 

We will go over this during our PM on Monday and prioritize the issue accordingly. 

Cheers! :)

**Comment by Tobion** [comment]
@kardolus Any update here? Using the production defaults like suggested in #265 seems fine to me.

**Comment by dfreilich** [comment]
@Tobion Thanks for checking back in! No updates yet, but we may decide to defer this feature for our new [php-web-cnb](https://github.com/cloudfoundry/php-web-cnb) instead of doing it here. 

@dmikusa-pivotal Do you have any thoughts?

**Comment by dmikusa-pivotal** [comment]
@Tobion - Do you have any examples of how this is impacting your apps?

**Comment by Tobion** [comment]
The old serialize_precision results in float values to not be rounded correctly in json apis. See https://wiki.php.net/rfc/precise_float_value

**Comment by dmikusa-pivotal** [comment]
@dfreilich - Given the use case, I feel like we need to go ahead with this. It should be a small amount of work and will resolve two issues, this one and #265.

**Comment by ForestEckhardt** [comment]
@dmikusa-pivotal and I have updated the PHP buildpack to use the latest version of php.ini from PHP.net (for 7.1, 7.2 and 7.3). This change is in the develop branch if you're interested in testing it and should get picked up in the next release.

**Comment by dfreilich** [comment]
@Tobion Thanks for suggesting it! As mentioned above, it will be released in the next PHP Buildpack (`v4.3.80`), and it is already in our new [php-web-cnb](https://github.com/cloudfoundry/php-web-cnb/commit/fdbd12d0c356c8a73202ffa890820c1c00ab5390).
