### ISSUE TITLE
curl not available in cli

### ISSUE THREAD

**Issue by crypticro** [cloudfoundry/php-buildpack#305]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?

```
"min_cli_version": "6.42.0",
"api_version": "2.128.0",
"osbapi_version": "2.14"
```

What version of the buildpack you are using?

-------> Buildpack version 4.3.76

If you were attempting to accomplish a task, what was it you were attempting to do?

Running a CLI task that uses the PHP CURL library.
I specified a Command in options.json to run a Preprocess PHP CLI Command using the ADDITIONAL_PREPROCESS_CMDS attribute.

What did you expect to happen?

To run the task with CURL. 

What was the actual behavior?

```
/app/php/bin/php curl.php


Fatal error: Uncaught Error: Call to undefined function curl_init() in /home/vcap/app/curl.php:3
Stack trace:
#0 {main}
  thrown in /home/vcap/app/curl.php on line 3
```

The curl modules is available when accessing via web server (nginx/apache) but not in CLI. I have enabled the cli module in options.json and added the curl.so library in the php ini file.

```
vcap@1037f746-835c-455b-7524-cf35:~/app$ /app/php/bin/php -m
[PHP Modules]
bcmath
calendar
Core
ctype
date
dom
filter
hash
iconv
intl
json
libxml
mysqlnd
pcre
Phar
posix
Reflection
session
SimpleXML
SPL
sqlite3
standard
tokenizer
xml
xmlreader
xmlwriter
```

Please confirm where necessary:
* [x ] I have included a log output
* [x ] My log includes an error message
* [x ] I have included steps for reproduction

**Comment by dmikusa-pivotal** [comment]
It sounds like you're doing the same thing as in this issue: https://github.com/cloudfoundry/php-buildpack/issues/239#issuecomment-356956582

**Comment by crypticro** [comment]
@dmikusa-pivotal 

Yes it does. But this doesn't solve my problem. I moved the execution of those commands to the .profile file now and it's working now. But I don't quite understand the use of ADDITIONAL_PREPROCESS_CMDS if not all modules are available at that stage.

**Comment by dmikusa-pivotal** [comment]
`ADDITIONAL_PREPROCESS_CMDS` is the old way of doing things. I don't think it's ever been deprecated, or anything like that, but in pretty much all cases, if you want to run something before the app starts up (i.e. in the runtime container), you should use a `.profile` script.

Support for `.profile` comes from the platform, so it's not buildpack specific.
