### ISSUE TITLE
Possible issues with buildpack with Mediawiki

### ISSUE THREAD

**Issue by dgarci10** [cloudfoundry/php-buildpack#312]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?

{
   "name": "Bluemix",
   "build": "270030",
   "support": "http://ibm.com",
   "version": 0,
   "description": "IBM Bluemix",
   "authorization_endpoint": "https://login.w3ibm.bluemix.net/UAALoginServerWAR",
   "token_endpoint": "http://uaa.w3ibm.bluemix.net",
   "min_cli_version": null,
   "min_recommended_cli_version": null,
   "api_version": "2.92.0",
   "app_ssh_endpoint": "ssh.w3ibm.bluemix.net:2222",
   "app_ssh_host_key_fingerprint": "b6:98:0b:3e:33:1e:c1:51:1b:3f:06:6e:3f:da:6f:d9",
   "app_ssh_oauth_client": "ssh-proxy",
   "doppler_logging_endpoint": "wss://doppler.w3ibm.bluemix.net:443"
}

cf version 6.41.0+dd4c76cdd.2018-11-28

What version of the buildpack you are using?
4.3.78
(https://github.com/cloudfoundry/php-buildpack.git)

If you were attempting to accomplish a task, what was it you were attempting to do?

I was attempting to install Mediawiki 1.32.2 by following their basic installation guide on their page, however, I run into "MediaWiki now also has some external dependencies that need to be installed via composer or from a separate git repo. Please see mediawiki.org for help on installing the required components."

Upon several googling I found a guide that told me to remove a specific file ( I forgot what it was and can't find the link) and it allowed me to get past this issue but then I had the issues that I was missing the extensions mbstring, & fileinfo. 

To see if this was just me failing to install Mediawiki, I tried to install phpMyAdmin, and I run into the issues that mysqli extension is also missing. 

However, I have installed both MediaWiki and phpMyAdmin locally without any issues...so I am wondering if it could be the build pack, as I am trying to replicate an app someone had previously created. They use the same Mediawiki software but under build pack on cloud foundry it just says "no runtime" instead of "PHP_BUILDPACK"

I have tried following comments from this link but no luck:
https://github.com/cloudfoundry/php-buildpack/issues/214

What did you expect to happen?

I expected to run into the media wiki install page. I did this locally to confirm I was doing the right steps and and I got successfully to the installation page.

What was the actual behavior?

I get the error that I must use composer to install external dependencies but I did...

Please confirm where necessary:
* [ ] I have included a log output
* [ ] My log includes an error message
* [x] I have included steps for reproduction

**Comment by dmikusa-pivotal** [comment]
There may be multiple things going on here. It's hard to tell though as there's not a lot of detailed info here.

If you're missing extensions, then you likely just need to add an ini snippet and tell PHP to load them. All the ones you mentioned are included with the buildpack but not turned on by default.

https://docs.cloudfoundry.org/buildpacks/php/gsg-php-config.html#php-extensions

As far as the other issues, try what's on #214 again and try to be more specific about documenting what you're doing. Include error messages & logs as well as the specific configuration that you're using.

Hope that helps!

**Comment by dgarci10** [comment]
I have followed the above link before, and have typed the following:

```
extension=mysqli.so
extension=mbstring.so
extension=fileinfo.so
```

however, when running it on cloud foundry, it still says these are missing. However, I ran this locally today and do not get these issues. I am able to get to the Mediawiki page fine.


I am new to this so I am not sure how more specific I should be, what type of logs should I post?

**Comment by dmikusa-pivotal** [comment]
>when running it on cloud foundry, it still says these are missing.

Where are you seeing that they are missing?

**Comment by dgarci10** [comment]
When going to the app by clicking on the server link, instead of landing on the MediaWiki installation page, I get 

"MediaWiki 1.32 internal error

Installing some PHP extensions is required.

Required components

You are missing a required extension to PHP that MediaWiki requires to run. Please install:

mbstring (more information)
fileinfo (more information)"


However, I did add the above files to make sure they are on.

**Comment by dmikusa-pivotal** [comment]
Sorry, not sure what's happening here. I went through the steps I listed on #214 and they worked just fine for me. Here's a directory listing to give a little more context. The contents of these files is exactly what I put on #214. Hope that helps!

```
$ ls -la
total 16
drwxr-xr-x   6 dmikusa  staff   192 Jun 18 21:47 .
drwxr-xr-x+ 17 dmikusa  staff   544 Jun 18 21:43 ..
drwxr-xr-x   4 dmikusa  staff   128 Jun 18 21:44 .bp-config
-rw-r--r--   1 dmikusa  staff    14 Jun 18 21:43 .cfignore
drwxr-xr-x@ 37 dmikusa  staff  1184 Jun 18 21:41 htdocs
-rw-r--r--   1 dmikusa  staff   109 Jun 18 21:47 manifest.yml
```

```
$ ls -laR .bp-config/
total 8
drwxr-xr-x  4 dmikusa  staff  128 Jun 18 21:44 .
drwxr-xr-x  6 dmikusa  staff  192 Jun 18 21:47 ..
-rw-r--r--  1 dmikusa  staff   59 Jun 18 21:44 options.json
drwxr-xr-x  3 dmikusa  staff   96 Jun 18 21:44 php

.bp-config//php:
total 0
drwxr-xr-x  3 dmikusa  staff   96 Jun 18 21:44 .
drwxr-xr-x  4 dmikusa  staff  128 Jun 18 21:44 ..
drwxr-xr-x  3 dmikusa  staff   96 Jun 18 21:46 php.ini.d

.bp-config//php/php.ini.d:
total 8
drwxr-xr-x  3 dmikusa  staff  96 Jun 18 21:46 .
drwxr-xr-x  3 dmikusa  staff  96 Jun 18 21:44 ..
-rw-r--r--  1 dmikusa  staff  38 Jun 18 21:46 wiki.ini
```

**Comment by dgarci10** [comment]
Thank you for your help. I followed your instructions but still am failing to reach the installation page. I now get the original error of missing dependencies via composer.

I will list out the steps I did.


1) Downloaded MediaWiki 1.32.2.tar.gz file from https://www.mediawiki.org/wiki/Download

2) Made a new folder on my Desktop say Wiki, un-tar the downloaded tar.gz folder and put it in the Wiki folder. 
i.e ~/Desktop/Wiki/media/ has all the contents of MediaWiki

3) Made .bp-config/options.json, .bp-config/php.ini.d/wiki.ini, and .cfignore files as shown in #214, and put them in the Wiki folder (~/Desktop/Wiki). I have also done another run where I put these files within the same media(~/Desktop/Wiki/media) folder.

4) Create the manifest.yml file as shown:

`---
applications:
- name: wikiApp
  memory: 256M
  instances: 1
  path: .
  buildpack: https://github.com/cloudfoundry/php-buildpack.git
  services:
  - sql
`

I had to change the buildpack because otherwise it uses PHP 5.6 which is incompatible with Mediawiki 1.32.2

running ls -la

`drwxr-xr-x   7 Dylan.Garcia@ibm.com  staff   224 Jun 19 10:29 .
drwx------+ 75 Dylan.Garcia@ibm.com  staff  2400 Jun 19 10:34 ..
-rw-r--r--@  1 Dylan.Garcia@ibm.com  staff  8196 Jun 19 10:41 .DS_Store
-rw-r--r--@  1 Dylan.Garcia@ibm.com  staff    59 Jun 19 09:36 .bp-config:options.json
-rw-r--r--@  1 Dylan.Garcia@ibm.com  staff    38 Jun 19 09:36 .bp-config:php:php.ini.d:wiki.ini
-rw-r--r--@  1 Dylan.Garcia@ibm.com  staff     7 Jun 19 09:35 .cfignore
drwxr-xr-x  40 Dylan.Garcia@ibm.com  staff  1280 Jun 19 10:41 media`

It seems that you have other files that I do not have

5) I run `cf push` and get no errors.

6) go to the server link, and get the error message `MediaWiki 1.32 internal error

Installing some external dependencies (e.g. via composer) is required.

External dependencies

MediaWiki now also has some external dependencies that need to be installed via composer or from a separate git repo. Please see mediawiki.org for help on installing the required components.`

However, the .tar.gz file from MediaWiki already includes these dependencies.

**Comment by dmikusa-pivotal** [comment]
>i.e ~/Desktop/Wiki/media/ has all the contents of MediaWiki

You need to follow *exactly*. This shouldn't be "media", it needs to be called "htdocs" or you need to set `WEBDIR` in `options.json` to tell the buildpack where your public files are located.

I suspect this is the main cause of your problems.

>I had to change the buildpack because otherwise it uses PHP 5.6 which is incompatible with Mediawiki 1.32.2

I don't know what buildpack is used on IBM's platform, but the default hasn't been 5.6 for a *long* time. If you need to set the buildpack do what's below, do *not* point to master which is unstable.

https://github.com/cloudfoundry/php-buildpack.git#v4.3.78  (or whatever stable version you want).

>-rw-r--r--@ 1 Dylan.Garcia@ibm.com staff 59 Jun 19 09:36 .bp-config:options.json
>-rw-r--r--@ 1. Dylan.Garcia@ibm.com staff 38 Jun 19 09:36 .bp-config:php:php.ini.d:wiki.ini

Not sure if this is a typo with the `:`'s, but `.bp-config` should be a folder. So should `php/php.ini.d/`. Double check that.

**Comment by dgarci10** [comment]
THANK YOU!

I was able to fix the directory and be able to successfully get to the install page. Thanks so much for your patience!
