### ISSUE TITLE
Installing Certificates into the Trust Store

### ISSUE THREAD

**Issue by jchallenger** [cloudfoundry/php-buildpack#314]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?
```
{
   "name": "IBM Cloud",
   "build": "6.8.0",
   "support": "http://ibm.biz/bluemix-supportinfo",
   "version": 0,
   "description": "IBM Bluemix",
   "authorization_endpoint": "https://iam.cloud.ibm.com/cloudfoundry/login/us-south",
   "token_endpoint": "https://uaa.us-south.cf.cloud.ibm.com",
   "min_cli_version": null,
   "min_recommended_cli_version": null,
   "app_ssh_endpoint": "ssh.us-south.cf.cloud.ibm.com:2222",
   "app_ssh_host_key_fingerprint": "c7:1f:89:2a:62:3b:78:a9:08:c9:33:81:fb:39:26:da",
   "app_ssh_oauth_client": "ssh-proxy",
   "doppler_logging_endpoint": "wss://doppler.us-south.cf.cloud.ibm.com:443",
   "api_version": "2.128.0",
   "osbapi_version": "2.14",
   "user": "6e747cdf-c2de-475f-af29-820b731a1cee"
}
cf version 6.33.0+a345ea34d.2017-11-20
```

What version of the buildpack you are using?
latest (4.3.78)

If you were attempting to accomplish a task, what was it you were attempting to do?
I am looking for a way to install trusted certificates into the cflinuxfs3 truststore via the Buildpack. Services (VCAP_SERVICES) can use self-signed certificates that our applications must add to the trust store (root access required).

What did you expect to happen?
I was hoping to be able to pull a certificate from VCAP_SERVICES and add it to the trust store.

What was the actual behavior?
I currently have no clearly documented way to add new certificates to the trust store.
This means that I am unable to use the Databases for Redis service.

**Comment by dmikusa-pivotal** [comment]
You just can't add certs to the main truststore. It's under `/etc/ssl/certs` which is only writable by root and you cannot get root access in your application container.

You would need to modify PHP and have an additional truststore that it uses to make decisions about which certs to trust. Kind of like here -> https://stackoverflow.com/a/41772652

**Comment by jchallenger** [comment]
Thanks, I'll close this for now and see if loading a cert this way helps. I might take a swing at putting an extension together to read the VCAP values, save the cert to a file and modify PHP ini instead of modifying my app directly.
