### ISSUE TITLE
IMPORTANT NOTICE: End of support for nginx versions 1.15.x after 2019-08-10

### ISSUE THREAD

**Issue by shanks3012** [cloudfoundry/php-buildpack#316]
The first release of the PHP buildpack after August 10, 2019 will no longer include nginx versions 1.15.x. These nginx versions are no longer supported upstream. Please migrate your PHP apps to supported versions of nginx before that time.

In addition, the default version of nginx will be bumped to 1.17.x at this time.

Note: Unless you are manually specifying a version of nginx for the buildpack to use, or you have customized your PHP buildpack, no action is required.

**Comment by RageZBla** [comment]
@shanks3012 is it normal the notice appears even if I have not specified nginx version?

**Comment by shanks3012** [comment]
@RageZBla I apologize for not seeing this response. We put these notices out as an informative precaution to give all users of the PHP buildpack a heads up about the removal of the dependency. Even though you don't specify a version of nginx, this notice will still be present to all. Let me know if you have further questions, but going to close this out!
