### ISSUE TITLE
Update new relic agent version to 9.1.0.246 for PHP 7.3 support

### ISSUE THREAD

**Issue by ocean90** [cloudfoundry/php-buildpack#320]
The current version of the agent based on http://download.newrelic.com/php_agent/release/ is 9.1.0.246.

It provides the following extensions:

```
newrelic-20090626-zts.so
newrelic-20090626.so
newrelic-20100525-zts.so
newrelic-20100525.so
newrelic-20121212-zts.so
newrelic-20121212.so
newrelic-20131226-zts.so
newrelic-20131226.so
newrelic-20151012-zts.so
newrelic-20151012.so
newrelic-20160303-zts.so
newrelic-20160303.so
newrelic-20170718-zts.so
newrelic-20170718.so
newrelic-20180731-zts.so
newrelic-20180731.so
```

Compared to 8.1.0.209, `newrelic-20180731.so` and `newrelic-20180731-zts.so` are new and required for PHP 7.3 support.

https://github.com/cloudfoundry/php-buildpack/blob/c1228dbc88137e8bdf309e3940c7f454e3cc5d94/manifest.yml#L22-L23
https://github.com/cloudfoundry/php-buildpack/blob/c1228dbc88137e8bdf309e3940c7f454e3cc5d94/manifest.yml#L113-L119

**Comment by dfreilich** [comment]
Fixed in #321 (in commit 58dcaf8). Thanks for pointing it out!
