### ISSUE TITLE
Error on deploy: If you at one point specified a buildpack that's at git URL, please make sure you're pointed at a version that supports this stack.

### ISSUE THREAD

**Issue by matosmts** [cloudfoundry/php-buildpack#324]
what is the new stack supprted by the newst buildpack version.

What version of the buildpack you are using?
The newest through the github link.

If you were attempting to accomplish a task, what was it you were attempting to do?
Deploy my application on prod env.

What did you expect to happen?
deploy works succesfully

What was the actual behavior?
 It looks like you're deploying on a stack (currently set to *cflinuxfs2*) that's not supported by this buildpack.
   That could be because you're using a recent buildpack release on a deprecated stack.
   If you at one point specified a buildpack that's at git URL, please make sure you're pointed at a version that supports this stack.
   Failed to compile droplet: Failed to run finalize script: exit status 44

Please confirm where necessary:
* [x] I have included a log output
* [ ] My log includes an error message
* [ ] I have included steps for reproduction

**Comment by dmikusa-pivotal** [comment]
>What version of the buildpack you are using?
>The newest through the github link.

You don't want to do that. This is one of the reasons why. Master evolves at its own pace. It's not stable. Things change in it. If you really want the most recent stuff you can use it, but you should probably look at using a tagged release instead.

For example, this would get you the latest stable release as of writing this:

`cf push -b https://github.com/cloudfoundry/php-buildpack#v4.4.0`

You can pick any tagged release though. See here for a list of releases and what they support. Version v4.3.82 was the last to support cflinuxfs2.

https://buildpacks.cloudfoundry.org/#/buildpacks/php/v4.4.0

You really shouldn't be using cflinuxfs2 at this point. Run `cf push -s cflinuxfs3` to upgrade.

**Comment by matosmts** [comment]
I tried to use cflinuxfs3, but after this command cf push -s cflinuxfs3, Im getting this error:
Getting app info...
Stack cflinuxfs3 not found
FAILED

Any suggestion to solve this problem?

**Comment by dmikusa-pivotal** [comment]
You need to talk with your platform operator. It sounds like the version of CF that they have deployed, the one you're targeting with `cf target`, is quite old. It would need to be updated before you can migrate to `cflinuxfs3`. For now, you'll just need to stick with the latest v4.3.x version of the PHP buildpack.
