### ISSUE TITLE
How to add custom extensions not included in the list?

### ISSUE THREAD

**Issue by libnux** [cloudfoundry/php-buildpack#33]
Hi,

Taking php-zookeeper as example, it's not included in the extension list, how could I add it? 

According to the [discussion](https://groups.google.com/a/cloudfoundry.org/forum/#!searchin/vcap-dev/php/vcap-dev/m19ajZEOlIM/2lJWmvO0CWMJ), it seems to me that I need to write an extension script to do this. 

Is there other way to do this? For example, if I've built out the .so file on a Lucid_64 machine, is is possible to use this .so file? 

Thanks!

**Comment by dmikusa-pivotal** [comment]
The method listed in that email should still work.  Sorry, I haven't gotten around to making an easier way to do it yet.

I would also suggest opening an issue [here](https://github.com/dmikusa-pivotal/cf-php-buildpack-binary-build-scripts/issues) to request official support for the extension ([done](https://github.com/dmikusa-pivotal/cf-php-buildpack-binary-build-scripts/issues/7)).  If it's an open source extension like `php-zookeeper`, I'd be happy to ship it with the build pack.

Dan

**Comment by libnux** [comment]
Thanks, Dan. 

Besides zookeeper, we also need the extensions of yaf, eaccelerator, lua and kafka. I'll open an issue for this.
