### ISSUE TITLE
Missing zip extension in php-7.4.x

### ISSUE THREAD

**Issue by kpricorn** [cloudfoundry/php-buildpack#331]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?

```
cf curl /v2/info
{
   "name": "",
   "build": "",
   "version": 0,
   "description": "Cloud Foundry provided by Swisscom",
   "min_cli_version": "6.42.0",
   "min_recommended_cli_version": "latest",
   "api_version": "2.143.0",
   "osbapi_version": "2.15",
}
cf version
cf.exe version 6.41.0+dd4c76cdd.2018-11-28
```

What version of the buildpack you are using?

master

If you were attempting to accomplish a task, what was it you were attempting to do?

Instantiating `ZipArchive` from within a PHP application deployed by a 7.4.* buildpack. e.g.

What did you expect to happen?

The class `ZipArchive` class should be found as with the previous 7.3 buildpack.

What was the actual behavior?

The `ZipArchive` class could not be found due to the missing zip extension. Looking at the PHP dependencies loaded by the buildback, the required `zip.so` is missing in the 7.4.x versions.

```
❯ curl --silent https://buildpacks.cloudfoundry.org/dependencies/php/php7-7.3.13-linux-x64-cflinuxfs3-f15bd873.tgz | tar -ztv | grep zip.so
-rwxr-xr-x root/root    256480 2019-12-18 14:58 php/lib/php/extensions/no-debug-non-zts-20180731/zip.so
lrwxrwxrwx root/root         0 2019-12-18 14:58 php/lib/libzip.so.4 -> libzip.so.4.0.0
-rw-r--r-- root/root     80328 2019-12-18 14:58 php/lib/libzip.so.4.0.0
lrwxrwxrwx root/root         0 2019-12-18 14:58 php/lib/libzip.so -> libzip.so.4.0.0

❯ curl --silent https://buildpacks.cloudfoundry.org/dependencies/php/php7-7.4.0-linux-x64-cflinuxfs3-f72ba7f2.tgz | tar -ztv | grep zip.so
lrwxrwxrwx root/root         0 2019-12-06 23:21 php/lib/libzip.so.4 -> libzip.so.4.0.0
lrwxrwxrwx root/root         0 2019-12-06 23:21 php/lib/libzip.so -> libzip.so.4.0.0
-rw-r--r-- root/root     80328 2019-12-06 23:21 php/lib/libzip.so.4.0.0

❯ curl --silent https://buildpacks.cloudfoundry.org/dependencies/php/php7-7.4.1-linux-x64-cflinuxfs3-c5a7f59e.tgz | tar -ztv | grep zip.so
lrwxrwxrwx root/root         0 2019-12-18 13:53 php/lib/libzip.so.4 -> libzip.so.4.0.0
-rw-r--r-- root/root     80328 2019-12-18 13:53 php/lib/libzip.so.4.0.0
lrwxrwxrwx root/root         0 2019-12-18 13:53 php/lib/libzip.so -> libzip.so.4.0.0
```

It seems, as if the configure syntax to enable the extenions has changed in 7.4. => https://www.php.net/manual/en/zip.installation.php#124570

Please confirm where necessary:
* [x] I have included a log output
* [x] My log includes an error message
* [x] I have included steps for reproduction

**Comment by dmikusa-pivotal** [comment]
Thanks for pointing this out. Looks like we need to update the builder: https://github.com/cloudfoundry/binary-builder/blob/master/recipe/php7_recipe.rb#L17

**Comment by shanks3012** [comment]
@kpricorn This should be on develop branch and will make its way to master next week. Closing for now, but feel free to reopen if you still experience issues.

Thanks
