### ISSUE TITLE
how to start a linux service like cron with buildpack configuration?

### ISSUE THREAD

**Issue by landall** [cloudfoundry/php-buildpack#339]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?

{
   "name": "IBM Cloud",
   "build": "v12.33.0",
   "support": "http://ibm.biz/bluemix-supportinfo",
   "version": 0,
   "description": "IBM Bluemix",
   "authorization_endpoint": "https://iam.cloud.ibm.com/cloudfoundry/login/us-south",
   "token_endpoint": "https://uaa.us-south.cf.cloud.ibm.com",
   "min_cli_version": null,
   "min_recommended_cli_version": null,
   "app_ssh_endpoint": "ssh.us-south.cf.cloud.ibm.com:2222",
   "app_ssh_host_key_fingerprint": "c7:1f:89:2a:62:3b:78:a9:08:c9:33:81:fb:39:26:da",
   "app_ssh_oauth_client": "ssh-proxy",
   "doppler_logging_endpoint": "wss://doppler.us-south.cf.cloud.ibm.com:443",
   "api_version": "2.146.0",
   "osbapi_version": "2.15",
   "user": "b9da9518-ed2f-4bc5-91ba-e9421af2c75d"
}

cf version 6.46.1+4934877ec.2019-08-23

What version of the buildpack you are using?

https://buildpacks.cloudfoundry.org/dependencies/php/php7-7.2.26-linux-x64-cflinuxfs3-d7884fb8.tgz

I can not find a way to get the root access of cloudfoundry so I would like to know if there is a way to start cron service when I run cf push.

**Comment by dmikusa-pivotal** [comment]
It is not possible to get root in a container running on Cloud Foundry. You can *only* run things as the `vcap` user. There is no way to change this when deploying apps with buildpacks.

[Cloud Foundry can run one-off tasks](https://docs.cloudfoundry.org/devguide/using-tasks.html) but it falls short of cron in that it doesn't have built-in scheduling.

There are a number of ways to make this work...

1.) Run a task that never ends, but sleeps and periodically wakes up to run your code.
2.) Run a scheduler like cron or jobber in its own container.
3.) Use cron as a service. There are a [number of these services](https://www.cronjobservices.com/) which will simply send you an HTTP(S) request at a scheduled time to trigger your cron jobs. You can then expose an endpoint in your app to receive this request and use that to trigger your custom code.

Probably other options a well. Feel free to share your solution if you find a different one that works well.

**Comment by landall** [comment]
> It is not possible to get root in a container running on Cloud Foundry. You can _only_ run things as the `vcap` user. There is no way to change this when deploying apps with buildpacks.
> 
> [Cloud Foundry can run one-off tasks](https://docs.cloudfoundry.org/devguide/using-tasks.html) but it falls short of cron in that it doesn't have built-in scheduling.
> 
> There are a number of ways to make this work...
> 
> 1.) Run a task that never ends, but sleeps and periodically wakes up to run your code.
> 2.) Run a scheduler like cron or jobber in its own container.
> 3.) Use cron as a service. There are a [number of these services](https://www.cronjobservices.com/) which will simply send you an HTTP(S) request at a scheduled time to trigger your cron jobs. You can then expose an endpoint in your app to receive this request and use that to trigger your custom code.
> 
> Probably other options a well. Feel free to share your solution if you find a different one that works well.

Thanks for your reply. At present, I use ADDITIONAL_PREPROCESS_CMDS to start a never-ending task to play as 
 a crontab.
Webcron can not run a long process.

**Comment by dmikusa-pivotal** [comment]
That works & yes. If you're using a web-based cron, you'd need to be careful about execution time. PHP has limits it enforces, but so do the load balancing layers (which vary depending on where you run your app).

I'm going to close this out as there's nothing we can do at the buildpack level. If anyone else has a good way to handle this, feel free to share it.
