### ISSUE TITLE
composer report error because of lacking of ext-zip

### ISSUE THREAD

**Issue by landall** [cloudfoundry/php-buildpack#341]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?

{
"name": "IBM Cloud",
"build": "v12.33.0",
"support": "http://ibm.biz/bluemix-supportinfo",
"version": 0,
"description": "IBM Bluemix",
"authorization_endpoint": "https://iam.cloud.ibm.com/cloudfoundry/login/us-south",
"token_endpoint": "https://uaa.us-south.cf.cloud.ibm.com",
"min_cli_version": null,
"min_recommended_cli_version": null,
"app_ssh_endpoint": "ssh.us-south.cf.cloud.ibm.com:2222",
"app_ssh_host_key_fingerprint": "c7:1f:89:2a:62:3b:78:a9:08:c9:33:81:fb:39:26:da",
"app_ssh_oauth_client": "ssh-proxy",
"doppler_logging_endpoint": "wss://doppler.us-south.cf.cloud.ibm.com:443",
"api_version": "2.146.0",
"osbapi_version": "2.15",
"user": "b9da9518-ed2f-4bc5-91ba-e9421af2c75d"
}

cf version 6.46.1+4934877ec.2019-08-23
What version of the buildpack you are using?

Buildpack version 4.4.6

It will block the 'cf push' operation in the step of composer install if some package needs ext-zip or ext-mbstring. Including a php.ini.d/*.ini cannot work.

**Comment by landall** [comment]
I can add a requirement of ext-zip:"*" to the composer.json.
but I think it is a normal way to solve this trouble.

**Comment by dmikusa-pivotal** [comment]
The buildpack should find extensions listed in Composer. Do you have a composer.lock file? or just composer.json?

**Comment by landall** [comment]
> The buildpack should find extensions listed in Composer. Do you have a composer.lock file? or just composer.json?

just a json file. I haven‘t submit the lock file and vendor folder to VCS.

it seems the php do not load scanned ini files when the composer run.

**Comment by landall** [comment]
"mk-j/php_xlsxwriter" 
add this package will reproduce it in ibm cloud lite.

**Comment by dmikusa-pivotal** [comment]
You need to add a `composer.lock` file. Your `composer.json` file only has dependencies you specifically install. Any transitive dependencies are not in there. In contrast, the `composer.lock` file has everything. If you push up the `composer.lock` file, the buildpack will be able to examine it and get a complete list of what is required, including PHP C extensions.

For what it's worth, the next major version of the buildpack is going to require both files.

**Comment by landall** [comment]
> You need to add a `composer.lock` file. Your `composer.json` file only has dependencies you specifically install. Any transitive dependencies are not in there. In contrast, the `composer.lock` file has everything. If you push up the `composer.lock` file, the buildpack will be able to examine it and get a complete list of what is required, including PHP C extensions.
> 
> For what it's worth, the next major version of the buildpack is going to require both files.

ok, i see. I will submit this file from now on.
