### ISSUE TITLE
Redis session without password

### ISSUE THREAD

**Issue by pbleuse-orange** [cloudfoundry/php-buildpack#355]
https://github.com/cloudfoundry/php-buildpack/blob/cde40f369003bc8c788cab3111bc0769bd9f3d17/extensions/sessions/extension.py#L51

Hello,

We have some Redis service broker without password.
In this case the final config is
```
session.save_path=tcp://127.0.0.1:3201?auth=
```
and cause session crash.

For work it must be :
```
session.save_path=tcp://127.0.0.1:3201
```
and actually is only possible with raw config in .bp-config

it must be a good feature to do this automatically

Pascal

**Comment by dmikusa-pivotal** [comment]
Can you explain your use case more? 

For a little history, a decision was made to require auth for security reasons. Basically, when I wrote this code I couldn't think of a case where you could conceivably use Redis without authentication.

I see you're using 127.0.0.1 as the IP, which would seem to suggest that Redis is running in the container? That doesn't make a lot of sense though because the container is local and you couldn't share session data across app instances that way. At any rate, would you be able to explain your use case more? Thanks

**Comment by pbleuse-orange** [comment]
Tx for answer.

Sorry for 127.0.0.1 is for example. IP is like 10.123.1.25 and of course not on local container ;)

It's redis with dynomite and dynomite not support auth method.

https://github.com/Netflix/dynomite/blob/dev/notes/redis.md#Connection

Additionnaly, this service is on internal network and security is define at this stage.

In this case, redis config not have password.

**Comment by dmikusa-pivotal** [comment]
Thanks for sharing. It helps to understand the challenges here. I would be OK with adding something, but I think it would a.) not be the default and b.) need to be explicitly opt-ed into like "disable-auth: true" or something like that.

I also cannot speak to the feasibility of adding this to the current php-buildpack, that would be up to @kvedurmu. New development is really going into the Cloud Native PHP buildpacks. If that would work, feel free to add a request on https://github.com/paketo-buildpacks/php-web. It seems feasible to add support into php-web for an option like `disable-auth`.

**Comment by pbleuse-orange** [comment]
It's allready implemented on php-web:
https://github.com/paketo-buildpacks/php-web/blob/58cb4597d903c0747a15e5912772ebce84fe972a/features/redis.go#L153
but without specific param, only based if password exists and for me it's good solution, but I understand your vision.

Just for understand, Cloud Native PHP BP replace CFY PHP buildpack in future ?

**Comment by kvedurmu** [comment]
Hi. As Dan mentioned, our team's development efforts are focused on the next generation Paketo Buildpacks. We don't have the bandwidth to implement this in the v2 PHP Buildpack, but would welcome a PR if you're up for it.

**Comment by kvedurmu** [comment]
Closing this out, due to inactivity. As mentioned, we're not planning on supporting this in the v2 PHP Buildpack, but we'll always set aside time to review a PR for this.
