### ISSUE TITLE
'mbstring' is missing from my php installation

### ISSUE THREAD

**Issue by McFads1** [cloudfoundry/php-buildpack#360]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?

cf version 6.49.0+d0dfa93bb.2020-01-07
"build": "2.7.9-build.21",
cli version: 6.23.0

What version of the buildpack you are using?
4.4.6

If you were attempting to accomplish a task, what was it you were attempting to do?
run a cms library called grav
command: php/bin/php bin/grav install

What did you expect to happen?
grav to install

What was the actual behavior?
`'mbstring' extension is not loaded.  This is required for Grav to run correctly`

Please confirm where necessary:
* [ ] I have included a log output
* [ ] My log includes an error message
* [ ] I have included steps for reproduction

-------------------------------------------------------------
The steps I have taken:
created path: .bp-config/php/php.ini.d/mbstring.ini 
contents:

```
[PHP]
extension=mbstring.so
extension=mbstring
```

when i run php -m, mbstring does not show up.

I could use some direction here? the version of PHP i'm on is 7.3.13

---- edit ---
if i put extension=fakeexenstion , it doesn't even show up in the logs as an error when i cf push

**Comment by ikari7789** [comment]
This is affecting us as well. I'm wondering are the extensions loaded before or after composer is run? This is kind of a major bug.

**Comment by arjun024** [comment]
Hi,

We were not able to reproduce this.

```
cf push phpapp7313 -b php_buildpack446 -c "php -m" --health-check-type none && cf logs phpapp7313 --recent
```
and it printed out

```
2020-12-16T16:27:20.84+0000 [APP/PROC/WEB/0] OUT mbstring
```

The issue is being closed. If you think the issue persists, feel free to reopen with a sample app
