### ISSUE TITLE
Some programs start hhvm without config options, how to solve?

### ISSUE THREAD

**Issue by chregu** [cloudfoundry/php-buildpack#37]
Hi

I have a problem which I don't know how to solve properly.

Symfony sometimes calls additional php commands via shell from with php, eg. app/console (again during the post-install-cmd for example).

It tries to be clever and searches for viable binaries. If it's called from HHVM, it's looking for that. It of course finds it, but it calls it without the "-c  $HOME/hhvm/etc/php.ini" option, therefore some stuff fails for me for those commands.

There's unfortunately not something like PHPRC for hhvm, it is just looking in /etc/hhvm/php.ini for a default .ini. On that we can't write AFAIK, not even in the buildpack (correct me, if I'm wrong)

Maybe I'll open an Issue at HHVM for that, it would be nice, if it supported that

One solution I found after long long trying to figure out where it goes wrong:

write somewhere an hhvm script with the following content (eg. bin/):

````

$HOME/hhvm/usr/bin/hhvm -c "$HOME/hhvm/etc/php.ini" "$@"
````
and set the env variable PHP_BINARY to
`PHP_BINARY: /home/vcap/app/bin/hhvm``

Does anyone have a better solution? If not, should we add such a script somewhere into the buildpack  so one can use that by default?

I assume, the proper thing would be to ask HHVM to add something like PHPRC, and the above as temporary solution, I don't have to change the buildpack, I can put that script into my app somewhere.

But any input is welcome

**Comment by dmikusa-pivotal** [comment]
My $0.02 is that hhvm should support something like `PHPRC` for setting the configuration directory.  It would certainly make things easier for the build pack and it would give users another option for supplying configuration files. 

As far as how to handle this in the build pack, is this happening during staging or at runtime?  If it's at staging, I would suggest trying to defer those tasks to run in the runtime environment, like we discussed [here](https://github.com/cloudfoundry/php-buildpack/issues/34#issuecomment-71304583).

At runtime, the build pack currently defines a [bash function called hhvm](https://github.com/cloudfoundry/php-buildpack/blob/master/lib/hhvm/extension.py#L26-L27) in the script that starts your application.  This wraps calls to `hhvm` and makes sure that the `-c` argument to `php.ini` is always supplied (actually now that I look at things, we're probably doubling up the `-c` argument for php.ini but that's OK).

If you set the command that you need to run as an `ADDITIONAL_PREPROCESS_CMDS` that should run after the hhvm function is defined and hopefully that will make sure that the `-c` argument is supplied.  If that's not working for you, I wouldn't be opposed to using a wrapper script instead.  This might be more flexible for situations like this.

I'd see the build pack doing something like this:

  1.) Unpack hhvm
  2.) Move hhvm binary to hhvm.bin or hhvm.orig or something like that
  3.) Create the wrapper script, called hhvm.  Place it where the binary usually resides.
  4.) chmod it as executable.

Could you submit a small test app that triggers this problem?  It would help debugging, allow us to confirm a fix and ensure no future regressions.

Thanks!

**Comment by chregu** [comment]
Yes, it's during runtime where it hit me (but during staging, the same problem does occur)

I saw the shell function for hhvm, the problem is that symfony is searching for a file called hhvm to execute and discards all command line options given 

I'll try to come up with a test case and also made a feature request to HHVM at https://github.com/facebook/hhvm/issues/4722
