### ISSUE TITLE
not able to execute ADDITIONAL_PREPROCESS_CMDS command at start.

### ISSUE THREAD

**Issue by ajitrishabh** [cloudfoundry/php-buildpack#371]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?
```
{                                                                                      
   "name": "MindSphere",                                                               
   "build": "v1.21.0",                                                                 
   "support": "http://www.siemens.com/automation/service&support",                     
   "version": 0,                                                                       
   "description": "MindSphere PaaS",                                                   
   "authorization_endpoint": "https://login.cf.eu1.mindsphere.io",                     
   "token_endpoint": "https://uaa.cf.eu1.mindsphere.io",                               
   "min_cli_version": "6.30.0",                                                        
   "min_recommended_cli_version": "latest",                                            
   "app_ssh_endpoint": "ssh.cf.eu1.mindsphere.io:8443",                                
   "app_ssh_host_key_fingerprint": "//",      
   "app_ssh_oauth_client": "ssh-proxy",                                                
   "doppler_logging_endpoint": "wss://doppler.cf.eu1.mindsphere.io:443",               
   "api_version": "2.148.0",                                                           
   "osbapi_version": "2.15"                                                            
}                                                                                      
cf version 6.40.0+07673feb9.2018-10-08
```

What version of the buildpack you are using?
**buildpacks:        php 4.4.13**

If you were attempting to accomplish a task, what was it you were attempting to do?
Hi @dmikusa-pivotal ,

not able to run sh script in my app as you suggested here [https://github.com/cloudfoundry/php-buildpack/issues/17#issuecomment-479480188](url)

need help here.
1. i used this **ADDITIONAL_PREPROCESS_CMDS** not working
2. did `cf push -c 'loop.sh'` not working 
2. created **Procfile** file still not working 

if you can provide sample app to test at my end it would great.

![image](https://user-images.githubusercontent.com/7721618/87244691-9e4b6d00-c45c-11ea-85e6-23a3780264b1.png)

```
Updating app with these attributes...
  name:                phptestingcron
  path:                C:\xampp\htdocs\mindsphere\cfphpapp\php_cf_cron
  command:             loop.sh
  disk quota:          512M
  health check type:   port
  instances:           1
  memory:              128M
  stack:               cflinuxfs3
  routes:
    phptestingcron.apps.eu1.mindsphere.io
```

**2020-07-12T16:18:50.80+0530 [APP/PROC/WEB/0] ERR bash: loop.sh: command not found**
```
 2020-07-12T16:18:50.79+0530 [APP/PROC/WEB/0] OUT Could not open input file: ../htdocs/testing.php
   2020-07-12T16:18:50.80+0530 [APP/PROC/WEB/0] ERR bash: loop.sh: command not found
   2020-07-12T16:18:50.84+0530 [APP/PROC/WEB/0] OUT Exit status 127
   2020-07-12T16:18:50.84+0530 [CELL/SSHD/0] OUT Exit status 0
   2020-07-12T16:18:57.53+0530 [CELL/0] OUT Cell a3ffc01d-afd8-4193-9493-e56c1c95de1f stopping instance 34ab241a-4973-42da-723e-281a
   2020-07-12T16:18:57.53+0530 [CELL/0] OUT Cell a3ffc01d-afd8-4193-9493-e56c1c95de1f destroying container for instance 34ab241a-4973-42da-723e-281a
   2020-07-12T16:18:57.55+0530 [API/1] OUT Process has crashed with type: "web"
   2020-07-12T16:18:57.60+0530 [API/1] OUT App instance exited with guid 23969abf-8f95-4ce2-a8db-4d965725b07f payload: {"instance"=>"34ab241a-4973-42da-723e-281a", "index"=>0, "cell_id"=>"a3ffc01d-afd8-4193-9493-e56c1c95de1f", "reason"=>"CRASHED", "exit_description"=>"APP/PROC/WEB: Exited with status 127", "crash_count"=>3, "crash_timestamp"=>1594550937498536096, "version"=>"213097ef-3c7a-4782-ada1-453fcf0fa1a1"}
   2020-07-12T16:18:57.77+0530 [PROXY/0] OUT Exit status 137
   2020-07-12T16:18:58.04+0530 [CELL/0] OUT Cell a3ffc01d-afd8-4193-9493-e56c1c95de1f successfully destroyed container for instance 34ab241a-4973-42da-723e-281a
```

What did you expect to happen?
sh script suppose to so that php file can run in background

What was the actual behavior?
`   2020-07-12T16:18:50.80+0530 [APP/PROC/WEB/0] ERR bash: loop.sh: command not found`

Please confirm where necessary:
* [x] I have included a log output
* [x] My log includes an error message
* [x] I have included steps for reproduction

**Comment by sophiewigmore** [comment]
Hi @ajitrishabh, sorry to hear that this isn't working for you as expected. Is this still causing an issue for you? If so, would you mind providing more information about your use case?

**Comment by bbodenmiller** [comment]
@ajitrishabh I had do run command of `mv ./htdocs/loop.sh . && chmod +x ./loop.sh && exec ./loop.sh` because:
* By default files look to be uploaded inside `$HOME/htdocs` but commands look to run from `$HOME`
* Must move file because adding execute permission on `loop.sh` while inside `htdocs` does not seem to work

**Comment by menehune23** [comment]
@ajitrishabh I'm closing this as stale, but if this is still something you'd like to discuss, feel free to reopen and respond with the details requested by @sophiewigmore. Thanks!
