### ISSUE TITLE
Default timeout when using HTTPD & PHP is only 60 seconds | PHP Buildpack 4.4.18

### ISSUE THREAD

**Issue by ils-pushpakb** [cloudfoundry/php-buildpack#372]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?

`{
   "name": "",
   "build": "",
   "support": "https://support.run.pivotal.io",
   "version": 0,
   "description": "Cloud Foundry sponsored by Pivotal",
   "authorization_endpoint": "https://login.run.pivotal.io",
   "token_endpoint": "https://uaa.run.pivotal.io",
   "min_cli_version": "6.22.0",
   "min_recommended_cli_version": "latest",
   "app_ssh_endpoint": "ssh.run.pivotal.io:2222",
   "app_ssh_host_key_fingerprint": "e7:13:4e:32:ee:39:62:df:54:41:d7:f7:8b:b2:a7:6b",
   "app_ssh_oauth_client": "ssh-proxy",
   "doppler_logging_endpoint": "wss://doppler.run.pivotal.io:443",
   "api_version": "2.151.0",
   "osbapi_version": "2.15",
   "routing_endpoint": "https://api.run.pivotal.io/routing"
}
cf version 6.35.2+88a03e995.2018-03-`

What version of the build pack you are using?
PHP Buildpack 4.4.18

If you were attempting to accomplish a task, what was it you were attempting to do?
 I am calling data from database in bulk, and an extensive query is running for it

What did you expect to happen?
I wish to see the output but due to httpd timeout fixed to 60sec, the performed operation is throwing error 504 after 60sec. Check ss 
![image](https://user-images.githubusercontent.com/37648198/87571768-2e511700-c6e8-11ea-8a46-c4030ce8ab2b.png)

On the log over pivotal earlier I was getting "Proxy Fcgi:error -  The timeout specified has expired", but after using httpd-php.conf under .bp-config/httpd/extra and increasing proxy timeout, using this reference -

https://github.com/cloudfoundry/php-buildpack/issues/212#issuecomment-396211189

I am getting 200 response, see below - 
![image](https://user-images.githubusercontent.com/37648198/87572336-01e9ca80-c6e9-11ea-8f6d-788dfa45462a.png)
 in PWS metrics logs console but still getting error 504 timeout on the browser.

 Tried almost everything, but it is still using the default timeout of httpd in PHP build pack.

**Comment by kvedurmu** [comment]
Hi. Our team is currently focused on building out the next generation Paketo Buildpacks. This is good feedback for something that we should make configurable in the PHP Paketo Buildpack (see https://github.com/paketo-buildpacks/php-web/issues/4). I'd recommend using the suggested workaround here (modifying the httpd .bp-config).

**Comment by kvedurmu** [comment]
Closing this out due to inactivity.
