### ISSUE TITLE
Missing sodium extension in PHP 7.4.X

### ISSUE THREAD

**Issue by MadCat34** [cloudfoundry/php-buildpack#374]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?
```
I can give only this information
cf curl /v2/info
{
   [...]
   "api_version": "2.147.0",
   "osbapi_version": "2.15",
}

cf version 7.0.1+fb3f929c2.2020-06-24
```

What version of the buildpack you are using?
v4.4.18 with PHP 7.4.X

If you were attempting to accomplish a task, what was it you were attempting to do?
Enable sodium.so

What did you expect to happen?
Application is deployed

What was the actual behavior?
Application is not deployed
Message: "**RuntimeError: The extension "sodium" is not provided by this buildpack**"

Please confirm where necessary:
* [ ] I have included a log output
* [ x ] My log includes an error message
* [ ] I have included steps for reproduction

**Comment by floragj** [comment]
Hi there. We're taking a look at this.

I imagine that you specified the sodium extension [as described in the Cloud Foundry docs](https://docs.cloudfoundry.org/buildpacks/php/gsg-php-config.html#php-extensions). Is that the case?

**Comment by aszenz** [comment]
I see that the extension sodium is not included in php-7.4.9 and php7.4.10 while it is present in older versions for v4.2.2 of the builpack

**Comment by MadCat34** [comment]
@floragj Yes, I have done as described in the Cloud Foundry docs.

**Comment by floragj** [comment]
As of right now, the `sodium` extension is [explicitly excluded](https://github.com/cloudfoundry/buildpacks-ci/blob/564c8db25785188b848b667a8068795cddf657b6/tasks/build-binary-new/php74-extensions-patch.yml#L4) from the 7.4 versions of php within the buildpack.  The team is currently looking into why it's not included and whether it can be added again.

For now, you'd need to use a 7.3.* version of php from the buildpack to get the desired extension.

cc @mdelillo

**Comment by kvedurmu** [comment]
The sodium extension has been [added back](https://github.com/cloudfoundry/buildpacks-ci/commit/4c95b1064e029ae818473488dc1f357a5525e59a) to 7.4.x versions of PHP. The latest release of the PHP buildpack has these changes - https://github.com/cloudfoundry/php-buildpack/releases/tag/v4.4.24
