### ISSUE TITLE
Adding nodejs/npm as an option?

### ISSUE THREAD

**Issue by chregu** [cloudfoundry/php-buildpack#38]
More and more people are using eg. gulp.js to minify and concat their css and js files during deployment. (We at Liip, for example ;)). But that needs nodejs and npm. Would it be a good idea to add nodejs/npm as an option to the buildpack? As an extension and configurable in options.json

I could try to do that, should be doable, but not sure if you agree this should be added

We can of course do that step locally before doing cf push, but I would prefer to do that during staging.

I could also add it as .extension into the app itself, if we can't agree that this should be in the buildpack.

And in general: Is this the right place for such questions? Or is there a more preferred one? The vcap-dev mailing list?

**Comment by dmikusa-pivotal** [comment]
My vote would be to leave this as a feature request for now.  If we get more interest, we can pull it into the build pack.

If you want to implement this for yourself, I'd say adding a custom extension to `.extensions` would be the way to go.  Then if there is more interest in this feature and you're willing, we could pull your extension into the build pack.

**Comment by jchesterpivotal** [comment]
Right now PHP buildpack is unique in that we own it entirely, so the product management function is now entirely in-house. For the other buildpacks we rely on the upstream buildpack to provide some feature guidance.

As you can see, cf-gitbot enters Tracker bugs from Github issues. Then it's up to the Product Manager (@MarkKropf) to schedule it according to the current view of customer value.

**Comment by MarkKropf** [comment]
I'm not sure if we'd optimize the push experience by adding the download time of node/v8/npm to gain the value of minifying at staging instead of pre-minifying before push. @chregu let me know if I'm characterizing this incorrectly.

**Comment by chregu** [comment]
If I make an offline pack, the download time should be minimal.

But the main problem is, that I'd like to prevent people doing just a "cf push" before minifying the files (or needing the build environment locally, which may be not setup correctly). 

But OTOH, I maybe need a "pre deployment script" anyway do make sure everything is set correctly and there I could also do the minifying.

**Comment by dbu** [comment]
https://packagist.org/packages/mouf/nodejs-installer could be a workaround

**Comment by Dannyzen** [comment]
@chregu is this issue good to close?

**Comment by chregu** [comment]
yes, you can close this
