### ISSUE TITLE
Upgrade rdkafka version from 3.1.2 to 4.0.0

### ISSUE THREAD

**Issue by crypticro** [cloudfoundry/php-buildpack#398]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?

cf7 version 7.0.2+17b4eeafd.2020-07-24
min cli version: 6.51.0
api version: 2.152.0
osbapi_version: 2.15

What version of the buildpack you are using?

v4.4.22

If you were attempting to accomplish a task, what was it you were attempting to do?

We required the rdkafka version of at least 4.0.0. However if we set the version in the composer file to "ext-rdkafka": ">=4.0.0" it fails.

What did you expect to happen?

Is it possible to force the rdkafka version to 4.0.0? 

What was the actual behavior?

```
Installing dependencies (including require-dev) from lock file
   Your requirements could not be resolved to an installable set of packages.
     Problem 1
       - The requested PHP extension ext-rdkafka >=4.0.0 has the wrong version (3.1.2) installed. Install or enable PHP's rdkafka extension.
   -----> Composer command failed

```

Please confirm where necessary:
* [x ] I have included a log output
* [x ] My log includes an error message
* [x ] I have included steps for reproduction

**Comment by kvedurmu** [comment]
Hi. The [latest release of the PHP Buildpack](https://github.com/cloudfoundry/php-buildpack/releases/tag/v4.4.23) bumps rdkafka to [4.0.3](https://github.com/cloudfoundry/php-buildpack/releases/tag/v4.4.23)
