### ISSUE TITLE
PHP_DEFAULT version is approaching it's end of life.

### ISSUE THREAD

**Issue by kalpaitch** [cloudfoundry/php-buildpack#399]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?
All versions

What version of the buildpack you are using?
latest (v4.4.22)

If you were attempting to accomplish a task, what was it you were attempting to do?
Ensure I can use the PHP_DEFAULT value.

What did you expect to happen?
That the PHP_DEFAULT in `/defaults/options.json` would be maintained, to the point where it was registered to an actively supported, stable php version.
See supported php versions, php 7.2 comes to end of life on 30th November 2020 - https://www.php.net/supported-versions.php

What was the actual behavior?
PHP 7.2 is still registered as the PHP_DEFAULT version in `/defaults/options.json`

Please confirm where necessary:
* [n/a] I have included a log output
* [n/a] My log includes an error message
* [n/a] I have included steps for reproduction

**Comment by kvedurmu** [comment]
Hi @kalpaitch - we typically send out deprecation notices 30 days before the dependency goes EOL upstream. So in this case, you can expect the first releases after November 30th to have removed PHP 7.2 dependencies, and at that point 7.4 will become the default version.
