### ISSUE TITLE
Interested in adding varnish?

### ISSUE THREAD

**Issue by chregu** [cloudfoundry/php-buildpack#40]
I integrated varnish in the PHP buildpack

We need this mostly to be able to have a PHP listeners which listens to RabbitMQ and for example purges the cache on demand and does other stuff

But it could also be useful for having varnish directly in the same cf app for PHP applications, not the immediate need by us, but could be useful

Would there be general interest to get this "upstream"? Or shall I just continue maintaining the fork? It's not perfect yet, but it works.

Here's the branch:
https://github.com/chregu/php-buildpack/tree/with-varnish

And here's a small REAME:

https://github.com/chregu/php-buildpack/blob/with-varnish/docs/varnish.md

PS. it was a little bit of pain to get the $PORT changed for http and nginx when there's a varnish in front, and I'm still not sure if there isn't a better way than I did. But the env variables returned by service_environment() are not available in rewrite and PORT is anyway only very late available  (and not really in service_environment()), if I remember correctly

**Comment by dmikusa-pivotal** [comment]
I'm on the fence about caching in the build pack.  On one hand it can be useful and it's pretty easy to get setup.  On the other hand, you either end up with a cache per app which limits it's usefulness or you end up with one cache "app" that serves requests (nice!) or has to pass them back through the router a second time (bummer).

The other issue is that the runtime team has submitted a proposal for [Route Services](https://groups.google.com/a/cloudfoundry.org/d/msg/vcap-dev/bfin6_Bl_zQ/G6eXRL5sEg8J), which seems like it would be the way to go for a Varnish service.  What do you think about the proposal?  Would it cover your use cases?

**Comment by chregu** [comment]
Saw the route services on the mailinglist, didn't yet look into it, will do

We do plan to have a cache "app" (or 2 for redundancy) separate from the actual application, but we need some kind of "listener" to easily run some commands in them, like clearing the cache and other things not easily possible from within varnish and almost not possible if you have more than one varnish in CF.  And we did this in PHP, that's why we integrated varnish into this buildpack. So our use case may be a little bit special and I could understand if you hesitate to integrate that in the official buildpack. I'll maintain it anyway. The diff to the official buildpack is small, so it shouldn't be hard to do that. But that also means it doesn't add much to the buildpack in terms of code ;)

**Comment by dmikusa-pivotal** [comment]
Thanks for the feedback!  If you're OK maintaining the fork for now, I'd say let's leave this open and see if anyone else is interested in this functionality.

As far as the patch itself, I'm a little concerned with the way it's integrated.  It's not bad, but I think the build pack could be improved to be more flexible for this type of use case.  Before pulling it in, I'd want to see if we could do something to make the integration easier and less cross cutting (i.e. so you don't have to touch the core extensions & config files).  

I'm also a little concerned with testing.  It adds a new dimension of things that need to be tested.  i.e. we'd probably want to run integration tests for our current configurations and the same configurations with varnish.

**Comment by chregu** [comment]
Didn't think about testing yet, but yes, could get complicated.

And if you find a way so I don't have to touch core files, that would be great of course ;)

**Comment by chregu** [comment]
Just FYI, my "official" fork is now here: https://github.com/chregu/cf-php-varnish-buildpack
I will try to maintain it and merge stuff from the official buildpack into the fork from time to time

(I also updated HHVM to 3.5.0 in that fork)

**Comment by jchesterpivotal** [comment]
Hi @chregu 

We haven't gotten a Product decision on this, so this is just my view on the background and technical stuff.

Generally we're going to be reluctant to add features like this to the buildpack without a lot of customer demand. We try to keep each buildpack as simple as possible. For CF, the preferred architectural approach is that each app or service is run as an independent push. So in this case, varnish would run separately from PHP.

In particular, we think it would work better in general to publish Varnish instances as [services](http://docs.run.pivotal.io/devguide/services/), not applications. This way service information is published in the [`VCAP_SERVICES`](http://docs.run.pivotal.io/devguide/deploy-apps/environment-variable.html#VCAP-SERVICES) environment variable and your PHP applications can look them up at runtime.

There's also the advantage that upon scaling up to multiple instances of the PHP app, the Varnish cache will be shared amongst multiple instances -- you won't be carrying multiple copies of content in multiple independent caches.

Lastly, it allows you to scale Varnish independently of PHP instances.

As I said, we still don't have a decision from our product managers (@MarkKropf or @flavorjones). But as a general statement I think this proposal is unlikely to be pulled in.

**Comment by flavorjones** [comment]
For now, I'd like to delay the decision on whether to include additional packages into the buildpacks. We hope to have a proposal soon to make buildpacks more easily-extensible; and at that point it may become an application-specific configuration.

I'll leave this open for now; I'd love to pick up the discussion in a month or two.

**Comment by flavorjones** [comment]
@jtarchie Any thoughts on how our extensibility experiments might work with something like adding Varnish as suggested?

**Comment by svrc-pivotal** [comment]
my 2 cents ...  we have a customer prospect interested in varnish + PHP + drupal.   (email me privately for details)  

the route services approach will probably be best when it is ready.   but for now we probably would use something like @chregu 's Varnish standalone buildpack or varnish+PHP buildpack , possibly behind a service broker. 

note @jchesterpivotal even with services you'd need a Varnish buildpack or a Dockerfile  to run this in the elastic runtime , so there is a point here...

the main question IMO is whether this is a corner case, i.e.  the varnish standalone buildpack would be more used (especially when it is paired with a route services broker down the road)... the new diego SSH support somewhat obviates the need for an embedded PHP daemon, as one could do this via the varnish CLI now either direct or via TCP tunnel....  unless you wanted to build a web GUI.   

 I lean towards 'corner case'... unless we have plans to extend / run more daemons inside the PHP buildpack , as it is in theory the foundation for  "any httpd or nginx or fastcgi module" buildpack :)

**Comment by jchesterpivotal** [comment]
I'm not on buildpacks any more, but I think my original logic was reasonable. Varnish is really a service, it should really be shipped, managed and injected as a service. 

Otherwise we'd be talking about memcache buildpacks, redis buildpacks, rabbitmq buildpacks, postgres buildpacks and so on and so forth.
