### ISSUE TITLE
Local vendor directory should not be moved by default

### ISSUE THREAD

**Issue by ikari7789** [cloudfoundry/php-buildpack#409]
https://github.com/cloudfoundry/php-buildpack/blob/2064abbb4a13e2d345640841bba1a88af72d1c29/extensions/composer/extension.py#L203-L214

This logic here breaks situations where a user specifically wants to included vendored items under their webdir under the `/vendor` path. I'm not sure what it's purpose is especially when a vendor dir is already specified by the user in `.bp-config/options.json`

**Comment by menehune23** [comment]
Hi @ikari7789, I'm closing this issue as it's almost a year old now, but if this is still a concern please feel free to reopen.

I'd also invite you to check out the newer [Paketo PHP buildpack](https://github.com/paketo-buildpacks/php) to see if it gives you a better experience. Thank you!
