### ISSUE TITLE
xsl extension

### ISSUE THREAD

**Issue by ivanB1975** [cloudfoundry/php-buildpack#41]
Could you please add the xsl extension on the buildpack?
Many thanks
Bests
Ivan

**Comment by dmikusa-pivotal** [comment]
I added this yesterday.  Are you not seeing it / not able to use it?

**Comment by dmikusa-pivotal** [comment]
https://github.com/cloudfoundry/php-buildpack/commit/0860ba1390c9b7e47c19b24fbb634e859d057125

**Comment by dmikusa-pivotal** [comment]
It's only going to be available to the latest PHP releases though.  Make sure you're not using an older release.

**Comment by ivanB1975** [comment]
Got it!
Thanks

**Comment by dmikusa-pivotal** [comment]
No problem.  Let me know if you have any trouble with it.
