### ISSUE TITLE
Newrelic not working: PHP Warning:  PHP Startup: Unable to load dynamic library

### ISSUE THREAD

**Issue by dah0f** [cloudfoundry/php-buildpack#422]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?
v6

What version of the buildpack you are using?
 Buildpack version 4.4.12

If you were attempting to accomplish a task, what was it you were attempting to do?
1) Add NEWRELIC_LICENSE,
2) Buildpack detecs license and starts downloading the default version of newrelice (newrelic-php5-9.1.0.246-linux.tar.gz)
3) After installing it tries to load the .so files and fails: 
`PHP Warning:  PHP Startup: Unable to load dynamic library '/tmp/app/newrelic/agent/x64/newrelic-20190902.so' (tried: /tmp/app/newrelic/agent/x64/newrelic-20190902.so (/tmp/app/newrelic/agent/x64/newrelic-20190902.so: cannot open shared object file: No such file or directory), /tmp/app/php/lib/php/extensions/no-debug-non-zts-20190902//tmp/app/newrelic/agent/x64/newrelic-20190902.so.so (/tmp/app/php/lib/php/extensions/no-debug-non-zts-20190902//tmp/app/newrelic/agent/x64/newrelic-20190902.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0`

I  manually download the package and extract it: The file newrelic-20190902.so is not part of the newrelic release

The file is part of the php5-9.14.0.290 release.

What did you expect to happen?
Newrelic is initialised and sending data

What was the actual behavior?

While initialising the buildpack it fails to load newrelic with following error
PHP Warning:  PHP Startup: Unable to load dynamic library '/tmp/app/newrelic/agent/x64/newrelic-20190902.so'

Questions:
- How can i overwrite the default version?

Please confirm where necessary:
* [x] I have included a log output
* [x] My log includes an error message
* [x] I have included steps for reproduction

**Comment by jschulthess** [comment]
Is there any progress on this issue?
Or is there a work-around, eg. a way to overwrite the default library version being loaded?

**Comment by dah0f** [comment]
No workaround from my side: I was hoping for an option to overwrite the default version as you said.

**Comment by jschulthess** [comment]
The NewRelic version in the plugin code comes from a Variable NEWRELIC_VERSION. Trying to find a way to pass this version in (eg. as "9.14.0.290") to override and force download of the current archive containing the missing library.
This would be a way to override. However, simply setting the variable doesn't seem to work.

**Comment by jschulthess** [comment]
I've created issue #422 with the request to bump up the NewRelic version.

**Comment by booooza** [comment]
Using https://github.com/cloudfoundry/php-buildpack.git#v4.4.33 New Relic seems to work again. :+1: 
Buildpack version 4.4.33 / Newrelic Version 9.14.0.290

**Comment by Tobion** [comment]
The issue can be closed given https://github.com/cloudfoundry/php-buildpack/commit/fcfd332d85acd2054d09700714853e1cd055c083
