### ISSUE TITLE
Non-OSS packages downloaded/installed without any choice from the end users?

### ISSUE THREAD

**Issue by gu-bin** [cloudfoundry/php-buildpack#427]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?
cf version 6.48.0+ca3deaa94.2019-12-04

What version of the buildpack you are using?
v4.4.20

Our legal department has some concern about two non-OSS packages downloaded/installed without any choice from the end users.

When end users run `cf push` with php-buildpack, the buildpack will download and install all the extensions including two non-OSS ones:
appdynamics-php-agent-linux_x64-20.4.0.3759.tar.bz2
CA-APM-PHPAgent-20.1.0_linux.tar.gz

The end users have no choice and may be even not aware of it. Would you please explain if this will cause legal problem with end users? Thanks.

**Comment by gu-bin** [comment]
After checking the php-buildpack code, it appears that the two packages will be downloaded and installed only when the specific services (with name "app[-]?dynamics" or "caapm") are bound to end user apps. So the license should be considered with the bound backend services, not the agent packages. If there are no such services (with name "app[-]?dynamics" or "caapm") provided, the end user apps will never download or install the packages.

Would you please confirm all the above are correct? Thanks.

**Comment by ForestEckhardt** [comment]
@gu-bin You are correct that those packages should only be installed if the user has a specific service. Hopefully this alleviates your concerns!
