### ISSUE TITLE
Reques to bump up newrelic plugin version

### ISSUE THREAD

**Issue by jschulthess** [cloudfoundry/php-buildpack#436]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?
6

What version of the buildpack you are using?
4.4.26

If you were attempting to accomplish a task, what was it you were attempting to do?
Same as issue #422 
1. Add NEWRELIC_LICENSE,
2. Buildpack detecs license and starts downloading the default version of newrelice (newrelic-php5-9.1.0.246-linux.tar.gz)
Downloaded [file:///tmp/buildpacks/649096e8ec6996024fe198c0f6eeaa41/dependencies/https___download.newrelic.com_php_agent_archive_9.1.0.246_newrelic-php5-9.1.0.246-linux.tar.gz] to [/tmp]
3. After installing it tries to load the .so files and fails:
PHP Warning:  PHP Startup: Unable to load dynamic library '/home/vcap/app/newrelic/agent/x64/newrelic-20190902.so' (tried: /home/vcap/app/newrelic/agent/x64/newrelic-20190902.so (/home/vcap/app/newrelic/agent/x64/newrelic-20190902.so: cannot open shared object file: No such file or directory), /home/vcap/app/php/lib/php/extensions/no-debug-non-zts-20190902//home/vcap/app/newrelic/agent/x64/newrelic-20190902.so.so (/home/vcap/app/php/lib/php/extensions/no-debug-non-zts-20190902//home/vcap/app/newrelic/agent/x64/newrelic-20190902.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0

What did you expect to happen?
Propper loading and working of newrelic agent

What was the actual behavior?
The agent downloaded (9.1.0.246) is missing the newer library newrelic-20190902.so required for the agent to work.

Version 9.14.0.290 of the NewRelic agent does contain the correct version.
I've tried to override the version (setting the NEWRELIC_VERSION) but this is ignored.

Can you please bump up the NewRelic version to 9.14.0.290!

Issue reference: https://github.com/cloudfoundry/php-buildpack/issues/422

Please confirm where necessary:
* [x] I have included a log output
* [x] My log includes an error message
* [x] I have included steps for reproduction

**Comment by jschulthess** [comment]
Is there anythink I can do to speed this up (bumping up the Newrelic version to at least 9.14.0.290)?

**Comment by Tobion** [comment]
The amqp extension is also missing for php 7.4.

> Downloaded [file:///tmp/buildpacks/990611246252e71235d25725818d4f3f/dependencies/https___buildpacks.cloudfoundry.org_dependencies_php_php7_7.4.13_linux_x64_cflinuxfs3_86b5e4fc.tgz] to [/tmp]
   __The extension 'amqp' is not provided by this buildpack.__
   Downloaded [file:///tmp/buildpacks/990611246252e71235d25725818d4f3f/dependencies/https___download.newrelic.com_php_agent_archive_9.14.0.290_newrelic-php5-9.14.0.290-linux.tar.gz] to [/tmp]
   Downloaded [file:///tmp/buildpacks/990611246252e71235d25725818d4f3f/dependencies/https___buildpacks.cloudfoundry.org_dependencies_php_php7_7.4.13_linux_x64_cflinuxfs3_86b5e4fc.tgz] to [/tmp]
   Downloaded [file:///tmp/buildpacks/990611246252e71235d25725818d4f3f/dependencies/https___buildpacks.cloudfoundry.org_dependencies_composer_composer_2.0.7_linux_noarch_any-stack_0a060e8c.phar] to [/tmp]
   Installing dependencies from lock file
   Verifying lock file contents can be installed on current platform.
   Your lock file does not contain a compatible set of packages. Please run composer update.
     Problem 1
       - Root composer.json requires PHP extension ext-amqp * but it is missing from your system. Install or enable PHP's amqp extension.

amqp ext is also not listed in php 7.4 on the buildpack releases page. But I don't see why it shouldn't be done. the amqp extension should be compatible with php 7.4, see https://github.com/php-amqp/php-amqp/pull/361

**Comment by fg-j** [comment]
cc @cloudfoundry/core-dependencies

**Comment by Tobion** [comment]
The amqp problem seems to be fixed with the latest version https://github.com/cloudfoundry/php-buildpack/releases/tag/v4.4.28
But the newrelic problem is still there.
