### ISSUE TITLE
I have big issue.

### ISSUE THREAD

**Issue by awesome1128** [cloudfoundry/php-buildpack#465]
When I run this command, I face error.
-run
ibmcloud cf push fixspeedcams -b https://github.com/cloudfoundry/php-buildpack.git

-error
Error staging application: App staging failed in the buildpack compile phase
FAILED

**Comment by arjun024** [comment]
Hi, I need more info (sample app, build logs etc.) to identify your issue. I'm going to close this issue for now but feel free to reopen with more helpful details.
