### ISSUE TITLE
composer self-update flag and more debug output

### ISSUE THREAD

**Issue by hairmare** [cloudfoundry/php-buildpack#47]
Hi Dan

I ran into a hairy issue pertaining to composer ``1.0.0-alpha9`` (lastest composer release as packaged by this buildpack) and version constraining (``>=0.13 <2`` vs. ``>=0.13,<2``).

These issues are long fixed in ``composer.phar`` that is based on ``1.0-dev`` and a not ([yet](https://github.com/composer/composer/issues/3779)) tagged release.

In debugging this, the following would have helped a lot:
* have composer output ``composer -V`` (version output) when ``BP_DEBUG`` is enabled
* an additional ``BP_COMPOSER_DEV: "True"`` env setting that runs ``composer self-update`` before doing much (the same setup i might have in a ``.travis.yml`` ``before_script`` depending on how modern my app is and if i've just been hit by some problems).

Sorry about not doing a PR, my python-fu is not strong enough and does not grok your style of (admittedly very nice) style of python coding. It's a pity as I am probably even under corporate CLA since I can sign commits as ``me@swisscom.com``.

Thanks for this great buildpack and cheers,
Lucas

**Comment by narcoticfresh** [comment]
I had also problems with a the caret operator (`"doctrine/instantiator": "^1.0.2"`) as used as a dependency in `phpspec/prophecy` - fails the same way. Hope update to `1.0-dev` (once tagged) will fix these as well..

**Comment by dmikusa-pivotal** [comment]
>These issues are long fixed in composer.phar that is based on 1.0-dev and a not (yet) tagged release.

Happy to pull in the latest Composer when it's tagged.  Will try to keep an eye out for it, but feel free to post an update here as a reminder when it's available.

>have composer output composer -V (version output) when BP_DEBUG is enabled

Sounds reasonable to me.

>an additional BP_COMPOSER_DEV: "True" env setting that runs composer self-update before doing much (the same setup i might have in a .travis.yml before_script depending on how modern my app is and if i've just been hit by some problems).

The build pack should include the latest stable version of Composer, so I'm not sure why this would be necessary unless you want to be able to roll back to an older version of Composer?  Can you explain your use case more?

Thanks

**Comment by hairmare** [comment]
> Happy to pull in the latest Composer when it's tagged. Will try to keep an eye out for it, but feel free to post an update here as a reminder when it's available.

Thanks, I'll keep that in mind.

> The build pack should include the latest stable version of Composer, so I'm not sure why this would be necessary unless you want to be able to roll back to an older version of Composer? Can you explain your use case more?

The use case was being able to pull in composer ``1.0-dev`` if/when there hasn't been a tagged release and any one of my vendors introduces a change that needs composer at its latest version.

This is only an issue since composer instructs its users to use ``1.0-dev`` by default, leading to a large amount of vendors relying on modern features. I've had this problem on travis-ci before, and there it is usually fixed by self-updating composer in a before_script.

**Comment by dmikusa-pivotal** [comment]
Interesting.  Let me look into self-update a bit more.  That might be possible as well.

**Comment by SocalNick** [comment]
+1 on being able to use a dev release of composer. Unfortunately, the documentation on https://getcomposer.org is based on master, not the latest tagged "stable" alpha release.

**Comment by dmikusa-pivotal** [comment]
I have committed a fix for this.  To use the latest dev release of composer, set COMPOSER_VERSION to `latest` (in `.bp-config/options.json`).  This will instruct the build pack to download the latest dev release of Composer, rather than the latest stable release.  It does this by simply downloading `https://getcomposer.org/composer.phar`, which always gives the latest dev release (this is basically what `composer self-update` does when run).

Because we have to pull in the latest dev release directly from the Composer web site, this will not work in offline mode.

**Comment by dmikusa-pivotal** [comment]
>have composer output composer -V (version output) when BP_DEBUG is enabled

This is also fixed now.  The build pack will run `composer -V` to dump the version in debug mode.
