### ISSUE TITLE
PHP Buildpack is still failing in multibuildpack environment due to old python2 code

### ISSUE THREAD

**Issue by sweettbug3** [cloudfoundry/php-buildpack#478]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?
+ eval cf curl /v2/info '&&' cf version
++ cf curl /v2/info
{
   "name": "VMware Tanzu Application Service",
   "build": "2.10.10-build.24",
   "support": "https://support.pivotal.io",
   "version": 0,
   "description": "https://docs.pivotal.io/pivotalcf/2-10/pcf-release-notes/runtime-rn.html",
   "min_cli_version": "6.23.0",
   "min_recommended_cli_version": "6.23.0",
   "app_ssh_oauth_client": "ssh-proxy",
   "api_version": "2.150.0",
   "osbapi_version": "2.15",
}
++ cf version
cf version 6.50.0+4f0c3a2ce.2020-03-03

What version of the buildpack you are using?
- php_buildpack-cached-cflinuxfs3-v4.4.27
- python_buildpack-cached-cflinuxfs3-v1.7.26

If you were attempting to accomplish a task, what was it you were attempting to do?
- Trying to bring up a suitecrm app with a manifest.yml with: 
`   buildpacks:
     - python_buildpack 
    - php_buildpack`

What did you expect to happen?
For the php buildpack scripts to work, and my app to deploy

What was the actual behavior?
instead they fail:
`  -------> Buildpack version 4.4.27
     File "/tmp/buildpacks/b1829161628f7a480de22cd7336394fc/scripts/compile.py", line 80
       print 'Finished: [%s]' % datetime.now()
             ^
   SyntaxError: invalid syntax
   Failed to compile droplet: Failed to run finalize script: exit status 1`

this is probably related to : https://github.com/cloudfoundry/php-buildpack/issues/323.  it seems this was closed because python2 would be around a while, well it isnt around in the newer python buildpacks

If I use python_buildpack_1_6_34 it doesnt fail. But python 1_6_34 buildpack wont be available for much longer in my environment, I should be able to use a new python_buildpack without it failing.

Please confirm where necessary:
* [x] I have included a log output
* [x] My log includes an error message
* [x] I have included steps for reproduction

**Comment by sweettbug3** [comment]
Same steps to reproduce as #323.

**Comment by ryanmoran** [comment]
I believe this should be resolved by https://github.com/cloudfoundry/php-buildpack/commit/959ac57a2405f7a34adb5ad59650cd6192c0ade0. This will be released in the next version of the buildpack, which should come out at some point this week.

**Comment by ryanmoran** [comment]
This was released in https://github.com/cloudfoundry/php-buildpack/releases/tag/v4.4.38. I'm going to close this for now. Please feel free to reopen this or another issue if you experience further problems.
