### ISSUE TITLE
some PROTIP goodness

### ISSUE THREAD

**Issue by hairmare** [cloudfoundry/php-buildpack#48]
This one is for the composer extension.

Could you add a ``PROTIP`` warning when people push a populated vendor dir in composer mode. It should tell users to add ``vendor/`` to their ``.cfignore``.

This makes it easier for a PHP-PaaS provider to do composer caching where it should be (in stage and on the network).

It might even make sense to add such a warning regardless of the composer extension for situations where a dev ``.cfignore``s the ``composer.*`` files.

**Comment by dmikusa-pivotal** [comment]
>Could you add a PROTIP warning when people push a populated vendor dir in composer mode. It should tell users to add vendor/ to their .cfignore.

I understand what you're saying here, but a use case that we want to support is for a user to be able to include a vendor directory and not require Composer to hit the internet.  If we tell users not to include a vendor directory, it really goes against what is a supported use case.

If this is something that you'd like to implement in your particular environment, you could fork the build pack for your users and add a custom extension to it.  If the extension sees a vendor directory, you could spit out this message or even return an error and prevent it (depending on how strict you want to be).

Not sure we'd want this to be the default behavior though.

**Comment by hairmare** [comment]
I hadn't thought about the offline use case. In my case pushing a vendor is currently considered an anti-pattern just like pushing without a composer.lock. I probably won't be enforcing this, I'd rather just re-run composer install and maybe throw an error on continuous integration if the lockfile is outdated.

Thanks for the feedback.
