### ISSUE TITLE
Please add pthreads and protobuf support in buildpack

### ISSUE THREAD

**Issue by libnux** [cloudfoundry/php-buildpack#50]
We're using the extensions of pthread and protobuf in our php applications, and planning to run it in CF. 
But seems that they are not included in current php buildpack. 

Could you please add support for these two extensions? 
The latest versions are OK. Thanks.

pthread: http://php.net/manual/en/pthreads.installation.php
protobuf: https://github.com/allegro/php-protobuf/

**Comment by dmikusa-pivotal** [comment]
Hello.  I don't know that we can support pthread at this time.  From the docs, it says...

>pthreads requires a build of PHP with ZTS (Zend Thread Safety) enabled ( --enable-maintainer-zts or --enable-zts on Windows )

and we don't presently build PHP with ZTS.  It may be something we could add in the future, given enough demand.  At the present, if you need this I'd suggest building your own PHP binaries.  See [here](https://github.com/dmikusa-pivotal/cf-php-buildpack-binary-build-scripts/), which is the automated build system that we use.  Instructions on it's usage are in the readme.  More on using your own binaries can be found [here](https://github.com/cloudfoundry/php-buildpack/blob/master/docs/binaries.md).

Looks like php-protobuf should be no problem.  Adding that now.  Will let you know when something is available to test.

**Comment by dmikusa-pivotal** [comment]
Ok.  I've added the [php-protobuf](https://github.com/allegro/php-protobuf/) and [protocolbuffers](http://pecl.php.net/package/protocolbuffers) extensions.  Should be available starting with PHP 5.4.38, 5.5.22 and 5.6.6.

Let me know if you see any issues.

**Comment by libnux** [comment]
I'll report if any issue with protobuf. Thanks a lot. 

I'll build my own binaries for pthreads support.

**Comment by ninifi** [comment]
Hi,

This issue has been created to add pthread as well but it was not included because it requires a build of PHP with ZTS.
Are there currently any plans to support that soon?

Thanks

**Comment by dmikusa-pivotal** [comment]
@ninifi No, no plans to add official builds that include ZTS support. You can use the instructions I linked to above though and you can build your own.

Also, as a future note. With Cloud Native Buildpacks it will get easier to bring your own PHP binaries.

**Comment by ninifi** [comment]
@dmikusa-pivotal okay, thanks for the info.
