### ISSUE TITLE
IMPORTANT NOTICE: [php-buildpack] Change of default nginx version after 2021-07-09

### ISSUE THREAD

**Issue by arjun024** [cloudfoundry/php-buildpack#502]
The default version for NGINX will be updated to 1.21.x in the first release of the PHP buildpack after 2021-07-09.

We are giving a 30 day notice to inform users that the default version of NGINX in the PHP buildpack will be updated to the latest 1.21.x version in the first release of the PHP buildpack after 2021-07-09.

If you’d like to use a different NGINX version, please configure your application to select that version.[1]

As always, the buildpacks team is happy to answer questions you may have about this deprecation in the #buildpacks Slack channel[2].

[1] - https://docs.cloudfoundry.org/buildpacks/php/gsg-php-config.html
[2] - https://cloudfoundry.slack.com/archives/C02HWMDUQ

Thanks,
The Buildpacks Team

**Comment by shanks3012** [comment]
We have updated the default version earlier than the proposed timeline due to a need to remove version lines that were affected by a critical CVE. Closing the issue
