### ISSUE TITLE
IMPORTANT NOTICE: Removal of nginx versions 1.18.x and 1.19.x effective immediately

### ISSUE THREAD

**Issue by shanks3012** [cloudfoundry/php-buildpack#511]
Previously, a 30 day notice was sent alerting users of the php buildpack that nginx versions 1.18.x and 1.19.x would be removed in July, 2021. It has been recognized that version lines older than 1.20.x of nginx contain a critical CVE and thus, the affected version lines will be removed in the next release of the php buildpack; earlier than previously stated.

Additionally, the default version of nginx will become 1.21.x in the next release. We do not anticipate your application to incur breaking changes, but please be ready to ensure your php applications are configured to run with the latest nginx versions.

Thanks,
Buildpacks Team

**Comment by sophiewigmore** [comment]
Closing out this issue since NGINX 1.18 and 1.19 were removed in [PHP buildpack v4.4.43](https://github.com/cloudfoundry/php-buildpack/releases/tag/v4.4.43), and we are now at v4.4.48.
