### ISSUE TITLE
amqp extension missing in php-buildpack for php 8.x

### ISSUE THREAD

**Issue by jlnfsslr** [cloudfoundry/php-buildpack#520]
What version of the buildpack you are using?
php-buildpack-cflinuxfs3-v4.4.43 with PHP 8.0.x
https://github.com/cloudfoundry/php-buildpack/releases/tag/v4.4.43

If you were attempting to accomplish a task, what was it you were attempting to do?
Use the PHP extension `amqp` with the PHP 8.0.7 buildpack

What did you expect to happen?
The PHP extension `amqp` should be included as with the previous PHP 7.x buildpacks.

What was the actual behavior?
The PHP extension `amqp` is not included in the PHP 8.0.x buildpacks, see https://github.com/cloudfoundry/php-buildpack/releases/tag/v4.4.43 .
Message: **The extension 'amqp' is not provided by this buildpack.**

**Comment by jlnfsslr** [comment]
.. as I see the `amqp` extension has not a stable release yet for PHP 8. It would be nice if it could be integrated once a stable release is available

**Comment by menehune23** [comment]
Hi @jlnfsslr, as our development focus has shifted mostly to the newer [Paketo PHP buildpack](https://github.com/paketo-buildpacks/php), my recommendation would be to fork this repo to include any customizations like this. You might also try out the newer buildpack, though it is heavily container-focused, being part of the new buildpacks standard (https://buildpacks.io).

I'm going to close this for now, but feel free to reopen if you'd like to continue the conversation.

**Comment by mjanser** [comment]
There is a stable release of amqp 1.11.0 now for PHP 8.0 and 8.1. Will this be included in this buildpack soon?

**Comment by menehune23** [comment]
We'll take a look soon and see about including it. Thanks for the notification!

**Comment by brayanhenao** [comment]
Hi @mjanser @jlnfsslr,

We just released the PHP Buildpack [v4.4.55](https://github.com/cloudfoundry/php-buildpack/releases/tag/v4.4.55). This version adds the `amqp` extension for PHP 8.0

**Comment by jlnfsslr** [comment]
@brayanhenao 

Thanks a lot for your efforts and the information about the new release :). We're happy to see the `amqp` in the PHP 8.0 buildpacks, so we can now start upgrading some of our apps to PHP 8.0.

All the best
Julian
