### ISSUE TITLE
Just wondering if you have any plans of integrating elastic apm agent inside php-buildpack

### ISSUE THREAD

**Issue by clgx-pbogdan** [cloudfoundry/php-buildpack#536]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?
6.53.0

What version of the buildpack you are using?
Any php-buildpack

If you were attempting to accomplish a task, what was it you were attempting to do?
We're trying to deploying PHP application into PCF and additionally, we need to deploy elastic-apm agent in PCF

What did you expect to happen?
Ideally, elastic-apm-agent deploys along with php-buildback, and at the end, I am able to send metrics to Elasticsearch.
At the moment I need to download separately elastic-apm agent, unpack it and deploy it somehow to PCF.
It works perfectly with Java buildpack and I'm just wondering if there is any chance to integrate elastic apm agent inside php-buildpack in future releases?

Link to elastic APM agent -  https://www.elastic.co/guide/en/apm/agent/php/current/setup.html

**Comment by menehune23** [comment]
Hi @clgx-pbogdan, thanks for reaching out. I don't believe this is on the roadmap for this particular buildpack (@shanks3012, correct me if I'm wrong), as most new development is focused on the newer [Paketo PHP buildpack](https://github.com/paketo-buildpacks/php). That said, we'd happily take a look at a PR if you're interested in having it implemented here.

Feel free to reopen if this doesn't answer your question.
