### ISSUE TITLE
Missing imagick extension with php8

### ISSUE THREAD

**Issue by rugolinifr** [cloudfoundry/php-buildpack#554]
What version of the buildpack you are using?
 - v4.4.47

If you were attempting to accomplish a task, what was it you were attempting to do?
 - execute `cf push` to an app with `extension=imagick.so` and `php=8.0.*`

What did you expect to happen?
 - to successfully deploy the app

What was the actual behavior?
- the deployment failed, because the `imagick` extension is missing from the buildpack (`php 8`, not `php 7`)

As discussed on slack, the `imagick` extension wasn't supported with `php 8` when it was released.
But, the  `imagick` [v3.50.0](https://stackoverflow.com/questions/tagged/api-platform.com) introduced support for php8 since 2021-06-17.

Can someone look at adding this extension to the next buildpack release please ?

Thanks

**Comment by sophiewigmore** [comment]
@rugolinifr PHP 8.0.11 has been recompiled to include imagick. It will be available in the next release of the PHP buildpack (4.4.48).
