### ISSUE TITLE
Add support for WEBP images

### ISSUE THREAD

**Issue by pixelbrackets** [cloudfoundry/php-buildpack#560]
*System information*

- Cloud Foundry CLI 7.3.0
- Buildpack version 4.4.48
- PHP 7.4.23

*If you were attempting to accomplish a task, what was it you were attempting to do?*

- Convert existing images into WEBP format

*What did you expect to happen?*

- PHP May use a graphics software to modify images, e.g. ImageMagick
- ImageMagick supports WEBP converters
- A WEBP converter is installed
- ImageMagick converts `test.jpg` into `test1.webp`

*What was the actual behavior?*

- ImageMagick is installed - Version 6.9.7
- ImageMagick supports WEBP
  `convert -list delegate | grep webp` → `png <= webp   webp =>`
- WEBP is not installed `cwebp -version`→ `cwebp: not found`
- An error occurs during image conversion `convert -quality 100 test.jpg test1.webp` → `convert-im6.q16: delegate failed `'cwebp' -quiet %Q '%i' -o '%o'' @ error/delegate.c/InvokeDelegate/1919.`

_Please confirm where necessary:_

* [x] I have included a log output
* [x] My log includes an error message
* [x] I have included steps for reproduction

**Comment by menehune23** [comment]
Hi @pixelbrackets, thanks for contributing this and for doing some investigation on your own. I can't make any guarantees, but I'll add this to our backlog to discuss.
