### ISSUE TITLE
Update to latest AppDynamics sidecar which uses Log4j 2.17

### ISSUE THREAD

**Issue by coobr01** [cloudfoundry/php-buildpack#577]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?

  /v3 of the api
  cf version 7.3.0+645c3ce6a.2021-08-16

What version of the buildpack you are using?

   PHP Buildpack 4.4.53

Question

   Will another release be published soon with the updated AppDynamics agent in it that would use Log4j 2.17? Looks like release 4.4.53 is still using Log4j 2.16.

**Comment by cth18012017** [comment]
Hello i hope you can fix it with the new update for log4j=2.17.

**Comment by cth18012017** [comment]
Please Update httpd 2.4.52 to

**Comment by brayanhenao** [comment]
@coobr01 @cth18012017 

We just release PHP Buildpack [v4.4.54](https://github.com/cloudfoundry/php-buildpack/releases/tag/v4.4.54) that contains the `AppDynamics PHP Agent v21.12.2.13` which uses Log4j 2.17
