### ISSUE TITLE
upgrading from 3.0.3 to 3.0.4

### ISSUE THREAD

**Issue by clement360** [cloudfoundry/php-buildpack#58]
I want to upgrade the buildpack to vs 3.1.0 but I had too many issues upgrading 3.0.3 to 3.0.4 Essentially I am deploying wordpress on bluemix installing everything through composer. The app stages with all the files in the right place, but when I try to connect I get 503 errors.

**Comment by clement360** [comment]
New issue, I can't get past buildpack compile now. LOGS:

OUT -----> Downloaded app package (4.0K)
OUT -----> Downloaded app buildpack cache (38M)
ERR Cloning into '/tmp/buildpacks/php-buildpack'...
ERR Note: checking out 'e632ce5492ebbc2c9a2493872b6a4ad5eeac8312'.
ERR You are in 'detached HEAD' state. You can look around, make experimental
ERR changes and commit them, and you can discard any commits you make in this
ERR state without impacting any branches by performing another checkout.
ERR If you want to create a new branch to retain commits you create, you may
ERR do so (now or later) by using -b with the checkout command again. Example:
ERR   git checkout -b new_branch_name
OUT -------> Buildpack version 3.1.0
OUT Installing HTTPD
OUT Downloaded [https://pivotal-buildpacks.s3.amazonaws.com/php/binaries/lucid/httpd/2.4.12/httpd-2.4.12.tar.gz] to [/tmp/httpd-2.4.12.tar.gz]
		
	------------------------------------ LOTS OF INSTALLS HERE ------------------------------------

OUT Downloaded [https://pivotal-buildpacks.s3.amazonaws.com/php/binaries/lucid/composer/1.0.0-alpha9/composer.phar] to [/tmp/composer.phar]
OUT PROTIP: Include a `composer.lock` file with your application! This will make sure the exact same version of dependencies are used when you deploy to CloudFoundry.
OUT Loading composer repositories with package information
Installing dependencies
ERR   [RuntimeException]
ERR   Could not load package zendframework/zendframework in http://packagist.org: [UnexpectedValueException] Could not parse version constraint ^1.0: Invalid version string "^1.0"
ERR   [UnexpectedValueException]
ERR   Could not parse version constraint ^1.0: Invalid version string "^1.0"
ERR install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-plugins] [--no-custom-installers] [--no-scripts] [--no-progress] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [--ignore-platform-reqs] [packages1] ... [packagesN]
ERR Traceback (most recent call last):
ERR   File "/tmp/buildpacks/php-buildpack/scripts/compile.py", line 51, in <module>
ERR     .from_build_pack('lib/additional_commands')
ERR   File "/tmp/buildpacks/php-buildpack/lib/build_pack_utils/builder.py", line 189, in extensions
OUT -----> Composer command failed
ERR     process_extension(path, ctx, 'compile', process, args=[self])
ERR   File "/tmp/buildpacks/php-buildpack/lib/build_pack_utils/utils.py", line 69, in process_extension
ERR     success(getattr(extn, to_call)(*args))
ERR   File "/tmp/buildpacks/php-buildpack/extensions/composer/extension.py", line 359, in compile
ERR     return composer.compile(install)
ERR   File "/tmp/buildpacks/php-buildpack/lib/extension_helpers.py", line 154, in compile
ERR     self._compile(install)
ERR   File "/tmp/buildpacks/php-buildpack/extensions/composer/extension.py", line 162, in _compile
ERR     self.run()
ERR   File "/tmp/buildpacks/php-buildpack/extensions/composer/extension.py", line 244, in run
ERR     *self._ctx['COMPOSER_INSTALL_OPTIONS'])
ERR   File "/tmp/buildpacks/php-buildpack/extensions/composer/extension.py", line 289, in run
ERR     shell=True)
ERR   File "/tmp/buildpacks/php-buildpack/lib/build_pack_utils/runner.py", line 109, in stream_output
ERR     raise CalledProcessError(retcode, cmd)
ERR build_pack_utils.runner.CalledProcessError: Command '<open file '<fdopen>', mode 'w' at 0x28634b0>' returned non-zero exit status 1
OUT Staging failed: Buildpack compilation step failed
2015-03-26T17:16:01.16-0400 [API/0]      ERR Encountered error: App staging failed in the buildpack compile phase

**Comment by clement360** [comment]
The Logs from pushing with v3.0.3:

OUT -----> Downloaded app package (4.0K)
OUT -----> Downloaded app buildpack cache (38M)
ERR Cloning into '/tmp/buildpacks/php-buildpack'...
ERR Note: checking out 'f5b0b7818e313ed03e058d8126ceafc966a9c1df'.
ERR You are in 'detached HEAD' state. You can look around, make experimental
ERR changes and commit them, and you can discard any commits you make in this
ERR state without impacting any branches by performing another checkout.
ERR If you want to create a new branch to retain commits you create, you may
ERR do so (now or later) by using -b with the checkout command again. Example:
ERR   git checkout -b new_branch_name
OUT -------> Buildpack version 3.0.3
OUT Installing HTTPD
OUT Installing PHP
OUT PHP 5.4.36
OUT PROTIP: Include a `composer.lock` file with your application! This will make sure the exact same version of dependencies are used when you deploy to CloudFoundry.
OUT   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
OUT                                  Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0{
OUT   "resources": {
OUT     "core": {
OUT       "limit": 60,
OUT       "remaining": 60,
OUT       "reset": 1427407784
OUT     },
OUT     "search": {
OUT       "limit": 10,
OUT       "remaining": 10,
OUT       "reset": 1427404244
OUT     }
OUT   },
OUT   "rate": {
OUT     "limit": 60,
OUT     "remaining": 60,
OUT     "reset": 1427407784
OUT   }
OUT }
141   283  141   283    0     0   1573      0 --:--:-- --:--:-- --:--:--  7447
OUT Loading composer repositories with package information
Installing dependencies
ERR   [RuntimeException]
ERR   Could not load package zendframework/zendframework in http://packagist.org: [UnexpectedValueException] Could not parse version constraint ^1.0: Invalid version string "^1.0"
ERR   [UnexpectedValueException]
ERR   Could not parse version constraint ^1.0: Invalid version string "^1.0"
ERR install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-plugins] [--no-custom-installers] [--no-scripts] [--no-progress] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader]
OUT Finished: [2015-03-26 21:10:31.816581]
OUT -----> Uploading droplet (22M)
OUT Starting app instance (index 0) with guid 3f9d9aa2-3c1c-4fca-a316-a1a8cc1c900d
OUT 21:11:04 php-fpm-logs | tail: cannot open `/home/vcap/app/logs/php-fpm.log' for reading: No such file or directory
OUT 21:11:04 httpd        | [Thu Mar 26 21:11:04.926609 2015] [mpm_event:notice] [pid 39:tid 140238225585920] AH00489: Apache/2.4.10 (Unix) configured -- resuming normal operations
OUT 21:11:04 httpd        | [Thu Mar 26 21:11:04.926842 2015] [mpm_event:info] [pid 39:tid 140238225585920] AH00490: Server built: Feb 20 2015 17:01:31
OUT 21:11:04 httpd        | [Thu Mar 26 21:11:04.926868 2015] [core:notice] [pid 39:tid 140238225585920] AH00094: Command line: '/home/vcap/app/httpd/bin/httpd -f /home/vcap/app/httpd/conf/httpd.conf -D FOREGROUND'
OUT 21:11:05 php-fpm-logs | tail: `/home/vcap/app/logs/php-fpm.log' has appeared;  following end of new file
OUT 21:11:06 php-fpm-logs | [26-Mar-2015 21:11:04] NOTICE: fpm is running, pid 40
OUT 21:11:06 php-fpm-logs | [26-Mar-2015 21:11:04] NOTICE: ready to handle connections

I know the "^1.0" version string error is from having an out of date composer. and is the reason I need to update.

**Comment by dmikusa-pivotal** [comment]
Here's what I'd suggest.

1.) Deploy with v3.1.0.  This is the latest stable release.
2.) Edit your manifest file and add the environment variable BP_DEBUG.  Set it to "True".
3.) Push your code to a new application (i.e. give it a new name).  Capture the full output of `cf push`.  It will be a lot.  Post it here (please use triple back ticks so formatting is OK) or in a gist.
4.) Access your app and run `cf logs --recent <app>`.  Capture everything.  Again, post here or in a gist.

**IMPORTANT** Read through the debug logs and make sure it's not listing any private information or service credentials before you post!! The debug logs dump a lot of info and it's not automatically sanitized. **IMPORTANT**

One other thing, since you mentioned a 503.  If you have a customized HTTPD configuration in `.bp-config/httpd`.  You might want to try pushing without it.  We made changes a while back to make the default configuration better.  It's likely that you don't need this anymore.

Alternatively, send me a link to your app and I'll see if I can replicate the problem.

**Comment by jtarchie** [comment]
The buildpack became part of the `cf-release` we've been updating to support the buildpack package system.

@clement360 it looks like you are trying to use a newer feature of of `composer`. With the package system, we had to version lock to a version of `composer` that does not support that feature `^`.

Are you able to use an alternative version resolver, until composer get's bumped in the buildpack?

JT

**Comment by clement360** [comment]
Ok I'm getting the logs currently, I set BP_DEBUG using cf set-env APPNAME BP_DEBUG true.

As far as using another version string goes. I would really like to but it is in one of the zendframework dependencies, and I cannot find it, I've searched for quite a while.

also I do have a httpd-php.conf file: 
```
RewriteEngine on

<Directory "${HOME}/htdocs/">
Options +FollowSymLinks
RewriteBase /
RewriteRule ^index\.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.php [L]
</Directory>

# Proxy requests to /**/*.php
RewriteCond %{LA-U:REQUEST_FILENAME} -f
RewriteRule ^/(.*\.php)$ unix:#{PHP_FPM_LISTEN}|fcgi://localhost${HOME}/#{WEBDIR}/$1 [P,L]

# Proxy requests for folders, if an index.html file doesn't exist,
# to /**/index.php
RewriteCond %{LA-U:REQUEST_FILENAME} -d
RewriteCond %{LA-U:REQUEST_FILENAME}index.html !-f
RewriteCond %{LA-U:REQUEST_FILENAME}index.php -f
RewriteRule ^/(.*)$ unix:#{PHP_FPM_LISTEN}|fcgi://localhost${HOME}/#{WEBDIR}/$1index.php [P,L]

# Fix folder redirects, i.e. from /folder to /folder/
RewriteCond %{LA-U:REQUEST_FILENAME} -d
RewriteCond %{HTTP:x-forwarded-proto} =https
RewriteRule ^(.*[^/])$ https://%{SERVER_NAME}$1/ [R,L]
RewriteCond %{LA-U:REQUEST_FILENAME} -d
RewriteCond %{HTTP:x-forwarded-proto} !=https
RewriteRule ^(.*[^/])$ http://%{SERVER_NAME}$1/ [R,L]
```

**Comment by clement360** [comment]
https://gist.github.com/clement360/33e7aaa5c5250f888a8a

**Comment by clement360** [comment]
Solved buildpack compile issue by adding "COMPOSER_VERSION": "latest" to options.json

I'll try blowing away the httpd conf files now

**Comment by clement360** [comment]
That Worked! Thank you so much. I'll take down the top half of that log though, I'm a little worried about confidentiality
