### ISSUE TITLE
AppDynamics 21.12.4

### ISSUE THREAD

**Issue by cth18012017** [cloudfoundry/php-buildpack#583]
Hello, please update to AppDynamics 21.12.4 or grater with Log4J 2.17.1.

**Comment by brayanhenao** [comment]
> Hello, please update to AppDynamics 21.12.4 or grater with Log4J 2.17.1.

The PHP agent that this Buildpack uses currently doesn't have v21.12.4 released yet with Log4J 2.17.1. 

As soon as AppDynamics releases the fix we will put it in the Buildpack.

**Comment by cth18012017** [comment]
Hello,
there are postive news?

**Comment by brayanhenao** [comment]
Hi @cth18012017.

AppDynamics released the `PHP Agent v22.1.0` with `Log4J v2.17.1`. We are working on including this change in the Buildpack as soon as possible. 

A new release of PHP Buildpack is expected before the end of the week.

**Comment by brayanhenao** [comment]
Hi @cth18012017,

We just released the PHP Buildpack [v4.4.55](https://github.com/cloudfoundry/php-buildpack/releases/tag/v4.4.55). This version contains the `AppDynamics PHP Agent v22.1.0` which contains `Log4J v2.17.1`
