### ISSUE TITLE
New Relic extension incompatible with php 8

### ISSUE THREAD

**Issue by booooza** [cloudfoundry/php-buildpack#594]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?
cf api 2.174.0
cf cli 7.4.0

What version of the buildpack you are using?
buildpack 4.4.53
newrelic 9.14.0.290
php 8.0.13

If you were attempting to accomplish a task, what was it you were attempting to do?
Deploy an app with php-buildpack v4.4.53, php 8.0.13 and `NEWRELIC_LICENSE` env var set.

What did you expect to happen?
New Relic agent will be installed

What was the actual behavior?
The installed New Relic agent seems to be incompatible with php 8.
https://docs.newrelic.com/whats-new/2021/04/php-agent/
https://github.com/newrelic/newrelic-php-agent/releases/tag/v9.17.0.300

```
   Installing PHP
   PHP 8.0.13
   Downloaded [https://buildpacks.cloudfoundry.org/dependencies/php/php_8.0.13_linux_x64_cflinuxfs3_44302e97.tgz] to [/tmp]
   Downloaded [https://download.newrelic.com/php_agent/archive/9.14.0.290/newrelic-php5-9.14.0.290-linux.tar.gz] to [/tmp]
   Downloaded [https://buildpacks.cloudfoundry.org/dependencies/php/php_8.0.13_linux_x64_cflinuxfs3_44302e97.tgz] to [/tmp]
   Downloaded [https://buildpacks.cloudfoundry.org/dependencies/composer/composer_2.1.14_linux_noarch_any-stack_d44a9045.phar] to [/tmp]
     % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                    Dload  Upload   Total   Spent    Left  Speed
     0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
   100   714  100   714    0     0  11704      0 --:--:-- --:--:-- --:--:-- 11704
   PHP Warning:  PHP Startup: Unable to load dynamic library '/tmp/app/newrelic/agent/x64/newrelic-20200930.so' (tried: /tmp/app/newrelic/agent/x64/newrelic-20200930.so (/tmp/app/newrelic/agent/x64/newrelic-20200930.so: cannot open shared object file: No such file or directory), /tmp/app/php/lib/php/extensions/no-debug-non-zts-20200930//tmp/app/newrelic/agent/x64/newrelic-20200930.so.so (/tmp/app/php/lib/php/extensions/no-debug-non-zts-20200930//tmp/app/newrelic/agent/x64/newrelic-20200930.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
```

Please confirm where necessary:
* [x ] I have included a log output
* [x ] My log includes an error message
* [ x] I have included steps for reproduction

**Comment by arjun024** [comment]
Thanks for filing the issue. We'll looking into this and get newrelic updated
