### ISSUE TITLE
Question for EOL for php 7.4 with this buildpack

### ISSUE THREAD

**Issue by SamCrudge** [cloudfoundry/php-buildpack#636]
What version of the buildpack you are using?
v4.4.59

If you were attempting to accomplish a task, what was it you were attempting to do?
Understand EOL of 7.4 with this buildpacl

Any info on this would be great ta

**Comment by arjun024** [comment]
The buildpack follows the same timeline as of PHP official releases https://www.php.net/supported-versions.php
