### ISSUE TITLE
composer update

### ISSUE THREAD

**Issue by hairmare** [cloudfoundry/php-buildpack#64]
The ``1.0.0-alpha10`` version of composer has finally been tagged (see composer/composer#3779) and the buildpack should be updated to include this new version.

I might do a PR later this week, not sure if i'll find the time though. The release is important due to it including support for the caret operator in semver specs. This problem has been wreaking havoc throughout the community and is also the reason people were using the COMPOSER_VERSION = latest feature.

**Comment by flavorjones** [comment]
Hi @hairmare,

Thanks for opening this ticket! No need for a PR, we'll take care of it this week -- we've been making big changes to the `manifest.yml` file for the "skinny buildpacks" track of work (I emailed vcap-dev@ about this work last week), so any PR may not apply cleanly to `develop` by the time we get to it.

Thanks again!

**Comment by hairmare** [comment]
I just saw 9df60fc37bcc5745576bdd1158762acf64dcb1a1.

Thanks
