### ISSUE TITLE
Buildpack Stopped Building on dependency resolution

### ISSUE THREAD

**Issue by aryanet** [cloudfoundry/php-buildpack#686]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?

cf version 6.53.0+8e2b70a4a.2020-10-01

What version of the buildpack you are using?

4.4.2
and 
4.4.64

If you were attempting to accomplish a task, what was it you were attempting to do?

cf push of an existing app

What did you expect to happen?

deploy to finish successfully

What was the actual behavior?

It keeps failing on staging

Staging app and tracing logs...
   Cell 98ee4547-5349-444e-a5df-9573781cdf99 creating container for instance ad131ec9-0b07-4c76-91ac-c910a3bba9fc
   Cell 98ee4547-5349-444e-a5df-9573781cdf99 successfully created container for instance ad131ec9-0b07-4c76-91ac-c910a3bba9fc
   Downloading app package...
   Downloading build artifacts cache...
   Downloaded app package (2.1M)
   Downloaded build artifacts cache (103.4M)
   -------> Buildpack version 4.4.64
   WARNING: buildpack version changed from 4.4.2 to 4.4.64
   No Web Server is being installed.
   WARNING: A version of PHP has been specified in both `composer.json` and `./bp-config/options.json`.
   WARNING: The version defined in `composer.json` will be used.
   Warning: PHP_EXTENSIONS in options.json is deprecated. See: http://docs.cloudfoundry.org/buildpacks/php/gsg-php-config.html
   Installing PHP
   PHP 7.4.30
   Downloaded [https://buildpacks.cloudfoundry.org/dependencies/php/php_7.4.30_linux_x64_cflinuxfs3_2425db05.tgz] to [/tmp]
   The extension 'mcrypt' is not provided by this buildpack.
   Downloaded [https://buildpacks.cloudfoundry.org/dependencies/php/php_7.4.30_linux_x64_cflinuxfs3_2425db05.tgz] to [/tmp]
   Downloaded [https://getcomposer.org/composer.phar] to [/tmp/composer.phar]
   PROTIP: Include a `composer.lock` file with your application! This will make sure the exact same version of dependencies are used when you deploy to CloudFoundry.
     % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                    Dload  Upload   Total   Spent    Left  Speed
     0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
   100   714  100   714    0     0  18307      0 --:--:-- --:--:-- --:--:-- 18307
   No composer.lock file present. Updating dependencies to latest instead of installing from lock file. See https://getcomposer.org/install for more information.
   Loading composer repositories with package information
   Info from https://repo.packagist.org: #StandWithUkraine
Error staging application: App staging failed in the buildpack compile phase
FAILED

Please confirm where necessary:
* [X] I have included a log output
* [X] My log includes an error message
* [X] I have included steps for reproduction
[buildpack_issue.txt](https://github.com/cloudfoundry/php-buildpack/files/9203748/buildpack_issue.txt)

**Comment by aryanet** [comment]
Just a note that this is a continuous pipeline that has always built fine with 4.4.2. The error message with composer.lock is bogus as composer.lock exists. We always get this error on all of our builds event the successful ones, so I doubt if that is the issue. My hunch is that something is wrong with PHP repo, but I am not sure how to show troubleshooting information for that. Any tips would be appreciated.

**Comment by arjun024** [comment]
Can you see if `cf logs <app> --recent` have any more information?
Would it be possible to provide an example app?
