### ISSUE TITLE
Add binaries for PHP 5.4.40, 5.4.41, 5.5.24, 5.5.25, 5.6.8 and 5.6.9

### ISSUE THREAD

**Issue by dmikusa-pivotal** [cloudfoundry/php-buildpack#71]
5.4.40 - released on 4/16/15
5.4.41 - released on 5/14/15

5.5.24 - released on 4/16/15
5.5.25 - released on 5/14/15

5.6.8 - released on 4/16/15
5.6.9 - released on 5/14/15

**Comment by flavorjones** [comment]
Yes, we should absolutely update the packaged versions.

I'd like to avoid having two consecutive buildpack releases having mutually-exclusive versions, though, to avoid upgrade hell. By that I mean that a strict "two patch versions" policy would mean we drop 5.4.38 and 5.4.39 at the same time we add 5.4.40 and 5.4.41, meaning that any existing apps would need to synchronize their upgrade with the buildpack upgrade. I'd rather allow and encourage proactive version upgrades by keeping one version from the current release in the next release.

To that end, I'd like to specify that when we package these releases, that we include:

* 5.4.39, 40, 41
* 5.5.23, 24, 25
* 5.6.7, 8, 9

Make sense?

**Comment by crawsible** [comment]
@flavorjones Might be a bit unorthodox, but why provide 5.4.40, 5.5.24, or 5.6.8 at all? If the objective is to encourage users to use the latest teeny version without breaking their existing apps, then those three don't serve either purpose.

**Comment by flavorjones** [comment]
See updates to the tracker story, as well as this related story: https://www.pivotaltracker.com/story/show/94988124

**Comment by flavorjones** [comment]
This is updated on the `develop` branch and will be released shortly.
