### ISSUE TITLE
PHP Build Pack that supports NewRelic monitoring needed

### ISSUE THREAD

**Issue by bluethundr** [cloudfoundry/php-buildpack#72]
Hello,

 The majority of applications we run in our large environment are PHP based. In the current environment we use both NewRelic and AppDynamics monitoring to monitor those sites. So we'll need to support both in our new Pivotal environment.

 We already have an issue open to have a buildpack created that supports both PHP and AppDynamics. 

  You can find the AppD PHP buildpack request here:

 https://github.com/cloudfoundry/php-buildpack/issues/69

We'd appreciate it if you could get the ball rolling to have a PHP based NewRelic buildpack created as well!! 

Both app monitoring systems are very important to our organization.

**Comment by flavorjones** [comment]
Hi,

NewRelic is already available in PHP buildpacks 3.1.1, 3.2.0 and 3.2.1.

Are you running into a particular problem using NewRelic? If so, can you help me reproduce your issue?

Thanks,
-mike

**Comment by bluethundr** [comment]
Hi, 

 No, sorry! I was told that there is only Java support in the buildpacks. 

Could you link me to the PHP buildpacks with NewRelic?

Thanks

**Comment by flavorjones** [comment]
Hi,

You can download a PHP buildpack that supports NewRelic from here:

* https://github.com/cloudfoundry/php-buildpack/releases

Please note that my previous comment was wrong; we've supported NewRelic in the PHP buildpack for as far back as I know how to check (at least as far back as v2.0.0).

Thanks for using Cloud Foundry!

**Comment by flavorjones** [comment]
Also worth noting is that CF docs indicate NewRelic support here:

* http://docs.cloudfoundry.org/buildpacks/php/gsg-php-config.html#buildpack-extensions

Thanks again!
