### ISSUE TITLE
NewRelic Docs

### ISSUE THREAD

**Issue by dmikusa-pivotal** [cloudfoundry/php-buildpack#73]
I thought there were docs for using NewRelic w/ the PHP build pack, but I was searching today and couldn't find them.  Sorry if I missed it.

For the record, here's what's currently supported.

1.) Bind a NewRelic service to the app, the build pack will automatically see this and it'll setup NewRelic.  The only place I've tested this is on PWS.  It should generally work as long as the VCAP_SERVICES environment variable contains a service called `newrelic`, that service dict has a key called `credentials` and that in turn has a key called `licenseKey`.  It won't currently work with user provided services.

2.) Set the environment variable `NEWRELIC_LICENSE`, either through the manifest.yml file or with `cf set-env`.  The value of this should contain your NR license key.  If the user has any existing account with NewRelic (i.e. one created outside of CF), then this is the way to go.

**Comment by Dannyzen** [comment]
Added in https://github.com/cloudfoundry/docs-buildpacks/pull/28
