### ISSUE TITLE
Cannot stage PHP 8.1: libcrypto.so.1.1: version `OPENSSL_1_1_1' not found

### ISSUE THREAD

**Issue by murphatron** [cloudfoundry/php-buildpack#730]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?
```
{
   "name": "",
   "build": "",
   "support": "",
   "version": 0,
   "description": "",
   "authorization_endpoint": "{private}",
   "token_endpoint": "{private}",
   "min_cli_version": null,
   "min_recommended_cli_version": null,
   "app_ssh_endpoint": "{private}",
   "app_ssh_host_key_fingerprint": "{private}",
   "app_ssh_oauth_client": "ssh-proxy",
   "doppler_logging_endpoint": "{private}",
   "api_version": "2.124.0",
   "osbapi_version": "2.14",
   "user": "{private}"
}
cf version 6.53.0+8e2b70a4a.2020-10-01
```

What version of the buildpack you are using?
v4.4.67

If you were attempting to accomplish a task, what was it you were attempting to do?
Initialize an app using PHP 8.1.  

What did you expect to happen?
Successful build and staging of the app.  

What was the actual behavior?
App compilation error occurred. 
>/tmp/app/php/bin/php: /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1: version `OPENSSL_1_1_1' not found  

Please confirm where necessary:
* [x] I have included a log output
* [x] My log includes an error message
* [x] I have included steps for reproduction

### Logs
```
10:50:14.164: [API.1] Creating build for app with guid e10f7b8b-fd29-4dbe-8253-fe386fba5ea6
10:50:14.604: [STG.0] Cell 9ff5d9a4-728d-40bd-8bd4-5899a80d3bf1 creating container for instance 59353f2d-28ce-4f77-a12b-c19aa1df963d
10:50:15.026: [STG.0] Cell 9ff5d9a4-728d-40bd-8bd4-5899a80d3bf1 successfully created container for instance 59353f2d-28ce-4f77-a12b-c19aa1df963d
10:50:15.365: [STG.0] Downloading app package...
10:50:15.365: [STG.0] Downloading build artifacts cache...
10:50:15.389: [STG.0] Downloaded app package (337B)
10:50:15.391: [STG.0] Downloaded build artifacts cache (216B)
10:50:21.979: [STG.0] -------> Buildpack version 4.4.67
10:50:22.938: [STG.0] Installing HTTPD
10:50:22.938: [STG.0] HTTPD 2.4.54
10:50:24.150: [STG.0] Downloaded [https://buildpacks.cloudfoundry.org/dependencies/httpd/httpd_2.4.54_linux_x64_cflinuxfs3_ebde532e.tgz] to [/tmp]
10:50:24.481: [STG.0] Installing PHP
10:50:24.481: [STG.0] PHP 8.1.11
10:50:27.556: [STG.0] Downloaded [https://buildpacks.cloudfoundry.org/dependencies/php/php_8.1.11_linux_x64_cflinuxfs3_4e981704.tgz] to [/tmp]
10:50:29.645: [STG.0] /tmp/app/php/bin/php: /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1: version `OPENSSL_1_1_1' not found (required by /tmp/app/php/bin/php)
10:50:29.646: [STG.0] Traceback (most recent call last):
10:50:29.646: [STG.0]   File "/tmp/buildpackdownloads/3f0c03c7602ee67512337b56bc424f4b/scripts/compile.py", line 57, in <module>
10:50:29.646: [STG.0]     .from_build_pack('lib/additional_commands')
10:50:29.646: [STG.0]   File "/tmp/buildpackdownloads/3f0c03c7602ee67512337b56bc424f4b/lib/build_pack_utils/builder.py", line 212, in extensions
10:50:29.646: [STG.0]     process_extension(path, ctx, 'compile', process, args=[self])
10:50:29.646: [STG.0]   File "/tmp/buildpackdownloads/3f0c03c7602ee67512337b56bc424f4b/lib/build_pack_utils/utils.py", line 69, in process_extension
10:50:29.646: [STG.0]     success(getattr(extn, to_call)(*args))
10:50:29.646: [STG.0]   File "/tmp/buildpackdownloads/3f0c03c7602ee67512337b56bc424f4b/lib/extension_helpers.py", line 48, in extension_helper_wrapper
10:50:29.646: [STG.0]     return getattr(inst, 'compile')(install)
10:50:29.646: [STG.0]   File "/tmp/buildpackdownloads/3f0c03c7602ee67512337b56bc424f4b/lib/extension_helpers.py", line 154, in compile
10:50:29.646: [STG.0]     self._compile(install)
10:50:29.646: [STG.0]   File "/tmp/buildpackdownloads/3f0c03c7602ee67512337b56bc424f4b/lib/php/extension.py", line 142, in _compile
10:50:29.646: [STG.0]     validate_php_ini_extensions(ctx)
10:50:29.646: [STG.0]   File "/tmp/buildpackdownloads/3f0c03c7602ee67512337b56bc424f4b/lib/compile_helpers.py", line 168, in validate_php_ini_extensions
10:50:29.646: [STG.0]     all_supported =  _get_supported_php_extensions(ctx) + _get_compiled_modules(ctx)
10:50:29.646: [STG.0]   File "/tmp/buildpackdownloads/3f0c03c7602ee67512337b56bc424f4b/lib/compile_helpers.py", line 132, in _get_compiled_modules
10:50:29.646: [STG.0]     raise RuntimeError("Error determining PHP compiled modules")
10:50:29.646: [STG.0] RuntimeError: Error determining PHP compiled modules
10:50:29.657: [STG.0] Failed to compile droplet: Failed to run finalize script: exit status 1
10:50:29.673: [STG.0] Exit status 223
10:50:29.911: [STG.0] Cell 9ff5d9a4-728d-40bd-8bd4-5899a80d3bf1 stopping instance 59353f2d-28ce-4f77-a12b-c19aa1df963d
10:50:29.911: [STG.0] Cell 9ff5d9a4-728d-40bd-8bd4-5899a80d3bf1 destroying container for instance 59353f2d-28ce-4f77-a12b-c19aa1df963d
10:50:32.779: [STG.0] Cell 9ff5d9a4-728d-40bd-8bd4-5899a80d3bf1 successfully destroyed container for instance 59353f2d-28ce-4f77-a12b-c19aa1df963d
```

### Steps to reproduce
1. Clone https://github.com/murphatron/cf-php-buildpack-minimal
2. Login using cf cli.
3. Run `cf push my-cool-app --no-manifest -b https://github.com/cloudfoundry/php-buildpack -s cflinuxfs3 -m 512M -i 1 -p $(pwd) -u process -c "tail -f"`  

This issue was also reported in https://github.com/cloudfoundry/php-buildpack/issues/722 but was closed by the author.  

Another point: This only occurs when specifying PHP 8.1. Deploying with 8.0 or 7.4 will stage successfully without errors.

**Comment by ryanmoran** [comment]
What is the stack that this app was deploying against? `cflinuxfs3` or `cflinuxfs4`?

**Comment by orediggerco** [comment]
@ryanmoran both regions are `cflinuxfs3`. The genesis region still has `cflinuxfs2` but we're specifying `cflinuxfs3` in our `cf push`. The second region only has `cflinuxfs3`.

**Comment by ryanmoran** [comment]
I'm having trouble reproducing this. I've got a brand new CF env with only `cflinuxfs3` installed on it. When I run `cf push my-cool-app --no-manifest -b https://github.com/cloudfoundry/php-buildpack -s cflinuxfs3 -m 512M -i 1 -p $(pwd) -u process -c "tail -f"`, I get a successful build.

I also pulled down the latest stack image from DockerHub and can find the copy of `libcrypto.so.1.1` on the filesystem and confirm that `openssl` 1.1.1 is installed:

```
 ‣ docker run -it -u root cloudfoundry/cflinuxfs3:latest bash
root@8e946fe6da9f:/# find / -name '*libcrypto*'
/usr/lib/x86_64-linux-gnu/libcrypto.so
/usr/lib/x86_64-linux-gnu/pkgconfig/libcrypto.pc
/usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.0
/usr/lib/x86_64-linux-gnu/libcrypto.a
/usr/lib/x86_64-linux-gnu/libcrypto.so.1.1
root@8e946fe6da9f:/# which openssl
/usr/bin/openssl
root@8e946fe6da9f:/# openssl version
OpenSSL 1.1.1  11 Sep 2018
```

Are there any other details about this environment or the stacks that are customized outside of what you get with a vanilla CF installation?

**Comment by carlos-lehmann** [comment]
@ryanmoran we're getting the same error with cflinuxfs3 on a CF with version 0.40.0. On another with 0.242.0 it works fine. 
I know it's a very old version but we can't update the first and need to keep it running for a couple more months. If you could give me any clues on how to solve this via Buildpack (if at all) that would be much appreciated.

**Comment by ryanmoran** [comment]
@carlos-lehmann `0.40.0` and `0.242.0` are `cflinuxfs3` stack versions? If that is the case, I would recommend you update the stack to a modern version. The stack is patched by updating to the latest version, we do not ship any LTS support for any stack image. I'd also advise that this stack (`0.40.0`) has a number of unpatched CVEs against it that should be of concern: https://ubuntu.com/security/cves?q=&package=openssl&priority=&version=bionic&status=released.

**Comment by ryanmoran** [comment]
Given that this has gone quiet and the proposed resolution is to update to a recent stack version, I'm going to close this issue.
