### ISSUE TITLE
Set expose_php to Off

### ISSUE THREAD

**Issue by dmikusa-pivotal** [cloudfoundry/php-buildpack#75]
It's currently set to "On" and that results in PHP adding an X-Powered-By header with the current version number.  [OWASP recommends turning this off](https://www.owasp.org/index.php/PHP_Configuration_Cheat_Sheet#php.ini).

> X-Powered-By: PHP/5.4.38

PHP 5.4 - https://github.com/cloudfoundry/php-buildpack/blob/master/defaults/config/php/5.4.x/php.ini#L375
PHP 5.5 - https://github.com/cloudfoundry/php-buildpack/blob/master/defaults/config/php/5.5.x/php.ini#L375
PHP 5.6 - https://github.com/cloudfoundry/php-buildpack/blob/master/defaults/config/php/5.6.x/php.ini#L366

**Comment by styeung** [comment]
All set! Thanks @dmikusa-pivotal.

**Comment by flavorjones** [comment]
Looks like this was in php-buildpack v3.2.2: https://github.com/cloudfoundry/php-buildpack/releases/tag/v3.2.2
