### ISSUE TITLE
the requested PHP extension pcntl is missing from your system

### ISSUE THREAD

**Issue by natsu90** [cloudfoundry/php-buildpack#78]
I tried to deploy Laravel project using following repo, https://github.com/JKillian/Bluemix-Laravel-Demo
but got above error.

**Comment by dmikusa-pivotal** [comment]
I don't think we include support for pcntl in our PHP binaries at the moment.  It shouldn't be hard to add and include in a future version though.

http://php.net/manual/en/pcntl.installation.php

**Comment by natsu90** [comment]
@dmikusa-pivotal I'm trying on IBM Bluemix, they gave the repo as starter code. What do choice I have? Please advise.

**Comment by dmikusa-pivotal** [comment]
Not sure what to tell you.  We don't have that extension at the moment.  It's certainly something that we can include in the future, but that's not going to help you now.

You could compile your own build of PHP.  If you setup an Ubuntu 14.04 VM and build your version of PHP from source, building in pcntl as a shared library, you could bundle that with the app and install it with a `.profile.d` script.  Certainly not an easy process, but if you must get this running it would work.

For what it's worth I've talked to other people using Laravel with the build pack just fine.  Whatever is requiring this extension seems specific to something about your example.  Perhaps you can just modify the example not to use that extension.  You might also check with the author to see how he or she is running it.

**Comment by flavorjones** [comment]
@natsu90 I'm going to go ahead and close this ticket. If you feel that it's been closed in error, or you'd like to continue the conversation around whether this is a bug or not, please comment.

Thank you!

**Comment by clement360** [comment]
@natsu90 Try running this tutorial https://developer.ibm.com/bluemix/2014/06/17/getting-started-laravel-bluemix/. I recently updated it. (the repo is out dated)

**Comment by flavorjones** [comment]
FWIW, we now support pcntl in the php buildpack. See related:

* https://github.com/cloudfoundry/binary-builder/pull/3
* https://github.com/cloudfoundry/php-buildpack/issues/82

This should work as of v4.0.0.
