### ISSUE TITLE
Release: php-buildpack (Feb)

### ISSUE THREAD

**Issue by arjun024** [cloudfoundry/php-buildpack#788]
Release reminder!
Also make sure you pull in the `Release Reminder` workflow before release so that it automates this issue creation!

**Comment by sophiewigmore** [comment]
PHP module updates have been done already: https://github.com/cloudfoundry/buildpacks-ci/pull/226

**Comment by sophiewigmore** [comment]
https://github.com/cloudfoundry/php-buildpack/releases/tag/v4.5.2
