### ISSUE TITLE
mail() does not work with default stemcell

### ISSUE THREAD

**Issue by mattjcurryas** [cloudfoundry/php-buildpack#79]
the mail() function does not work in the default stemcell because sendmail is missing from the stemcell.

**Comment by dmikusa-pivotal** [comment]
@flavorjones correct me if I'm wrong, but I don't think there's anything the build pack can do about this.  Installing sendmail is not something we could do.

Fortunately there are other ways to send email in PHP without requiring sendmail to be installed.  Sendgrid is one option.  You could also use a smtp library like [PHPMailer](https://github.com/PHPMailer/PHPMailer), if you don't want to depend on a third party like Sendgrid.

Dan

**Comment by mattjcurryas** [comment]
We ended up using PHPMailer and it worked great.  It would probably be useful to document that the mail function does not work by default though.

Matt
