### ISSUE TITLE
PHP App logging

### ISSUE THREAD

**Issue by antonevane** [cloudfoundry/php-buildpack#81]
Hi, I have a question regarding buildpack.
Is there a way to get an access to STDOUT from php app?

I'm trying to attach Slim framework logging to CF log.

**Comment by flavorjones** [comment]
Hi @antonevane,

You should be able to access STDOUT in your `cf logs` or `cf logs --recent` output. Are you having trouble with that?

-m

**Comment by antonevane** [comment]
I want to get an access from my app and write all logging statements.

**Comment by shinji62** [comment]
Two way : 
 Using the PHP io  ```php
<?php
$stdout = fopen('php://stdout', 'w');
?>
```

Or just log message to errorLog , you can use Monolog and the ```ErrorLogHandler``` which will help you.

**Comment by antonevane** [comment]
Thanks
