### ISSUE TITLE
The buildpack should bring its own Python interpreter

### ISSUE THREAD

**Issue by ryanmoran** [cloudfoundry/php-buildpack#814]
In an upcoming release of `cflinuxfs4`, the stack will remove the Python interpreter that is currently available. Since this buildpack is written in Python and therefore relies on a Python interpreter being available, it will need to bring its own interpreter.

An example of how this type of thing can be achieved can be found on this equivalent PR for the Java buildpack: https://github.com/cloudfoundry/java-buildpack/pull/995

**Comment by brayanhenao** [comment]
PR: https://github.com/cloudfoundry/php-buildpack/pull/815
