### ISSUE TITLE
Release: php-buildpack (Mar)

### ISSUE THREAD

**Issue by sophiewigmore** [cloudfoundry/php-buildpack#830]
Release reminder for ${{ github.event.repository.name }}

* Bump PHP modules. See [doc](https://github.com/cloudfoundry/buildpacks-ci/tree/master/scripts/php-modules#pre-buildpack-release-task)
* See [diff from latest version](https://github.com/php-buildpack/compare/v4.5.3..develop) and validate if a release is required.
* Make sure the latest commit on `develop` has passed tests on the [CI](https://buildpacks.ci.cf-app.com/teams/main/pipelines/php-buildpack)
* Refer [release instructions](https://github.com/pivotal-cf/tanzu-buildpacks/wiki/Releasing-CF-Buildpacks). (private link)

**Comment by brayanhenao** [comment]
Release: [v4.6.0](https://github.com/cloudfoundry/php-buildpack/releases/tag/v4.6.0)
