### ISSUE TITLE
Add support for protobuf extension

### ISSUE THREAD

**Issue by libnux** [cloudfoundry/php-buildpack#84]
We use protobuf in our PHP applicaitons. Could you please add support for it? Thanks.

The protobuf extension we used is https://github.com/allegro/php-protobuf/

**Comment by dmikusa-pivotal** [comment]
This is already supported.  It's just not listed on the README.  We'll need to fix that.

For the record, we support the "protobuf" and "protocolbuffers" extensions.

http://php-info.cfapps.io/info.php

**Comment by jtarchie** [comment]
@libnux, we added protobuf in your original request (issue #50). Are you having issues with it? As @dmikusa-pivotal pointed out, the extensions do work in the latest buildpack. However, you'll need to explicitly enable the extension in your `.bp-config/options.json` (or via `composer.json`) for the extension to be loaded.

**Comment by libnux** [comment]
Sorry that I forgot that I've requested the support before.  
As dmikusa-pivotal said, I checked and found that it's not listed on the readme, and then requested again...

**Comment by flavorjones** [comment]
FYI, see Tracker story https://www.pivotaltracker.com/story/show/100244194 to drive out documenting protobuf support.
