### ISSUE TITLE
Ruby is not available in cflinuxfs4

### ISSUE THREAD

**Issue by ryanmoran** [cloudfoundry/php-buildpack#849]
The buildpack contains Ruby code (https://github.com/cloudfoundry/compile-extensions/tree/7540414906a3e842290194a10416e0ffdc0daec6) that it [invokes](https://github.com/cloudfoundry/php-buildpack/blob/9379c01414eb1d70e27a637fb5d357e4b4495ce7/bin/finalize#L41-L43) during the build process.

Now that the `cflinuxfs4` stack no longer contains a Ruby runtime, the buildpack will need to either bring along its own Ruby or be rewritten to run in a way that does not rely upon Ruby being available in the stack.

**Comment by sophiewigmore** [comment]
Resolved by the PR linked above and released in v4.6.2 of the buildpack.
