### ISSUE TITLE
Investigate dependency-builds failures

### ISSUE THREAD

**Issue by sophiewigmore** [cloudfoundry/php-buildpack#865]
The dependency builds pipeline for PHP is currently failing for 8.1 and 8.2 (since April 13). See the following CI builds:
- https://buildpacks.ci.cf-app.com/teams/main/pipelines/dependency-builds/jobs/build-php-8.1.x/builds/55
- https://buildpacks.ci.cf-app.com/teams/main/pipelines/dependency-builds/jobs/build-php-8.1.x/builds/56

We should investigate why these builds are failing and put in a fix so that we can continue to ship timely patches of dependencies in the buildpack

**Comment by brayanhenao** [comment]
Solved in https://github.com/cloudfoundry/binary-builder/pull/73

**Comment by sophiewigmore** [comment]
thank you @brayanhenao!!!!!!!!!

**Comment by sophiewigmore** [comment]
We can close this out once we see the build pipeline go green with your changes

**Comment by sophiewigmore** [comment]
https://buildpacks.ci.cf-app.com/teams/main/pipelines/dependency-builds/jobs/build-php-8.1.x/builds/57
https://buildpacks.ci.cf-app.com/teams/main/pipelines/dependency-builds/jobs/build-php-8.2.x/builds/25
:)
