### ISSUE TITLE
Update HHVM

### ISSUE THREAD

**Issue by dmikusa-pivotal** [cloudfoundry/php-buildpack#88]
Seems like we are a few versions behind on HHVM.

Latest in BP: 3.5.1 & 3.6.1
Latest Avail: 3.8.0 & 3.7.3 & 3.6.5

https://github.com/facebook/hhvm/releases

**Comment by mhoran** [comment]
Hey @dmikusa-pivotal. We have a few stories in our backlog regarding HHVM. We have a couple of concerns with the current packaging model of HHVM.

We don't benefit from the security updates provided by the rootfs architecture with HHVM, because the dependencies are pulled into the buildpack itself. This means that the buildpack has to be rebuilt when security vulnerabilities are discovered in the dependencies, instead of updating the rootfs.

We're also interested to see the usage of HHVM, given the versions have been behind for some time. If there is lots of interest in HHVM we will look into improving the maintenance of the binaries. This may make more sense after we work through some stories around re-architecting the buildpack process, something we're calling the buildpack development kit.

**Comment by dmikusa-pivotal** [comment]
>We don't benefit from the security updates provided by the rootfs architecture with HHVM, because the dependencies are pulled into the buildpack itself. This means that the buildpack has to be rebuilt when security vulnerabilities are discovered in the dependencies, instead of updating the rootfs.

Understood.  Historically they were pulled in that way because lucid64 didn't have dependencies that were up-to-date enough for HHVM.  Given that we're on trusty now, this might not be necessary any more.  

If the rootfs had all the dependencies that would certainly make packaging HHVM easier.  On the other hand, it's got a pretty good number of dependencies.  Out of curiosity, where is the line on what does and doesn't get included in the rootfs?  Is this something we've defined?  How would someone request something be added to the rootfs?  Sorry if these questions are a bit off topic.

>We're also interested to see the usage of HHVM, given the versions have been behind for some time. If there is lots of interest in HHVM we will look into improving the maintenance of the binaries.

You and me both :)  It's always been a pain to maintain and I get the feeling that only a few people use it.

>This may make more sense after we work through some stories around re-architecting the buildpack process, something we're calling the buildpack development kit.

Very cool.  Where can I find out more about this?  Is there an epic for it?

**Comment by mhoran** [comment]
> If the rootfs had all the dependencies that would certainly make packaging HHVM easier. On the other hand, it's got a pretty good number of dependencies. Out of curiosity, where is the line on what does and doesn't get included in the rootfs? Is this something we've defined? How would someone request something be added to the rootfs? Sorry if these questions are a bit off topic.

There's not really a hard line -- it's ultimately up to us now, as we've taken over ownership of the rootfs. However, we do want to keep dependencies minimal as every new package we add to the rootfs is something else we've got to keep up to date. Also, adding a dependency to the rootfs is a "one-way" street. We don't remove packages from the rootfs, as this would not be backwards compatible.

Interestingly, I noticed that you packaged some binaries that did not come from Trusty along side the Trusty HHVM. This seems to work, but is a little odd. Was this on purpose, or did you just bundle the most up to date dependencies? Check out my findings in [Tracker](https://www.pivotaltracker.com/story/show/99169476).

> > This may make more sense after we work through some stories around re-architecting the buildpack process, something we're calling the buildpack development kit.

> Very cool. Where can I find out more about this? Is there an epic for it?

There is an epic in the Buildpacks tracker: [architecture](https://www.pivotaltracker.com/epic/show/1898760). I think we've learned a lot from the extensibility of the PHP buildpack and there many improvements we can make across the board. We've mocked up a new DSL that seems to be working nicely, and are also experimenting with alternative mechanisms for debugging staging and hosting buildpack binaries.

**Comment by dmikusa-pivotal** [comment]
>Interestingly, I noticed that you packaged some binaries that did not come from Trusty along side the Trusty HHVM. This seems to work, but is a little odd. Was this on purpose, or did you just bundle the most up to date dependencies? Check out my findings in Tracker.

I'm not really familiar with HHVM or what it takes to build it, so when I got this working I basically looked at the Heroku build pack and did what they were doing.

https://github.com/heroku/heroku-buildpack-php/blob/master/support/build/hhvm#L38-L54

Unfortunately I have not idea why they're bundling things the way they are.  It could be a requirement of HHVM for specific versions, it could be related to Herkou's platform.  Not sure, sorry.

**Comment by chregu** [comment]
We'd be very interested in an up-to-date HHVM binary. We'll switch soon to CloudFoundry with our setup and HHVM support is paramount to us. We don't need the latest and greatest version as soon as it comes up, but being up to date would be great

If I can help out somewhere, just give me some direction what could be done and I can maybe look into it.

**Comment by Dannyzen** [comment]
@chregu Strictly out of curiosity what benefits do you receive from using HHVM over the traditional PHP binary?

**Comment by chregu** [comment]
It was way faster. With PHP 7 that gap closed almost, so it's not that important anymore for us.

(It also has some nice features with the Hack Language part, but we don't use that either, others may)

To sum up: I'd say PHP 7 support is much more important nowadays, HHVM is a nice to have, some people may want some features from there, but it looks like there aren't too many (or they are not using CF anyway)

And if your resources are limited, go for PHP 7 ;)

**Comment by Dannyzen** [comment]
Thanks for the feedback. If you have any interest in providing feedback on our PHP 7 RFC https://github.com/cloudfoundry/php-buildpack/issues/125 we welcome it.
