### ISSUE TITLE
Update other miscellaneous binaries

### ISSUE THREAD

**Issue by dmikusa-pivotal** [cloudfoundry/php-buildpack#89]
Not a huge deal, but these could be updated:

Apache HTTPD -> 2.4.16 just dropped.  Contains a few [low priority security fixes](http://httpd.apache.org/security/vulnerabilities_24.html) and some bug fixes.

Nginx -> 1.9.3 bug fixes

NewRelic -> 4.23.3.111

**Comment by flavorjones** [comment]
We'll prioritize this work this week!

**Comment by aemengo** [comment]
Check out the work here: https://github.com/cloudfoundry/php-buildpack/commit/e77a71e99c25a52a64a9e9dd0faf791b906db311
