### ISSUE TITLE
How to call cf command line from a PHP script?

### ISSUE THREAD

**Issue by jabrena** [cloudfoundry/php-buildpack#90]
Hi,

I would like to know, how to call some cf methods from php:

Idea:

``` php
<?php
$output = shell_exec('cf apps');
echo "<pre>$output</pre>";
?>
```

Many thanks in advance.

Juan Antonio

**Comment by dmikusa-pivotal** [comment]
Sorry, I don't think this really has much to do with the build pack.  Can you clarify what your expectation is here?  How can we help?

Keep in mind that if you're looking for general advise on PHP programming, you'd be much better served looking on StackOverflow, a PHP forum or PHP mailing list.

**Comment by jabrena** [comment]
Yes, I would like to launch cf commands from a PHP script. Imagine a web document showing the applications deployed in a Cloud Foundry instance. In that case, I need to know how to call

``` shell
cf apps
```

from a PHP document.

Does exist a PHP library to interact with cf commands?

Juan Antonio

**Comment by dmikusa-pivotal** [comment]
What you're asking is a general PHP question and not specific to CF or the PHP build pack.  There's very little difference between launching `cf` and any other external process from PHP.  There's no difference between doing it on your local PC or on an app running on CF.  

That type of question is not appropriate here, we're focused on the PHP build pack which consists mostly of automating the setup of PHP for your app.  I think you should check the PHP docs, StackOverflow or another resource like I mentioned previously.  Look for help / examples on how to launch an external process.  If you can run say `ls` and pull back the directory listing, running `cf` should be very similar.

**Comment by jabrena** [comment]
Ok, many thanks.

I will test the idea. If I continue with doubts, I will use Stackoverflow.
http://stackoverflow.com/questions/tagged/cloudfoundry
