### ISSUE TITLE
Allow configuring a custom NewRelic app name

### ISSUE THREAD

**Issue by dmikusa-pivotal** [cloudfoundry/php-buildpack#92]
The build pack pulls the CF app name and uses that to configure NewRelic.

https://github.com/cloudfoundry/php-buildpack/blob/master/extensions/newrelic/extension.py#L78-L79

In some cases like blue-green deployment this can cause problems.  It would be nice to allow overriding the app name, perhaps via env variable.

**Comment by jtarchie** [comment]
Can a use just set the `newrelic.appname` in a custom `php.ini` file? This way it is persisted with the application code. The problem would be if it was an environment variable, as part of their deployment process now they need to remember to always set the environment variable now.

**Comment by dmikusa-pivotal** [comment]
I don't remember if I tested that, but looking at the code I have a suspicion that it would result in having the setting added into php.ini twice.  This [code](https://emccorp.webex.com/emccorp/lsr.php?RCID=1db8ecf206f87950e9b06baee630edba), looks for a certain location in the php.ini file and inserts the NewRelic config right after that.  It doesn't check to see if it exists and I think it would do that even if you have a custom php.ini.

I'm not sure duplicates would cause an issue, so that might be a workaround, but a full custom php.ini seems like a lot of work to override the build pack's behavior.  It would be nice if the build pack offered more flexibility in this area.  I think a small change like this should suffice.

```
self.app_name = self._ctx.get('NEWRELIC_APPNAME', vcap_app.get('name', None))
```

That should first look at the context for `NEWRELIC_APPNAME`, which could be set as an environment variable or in `.bp-config/options.json`, and if that doesn't exist pull the application name from VCAP_APPLICATION.

**Comment by jvshahid** [comment]
@dmikusa-pivotal it looks like the newrelic php agent supports separate `newrelic.ini` config files. Why not check if one exist and if not create a basic config file with the app name set. That way we give the app developer complete flexibility over how to configure newrelic and not require them to write a full `php.ini` file ?

**Comment by dmikusa-pivotal** [comment]
It seems like NewRelic supports per-directory ini settings and it seems like those should override the global php.ini.  I haven't tested, but given that it would seem like adding a `.user.ini` file with a custom newrelic.app_name should override what the build pack configures.

**Comment by geramirez** [comment]
@dgodd  and I just tested out pushing a .user.ini with

newrelic.appname="Virtual Host 1;All Virtual Hosts"

and all worked as expected.

We have created story: https://www.pivotaltracker.com/story/show/119189143

**Comment by dmikusa-pivotal** [comment]
Awesome!

**Comment by jchesterpivotal** [comment]
For the information of followers, [the story @geramirez referred to](https://www.pivotaltracker.com/n/projects/1042066/stories/119189143) has been completed. 

We now include documentation on these NewRelic configuration items.
