### ISSUE TITLE
update redis version to '2.2.7' to support redis cluster

### ISSUE THREAD

**Issue by libnux** [cloudfoundry/php-buildpack#94]
The redis extension(https://github.com/phpredis/phpredis) included in current php-buildpack is version '2.2.5', and it seems not support redis cluster. 

Is it possible to do an update to '2.2.7' for cluster support? 

Thanks.

**Comment by libnux** [comment]
2.2.7 is the latest stable version for now: https://pecl.php.net/package/redis/2.2.7

**Comment by dmikusa-pivotal** [comment]
Seems like there are a few other extensions that could be updated too:

  - ioncube -> 5.0.14  (major version jump) 
  - mongo -> 1.6.10
  - msgpack -> 0.5.6
  - phalcon -> 2.0.6  (major version jump)
  - suhosin -> 0.9.38
  - twig -> 1.19.0
  - xdebug -> 2.3.3
  - zendopcache -> 7.0.5

**Comment by libnux** [comment]
Sorry... Please hold on this. 

I'm confirming whether phpredis 2.2.7 supports cluster.

**Comment by flavorjones** [comment]
Scheduling this update to phpredis.

**Comment by libnux** [comment]
Thanks. 
However, 2.2.7 still does not support cluster.This feature is still in develop branch.
