### ISSUE TITLE
App specific DOWNLOAD_URL no longer works

### ISSUE THREAD

**Issue by dmikusa-pivotal** [cloudfoundry/php-buildpack#95]
Previously it was possible to set an app specific `DOWNLOAD_URL` in `.bp-config/options.json`.  This allowed the application developer to override the build pack's binaries repository with a custom repository.  Documented [here](https://github.com/cloudfoundry/php-buildpack/blob/master/docs/config.md#optionsjson).

At the moment, you can change the download URL, but it appears to be ignored.

```
2015-08-13 20:55:15,767 [DEBUG] utils - Processing extension from [/tmp/buildpacks/php-buildpack/lib/httpd] with method [compile]
2015-08-13 20:55:15,767 [DEBUG] utils - Loading extension from [/tmp/buildpacks/php-buildpack/lib/httpd]
2015-08-13 20:55:15,768 [DEBUG] utils - line #41 in /tmp/buildpacks/php-buildpack/lib/httpd/extension.py, "compile" is setting [PHP_FPM_LISTEN] = [127.0.0.1:9000]
2015-08-13 20:55:15,768 [DEBUG] cloudfoundry - Installing [HTTPD]
2015-08-13 20:55:15,768 [DEBUG] cloudfoundry - Installing binary from manifest [https://s3.amazonaws.com/dmikusa/php_bp_binaries/httpd/2.4.16/httpd-2.4.16.tar.gz]
Installing HTTPD
Downloaded [https://pivotal-buildpacks.s3.amazonaws.com/concourse-binaries/httpd/httpd-2.4.16-linux-x64.tgz] to [/tmp]
```

Note the difference between the first location, which is crafted from DOWNLOAD_URL and the second URL, which is not.

Is it still possible to do this?

This feature was quite useful for a couple reasons...

 1.) If you're targeting a public cloud and you don't want to use the build pack provided binaries, you can easily change the repo.
 2.) If you're testing new binaries or want custom features for a specific application, you can point to a different repo.
 3.) It makes it easy to switch between a local repo and a remote repo.

Thanks

**Comment by flavorjones** [comment]
I'd frankly prefer to remove the DOWNLOAD_URL feature and allow/force people to customize their manifest for this behavior.

Objections?

**Comment by dmikusa-pivotal** [comment]
My objection, unless I'm missing something, is that this would require someone to fork the build pack.  Some users won't or can't do this, those that do are left with a maintenance burden as they have to pull in upstream changes or risk running with an out-of-date build pack.

Since the point of this change is to control your own binaries, I think the risk of running with an out-of-date build pack is less.  Effectively you're controlling what binaries you use, so it doesn't matter what happens upstream there.  That said, there are still interesting things that happen upstream and you'd have to periodically pull in those changes.

If there is / were a way to modify the manifest without forking that would be ideal and I'd be totally fine with dropping the DOWNLOAD_URL option.  

If that's not something we can support, I'm OK with updating the docs and removing references to DOWNLOAD_URL.  It's clearly been broken for a while and no one else has reported it, so it can't be a feature that many, if any, people are using.

**Comment by jtarchie** [comment]
The philosophy of CloudFoundry is to provide secure, audited, and trackable binaries. If the user wants to opt-in to overriding the binaries they can official fork the PHP buildpack and modify the `manifest.yml`. This way their changes are trackable and obviously different from the officially supported buildpack.

It was decided to [remove support](https://github.com/cloudfoundry/php-buildpack/commit/64cb3b188a4ba7214d202555b8e4748d165fadee) for DOWNLOAD_URL.

**Comment by dmikusa-pivotal** [comment]
Can we reword, this [feature in the README](https://github.com/cloudfoundry/php-buildpack/blob/master/README.md#features) as well?

>download location is configurable, allowing users to host binaries on the same network (i.e. run without an Internet connection)

Perhaps something like "download location is adjustable via a build pack fork, ...".  I just want it to be clear that a fork is required.

**Comment by y9c4lk** [comment]
Can somebody give me an example to change this parameter in the manifest.yml of my php project? Any example? 

Thanks in advance

**Comment by dmikusa-pivotal** [comment]
It's no longer possible to change on a per-project level.  You need to fork the PHP build pack and change this file, not your project's manifest.yml.

https://github.com/cloudfoundry/php-buildpack/blob/master/manifest.yml

Dan

**Comment by y9c4lk** [comment]
Thanks mate!
