### ISSUE TITLE
Bump PHP Modules and Release: php-buildpack (Nov)

### ISSUE THREAD

**Issue by cf-buildpacks-eng** [cloudfoundry/php-buildpack#954]
Release reminder for php-buildpack

* Bump PHP modules. See [doc](https://github.com/cloudfoundry/buildpacks-ci/tree/master/scripts/php-modules#pre-buildpack-release-task)
* See [diff from latest version](https://github.com/cloudfoundry/php-buildpack/compare/v4.6.12..develop) and validate if a release is required.
* Make sure the latest commit on  has passed tests on the [CI](https://buildpacks.ci.cf-app.com/teams/main/pipelines/php-buildpack)
* Refer [release instructions](https://github.com/pivotal-cf/tanzu-buildpacks/wiki/Releasing-CF-Buildpacks). (private link)

**Comment by brayanhenao** [comment]
Modules bump: https://github.com/cloudfoundry/buildpacks-ci/pull/333

**Comment by brayanhenao** [comment]
[v4.6.13](https://github.com/cloudfoundry/php-buildpack/releases/tag/v4.6.13) Released.
