### ISSUE TITLE
missing shared objects for extensions

### ISSUE THREAD

**Issue by jistok** [cloudfoundry/php-buildpack#97]
PHP Warning:  PHP Startup: Unable to load dynamic library '/tmp/staged/app/php/lib/php/extensions/no-debug-non-zts-20131226/apc.so' - /tmp/staged/app/php/lib/php/extensions/no-debug-non-zts-20131226/apc.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/tmp/staged/app/php/lib/php/extensions/no-debug-non-zts-20131226/apcu.so' - /tmp/staged/app/php/lib/php/extensions/no-debug-non-zts-20131226/apcu.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/tmp/staged/app/php/lib/php/extensions/no-debug-non-zts-20131226/xml.so' - /tmp/staged/app/php/lib/php/extensions/no-debug-non-zts-20131226/xml.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/tmp/staged/app/php/lib/php/extensions/no-debug-non-zts-20131226/xmlwriter.so' - /tmp/staged/app/php/lib/php/extensions/no-debug-non-zts-20131226/xmlwrit

**Comment by aemengo** [comment]
These warnings are the result of your php application requesting extensions that are not provided by the buildpack. This is either being done directly through specification in your `.bp-config` options, or indirectly through the dependencies of your composer extensions. You can read more details about this in this Github issue: https://github.com/cloudfoundry/php-buildpack/issues/93

The cloudfoundry buildpack team has already made some fixes that should alleviate this issue: https://www.pivotaltracker.com/story/show/100180478. They will be present the next release of the PHP buildpack.

**Comment by jistok** [comment]
sounds right - tho the documentation here should be updated as both apc and
apcu are listed at the bottom as supported:

https://github.com/cloudfoundry/php-buildpack

**Comment by aemengo** [comment]
How unfortunate. I have just put a story in to rectify the documentation. We'll address it soon. Thank you for bringing it to our attention.

**Comment by dmikusa-pivotal** [comment]
>PHP Warning: PHP Startup: Unable to load dynamic library '/tmp/staged/app/php/lib/php/extensions/no-debug-non-zts-20131226/apc.so' - /tmp/staged/app/php/lib/php/extensions/no-debug-non-zts-20131226/apc.so: cannot open shared object file: No such file or directory in Unknown on line 0
>PHP Warning: PHP Startup: Unable to load dynamic library '/tmp/staged/app/php/lib/php/extensions/no-debug-non-zts-20131226/apcu.so' - /tmp/staged/app/php/lib/php/extensions/no-debug-non-zts-20131226/apcu.so: cannot open shared object file: No such file or directory in Unknown on line 0

These two extensions are only available for PHP 5.4.  [apc is quite old](https://pecl.php.net/package/apc) with the last general release being in 2011.  [apcu has never had a GA release with the last beta being in 2014](https://pecl.php.net/package/apcu).

The build pack supports the [ZendOpcache](https://pecl.php.net/package/zendopcache) which is actively developed and [xcache](http://xcache.lighttpd.net/) which is also actively developed.  I'd suggest using one of these code caches instead.

>PHP Warning: PHP Startup: Unable to load dynamic library '/tmp/staged/app/php/lib/php/extensions/no-debug-non-zts-20131226/xml.so' - /tmp/staged/app/php/lib/php/extensions/no-debug-non-zts-20131226/xml.so: cannot open shared object file: No such file or directory in Unknown on line 0
>PHP Warning: PHP Startup: Unable to load dynamic library '/tmp/staged/app/php/lib/php/extensions/no-debug-non-zts-20131226/xmlwriter.so' - /tmp/staged/app/php/lib/php/extensions/no-debug-non-zts-20131226/xmlwrit

These don't need to be loaded as external extensions.  [The functionality is compiled into PHP itself](http://php-info.cfapps.io/info.php).

@aemengo  - Correct me if I'm wrong, but I believe there is a story to have the build pack filter out requests for extensions like this, so these warnings will go away.

**Comment by flavorjones** [comment]
@aemengo @dmikusa-pivotal @jistok These warnings will go away once code from https://www.pivotaltracker.com/story/show/100180478 is in a release. This should be in the next day or so.

@aemengo's newly-created story for updating docs is https://www.pivotaltracker.com/story/show/101861998

**Comment by flavorjones** [comment]
Fixed behavior will be in php-buildpack 4.1.0, follow here for status: https://www.pivotaltracker.com/story/show/102019942
