### ISSUE TITLE
Extensions not working

### ISSUE THREAD

**Issue by decanus** [cloudfoundry/php-buildpack#99]
![image](https://cloud.githubusercontent.com/assets/7621705/9502930/51b6d09c-4c34-11e5-96ca-66259851e312.png)

**Comment by flavorjones** [comment]
Thanks for letting us know.

These messages are misleading; these extensions are compiled into our PHP (and are not modules), and these error messages were intended to let people know about modules that aren't being loaded.

Can you confirm for me that these modules are in fact working, and that it's simply that these warning messages are incorrect and confusing?

**Comment by dmikusa-pivotal** [comment]
@flavorjones - did something change recently?  Those weren't compiled in previously.  curl, redis, mongo and openssl were all separate extensions.

**Comment by flavorjones** [comment]
@dmikusa-pivotal yes: #93 / https://www.pivotaltracker.com/story/show/100180478

**Comment by decanus** [comment]
@flavorjones They are not working, php is giving me errors that Redis cannot be found

**Comment by flavorjones** [comment]
@aemengo Is looking into this now. It's only in the git repo; we haven't shipped the buildpack yet. @decanus is likely pushing with the `cf push -b` option pointed at the github repo.

**Comment by decanus** [comment]
![image](https://cloud.githubusercontent.com/assets/7621705/9503109/5144c398-4c35-11e5-90d8-03841d8a576a.png)
@flavorjones Indeed I am, When will it be shipped on Git?

**Comment by flavorjones** [comment]
@decanus we were about to release 4.1.0 when you opened this ticket; now we're going to wait until we figure out what's going on. ;)

**Comment by decanus** [comment]
@flavorjones Ok, anyway I can repush my app with the older buildpack? Currently my live app is no longer working

**Comment by flavorjones** [comment]
Yes, you can re-push with https://github.com/cloudfoudry/php-buildpack#v4.0.0 to get the current release.

**Comment by decanus** [comment]
thanks

**Comment by dmikusa-pivotal** [comment]
I'm seeing the same issue with a test app.  Looking at the output of `cf files`, I do see the extensions.  They're just not enabled in `php.ini`.  That's with the #develop branch.

**Comment by aminjam** [comment]
@decanus We are unable to reproduce this. Can you give us steps to reproduce this error?

**Comment by decanus** [comment]
```buildpack: https://github.com/cloudfoundry/php-buildpack.git``` In manifest.yml

```"PHP_VERSION": "{PHP_56_LATEST}",
  "PHP_EXTENSIONS": ["curl", "openssl", "redis", "mongo"],```
In options

And then a standard CF push is what I did

**Comment by decanus** [comment]
![image](https://cloud.githubusercontent.com/assets/7621705/9504404/b569bf02-4c3c-11e5-88ca-564570dad01b.png)
Here is the full log output from Jenkins

**Comment by aemengo** [comment]
Thank you for your patience with this. The issue was that we made a
critical change to the buildpack for only the php version 5.5.x series but
have not accommodated the other versions. We will get this rectified as
soon as we can.

**Comment by cf-buildpacks-eng** [comment]
Please note that earlier today we reverted the commits that caused this on
the master branch, so pushes that use the github URL should be fine again.
